.github/workflows/build-desktop.yml

GitHub recently completed their rollout of Ubuntu 20.04 and pointed `ubuntu-latest` to those agents. This is causing the Linux version to be linked with a newer version of `glibc`, which can lead to errors on Ubuntu 18.04 and Debian 10.
Fixes #628 
N/A

fix(ci): Build Linux on Ubuntu 18.04

---

packages/shared/components/inputs/Dropdown.svelte
packages/shared/routes/dashboard/wallet/views/LineChart.svelte

When selecting values from the timescale dropdown above the charts the drop down changes size depending on the option selected. This new option for the dropdowns makes sure the components is sized to always allow the max length item by measuring the values in the dropdown.

feat: Option for dropdowns to size to their max content length

---

packages/shared/components/inputs/Pin.svelte
packages/shared/routes/dashboard/settings/views/Security.svelte
packages/shared/routes/setup/protect/views/Pin.svelte

Use the proper pin control in settings instead of a password box. This introduces a smaller version of the pin control which matches the style of standard inputs.
Also add error support for pin control, and corrects where the errors appear when validating the pin values.
Fixes https://github.com/iotaledger/firefly/issues/458
Tested on windows.

fix: Use pin control in settings

---

packages/shared/components/popups/Index.svelte

At the moment continuously tabbing around a popup then moves the focus behind the popup shield.
This captures the focus within the popup.
Fixes https://github.com/iotaledger/firefly/issues/625

fix: Capture the tab focus inside the dialog popup

---

packages/desktop/App.svelte

The scroll bar width is very small and hard to click on, this increases the width.
Fixes https://github.com/iotaledger/firefly/issues/647

fix: Scroll bars too small to click on

---

packages/shared/components/AccountTile.svelte

If the account name overflows the account tile width we use ellipsis. see pic
Fixes https://github.com/iotaledger/firefly/issues/650
Tested on windows with long account names

fix: Add ellipsis to account name on tile if it overflows

---

packages/shared/lib/helpers.ts
packages/shared/locales/en.json

When the diff for the last backup date was calculate it assumed less than 1 day means today, this can also mean yesterday so additional check is in place.
Fixes https://github.com/iotaledger/firefly/issues/723
Tested on windows with backup less than 24 hours old

fix: Last backup date within 24 hours

---

packages/shared/lib/utils.ts
packages/shared/locales/en.json
packages/shared/routes/dashboard/wallet/views/Send.svelte

When no account has been selected for an internal transfer the send is disabled.
Improves bech32 error reporting
Fixes https://github.com/iotaledger/firefly/issues/715

fix: disable send no account

---

packages/shared/components/inputs/Input.svelte
packages/shared/components/inputs/Password.svelte
packages/shared/routes/setup/Password.svelte

We now disallow using the cut/copy/paste on password controls.
Also improves the error handling on password page during setup
Fixes https://github.com/iotaledger/firefly/issues/702

fix: Disable contextmenu password

---

packages/shared/lib/app.ts
packages/shared/routes/dashboard/wallet/Wallet.svelte

On a send/internalTransfer completion we would reset the wallet routes and go back to the main view. If you had already navigated somewhere else this then navigated away from what you were viewing.
This removes the router reset, as even under normal circumstances you might want to make additional transfers so navigating away makes less sense.
Fixes https://github.com/iotaledger/firefly/issues/734
Tested on windows navigating to another location when transferring

fix: Don't reset the wallet route on a transfer completion

---

packages/desktop/App.svelte
packages/desktop/electron/preload.js
packages/shared/components/popups/ErrorLog.svelte
packages/shared/lib/electron.ts
packages/shared/lib/errors.ts
packages/shared/lib/shell/errorLogger.ts
packages/shared/lib/shell/walletApi.ts
packages/shared/lib/shell/walletErrors.ts
packages/shared/lib/wallet.ts

The error log was handled in the walletApi which is in the shell preload code, so it did not have access to the svelte reactive error log. However, it did persist into local storage so was available after a restart.
Now the error reporting is hooked by the main app so that background errors propagate through the hook to the main window. Also separated the backend and frontend shared logic to make it clearer who is responsible for what.
Fixes https://github.com/iotaledger/firefly/issues/537

fix: Error log is not available until after restart

---

packages/desktop/tsconfig.json
packages/shared/components/inputs/Amount.svelte
packages/shared/components/inputs/Input.svelte
packages/shared/lib/i18n.ts
packages/shared/lib/units.ts
packages/shared/tsconfig.json

Now uses the selected locale to find out the decimal separator instead of always using "."
The libs in tsconfig are updated as they otherwise don't know about FormatParts api.
Also fixes allowing overwriting value when content is at max length
Allows pasting of valid numbers only.
Fixes https://github.com/iotaledger/firefly/issues/639 https://github.com/iotaledger/firefly/issues/704 https://github.com/iotaledger/firefly/issues/670 https://github.com/iotaledger/firefly/issues/701 https://github.com/iotaledger/firefly/issues/632
Tested on windows in german

fix: Get decimal separator from locale

---

packages/desktop/electron/preload.js

The save dialog for stronghold now enforces the `.stronghold` extension.
Fixes https://github.com/iotaledger/firefly/issues/539
Tested on windows trying to save with different extension will still append stronghold.

fix: Enforce stronghold extension of save dialog

---

packages/shared/lib/helpers.ts
packages/shared/locales/en.json
packages/shared/routes/dashboard/wallet/views/CreateAccount.svelte
packages/shared/routes/dashboard/wallet/views/ManageAccount.svelte
packages/shared/routes/setup/Setup.svelte

Improves the robustness of account and profile name validation.
Also fixes the getInitials when there were runs of whitespace in the name.
Fixes https://github.com/iotaledger/firefly/issues/296 https://github.com/iotaledger/firefly/issues/649 https://github.com/iotaledger/firefly/issues/719
Tested on windows with lots of different account names with odd characters, emojis, whitespace etc

fix: Improve account and profile name validation

---

packages/shared/components/inputs/Dropdown.svelte

The inner div of the dropdown had colors changed when it was disabled, this wasn't needed as the whole control had an opacity set, which resulted in making the inner content hard to read. The inner text color changes have been removed.
Added keyboard and focus support.
Fixes https://github.com/iotaledger/firefly/issues/716
Tested on windows in light and dark mode.

fix: Dropdown disabled contrast

---

packages/shared/components/inputs/Amount.svelte
packages/shared/components/inputs/Input.svelte

The amount drop down for units it was not styled like other dropdowns.
Also adds keyboard support.
Fixes https://github.com/iotaledger/firefly/issues/631

fix: Style the amount drop down like other dropdowns

---

packages/shared/components/popups/Index.svelte

If a popup dialog has no controls other than the close button it triggered an exception trying to auto set focus. e.g. The error log when there and no entries, only the close button is available to focus.
Tested on windows with empty error log

fix: Exception setting focus when dialog has no controls other than close

---

packages/shared/lib/marketData.ts
packages/shared/routes/dashboard/wallet/Wallet.svelte
packages/shared/routes/dashboard/wallet/views/LineChart.svelte

Update chart data based on active profile currency. 
After a currency change, if the previously selected chart currency is not available anymore on the list, it will fallback to USD. 
Fixes issue #681.
Electron Linux

fix: update chart data based on active profile currency

---

packages/shared/lib/appUpdater.ts

The app updater did not retain the infinite timeout when showing the "ready to install" notification so it disappeared too quickly. The notification now stays until dismissed.
Fixes https://github.com/iotaledger/firefly/issues/672

fix: App updater notification disappears too quickly

---

packages/shared/components/inputs/Amount.svelte
packages/shared/components/inputs/Input.svelte

Add fiat currency conversion on the amount field
Related to #763 (not sure we will implement sending fiat directly).
Electron Linux

feat: add fiat currency conversion on the amount field

---

packages/desktop/electron/main.js

Although there was an icon for the AppImage the executable itself did not show an icon in title bar/docks.
Fixes https://github.com/iotaledger/firefly/issues/730
Test on ubuntu
The highlighted area was empty before this fix

fix: Add icon for linux app

---

packages/shared/routes/dashboard/wallet/views/Send.svelte

If the send/transfer page was already open when deleting an account it did not populate the parameters. A subscription to `sendParams` now guarantees external changes are updated on the display.
Fixes https://github.com/iotaledger/firefly/issues/627

fix: Update display if sendParams updated externally

---

packages/shared/lib/password.ts
packages/shared/locales/en.json
packages/shared/routes/dashboard/settings/views/Security.svelte
packages/shared/routes/setup/Password.svelte

The password error display looked up the zxcvbn warning to create a localizable key, not all messages were in the lookup table so we ended up with `undefined` for the key. The code has some additional lookups, but also a fallback mechanism if a message can not be found.
Fixes https://github.com/iotaledger/firefly/issues/711

fix: Fallback if password error message not found

---

packages/shared/routes/setup/import/views/BackupPassword.svelte

During backup onboarding the import password doesn't allow an enter keypress to submit the form, this fixes that issue.
Fixes https://github.com/iotaledger/firefly/issues/785

fix: Allow the backup password to be submitted with enter

---

packages/shared/components/inputs/Pin.svelte
packages/shared/routes/login/views/EnterPin.svelte
packages/shared/tailwind.config.js

On the PIN entry page entering 6 digits now automatically submits instead of having to click continue.
Fixes https://github.com/iotaledger/firefly/issues/332
Tested on windows with correct and incorrrect PINs.

feat: Auto submit the pin instead of having to click continue

---

packages/shared/lib/helpers.ts

The `truncateString` helper functions that displays the abbreviated addresses aaa...zzz was passed a null or undefined parameter, which triggered an exception. 
This fixes the exception in the helper, but the real question is why was the address in the payload empty!
Fixes https://github.com/iotaledger/firefly/issues/797

fix: Truncate string now behaves when the string is null or undefined

---

packages/desktop/App.svelte
packages/shared/components/ActivityDetail.svelte
packages/shared/components/inputs/Dropdown.svelte
packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
packages/shared/routes/dashboard/wallet/views/AccountNavigation.svelte
packages/shared/routes/dashboard/wallet/views/Security.svelte
packages/shared/routes/dashboard/wallet/views/WalletActions.svelte
packages/shared/routes/dashboard/wallet/views/WalletHistory.svelte

Reduce the visible width of the scroll bar but maintain the active area around the visible part.
Some element may need to apply the `scroll-secondary` or `scroll-tertiary` styles if they are on a different background color to the default.
Tested on windows in light and dark mode

feat: Reduce scroll bar width but maintain active area

---

packages/shared/lib/wallet.ts

The notification message for transfer assumed the order of the messages confirming, this PR looks at the content of the payloads to work out which accounts sent/received the transfer.
Fixes https://github.com/iotaledger/firefly/issues/624

fix: Corrects the order of the accounts in the transfers notification message

---

.github/ISSUE_TEMPLATE/config.yml
packages/desktop/App.svelte
packages/desktop/electron/preload.js
packages/shared/components/popups/DeleteProfile.svelte
packages/shared/lib/electron.ts
packages/shared/lib/helpers.ts
packages/shared/lib/profile.ts
packages/shared/routes/setup/Congratulations.svelte
packages/shared/routes/setup/Setup.svelte

If you exit the app during profile creation it leaves debris in the storage folder, so that any subsequent attempts to use the same profile name fail.
The in progress profile name is now persisted in the app storage and removed when a profile is completely setup. If on app start this value is still set it removes the folder.
This might have been the cause of multiple issues people were having if they got an error during setup and restarted the app.
Tested on windows with aborting the profile creation process at various stages.

fix: Cleanup in progress profiles

---

packages/shared/components/TitleBar.svelte

On windows the draggable region of the title bar overlapped the resize portions of the window. This reduces the size of the draggable region to provide access to the resize regions.
Fixes https://github.com/iotaledger/firefly/issues/695

fix: Inset the draggable title bar so it does not overlap resize areas

---

packages/desktop/App.svelte
packages/desktop/electron/lib/appUpdater.js
packages/desktop/electron/preload.js
packages/shared/components/popups/Version.svelte
packages/shared/lib/appUpdater.ts
packages/shared/lib/electron.ts

The app now checks in the background every 15 mins if there is a new version, the update check is also triggered if someone opens the version popup.
Fixes https://github.com/iotaledger/firefly/issues/673

fix: Regularly checks for new version while app is open

---

packages/shared/routes/dashboard/wallet/views/WalletHistory.svelte

- Remove alert on manual syncs from the wallet tab
Tested on Mac

fix: dont display sync alert from wallet tab

---

packages/shared/components/popups/Password.svelte
packages/shared/routes/dashboard/settings/views/Security.svelte

This PRs aims to fix PR #805 where there is no password validation before trying to export stronghold. 
N/A
Instructions:
- Go to settings > security > export backup
- Enter a wrong password: the popup should validate it and show you an error
- Enter a correct password: the popup should close and the backup should export succesfully
OS: Ubuntu 18.04

fix: validate password before trying to export stronghold

---

packages/shared/lib/profile.ts
packages/shared/lib/wallet.ts
packages/shared/routes/setup/Setup.svelte

If you start to create a new profile and then select "Import", go back and click "Create" you can trigger an exception. This is because if the `initialise` method is called twice in quick succession the RocksDB is still locked from the first creation.
This PR only tries to call the initialize again if the profile name has changed when you navigate in and out of those screens.
Also if the name has changed the previous actor will be cleaned up.
There was an additional exception that could be triggered if you backed all the way out of a create because the actor was still active and not cleaned up when the in progress profile was removed.

fix: Onboarding exception when switching modes

---

packages/shared/components/popups/Backup.svelte
packages/shared/locales/en.json

For the export stronghold popup this PR checks the password is correct and shows and inline error instead of a notification popup if it is incorrect. Also the popup controls are shown as busy while the export is in progress.

fix: Improve the control flow when exporting stronghold

---

packages/shared/lib/chart.ts
packages/shared/routes/dashboard/wallet/views/LineChart.svelte

If you are in account view and you logout an exception is triggered in the chart currency formatting. This is because as the views are torn down the activeProfile is no longer available and so the currency is undefined.

fix: Fixes the exception in chart when there is no longer an active profile

---

packages/shared/components/ActivityDetail.svelte

Activity details displays the sender as `null`, this is because the casing of the UTXO input type changed from `UTXO` to `Utxo` so the input lookup for the senders in the payload fails.
This also explains the underlying issue with https://github.com/iotaledger/firefly/pull/798

fix: Utxo type name case changed so sender could not be found

---

packages/shared/routes/setup/Legal.svelte

The colour of the scroll bar for the legal onboarding page was not updated to use the new styling.
Tested on windows in light and dark mode

fix: Scroll bar on legal onboarding page incorrect colour

---

packages/shared/lib/wallet.ts
packages/shared/locales/en.json
packages/shared/routes/dashboard/wallet/Wallet.svelte

When you transfer the whole amount between 2 accounts you only receive one confirmation from the wallet library, this is because there is actually only one message to confirm.
To remedy this instead of waiting for the second message with the same id we track the details at the initiation of the internal transfer. This means we have the details for both accounts when the message confirmation is received. 
If you logout before an internal transfer completes this tracked information will be lost, under these conditions we use the internal flag of the payload to determine it was an internal transfer and display a new message without the account names.
In addition we scan all the messages stored for the wallet to set the confirmed flag, not just the account referenced in the payload.
To avoid …

fix: Internal transfer for whole amount not confirming

---

packages/shared/components/popups/Diagnostics.svelte

If the settings for nodes were set to Manual Selection and then you show diagnostics an exception was triggered. This was due to it referencing some config settings that no longer exist.

fix: Exception in diagnostics when manual node mode selected

---

packages/shared/lib/helpers.ts

The getTrimmedLength method didn't account for the regex match not finding any characters and called .length on a null value.
Fixes https://github.com/iotaledger/firefly/issues/835

fix: Get trimmed length triggers exception when only whitespace

---

packages/shared/routes/dashboard/settings/views/Security.svelte

Added keyboard handlers for submission of password and pin in settings.
Fixes https://github.com/iotaledger/firefly/issues/847

fix: Allow password and pin settings to be submitted with keyboard

---

packages/shared/lib/typings/events.ts
packages/shared/lib/wallet.ts
packages/shared/routes/dashboard/wallet/Wallet.svelte

When a new address was generated it was not added to the address history, so any future balances changes could not find the address to store the relevant information. 
The typing for balance update event was incorrect so balance updates were never reflected live in the address history.
Fixes https://github.com/iotaledger/firefly/issues/828

fix: Address history is kept up to date with incoming data

---

packages/shared/components/inputs/Address.svelte
packages/shared/components/inputs/Dropdown.svelte
packages/shared/routes/dashboard/wallet/Wallet.svelte
packages/shared/routes/dashboard/wallet/views/Send.svelte

If someone enters an address belonging to one of the internal accounts internally we automatically switch to an internal transfer.
The `Address` and `Dropdown` components now have an `autofocus` property which is set on Send/Internal Transfer instead of the value amount.

fix: Internal address transfer

---

packages/shared/components/ActivityDetail.svelte
packages/shared/lib/chart.ts
packages/shared/lib/wallet.ts

Due to self transactions missing messages (from acc A to acc A) the portfolio/account chart algorithm was not correctly calculating balances. Now we filter out self transactions from chart algorithms.
Additionally the logic to display the message detail has been improved
N/A
Self transactions should not compute to the charts as they dont change the balance.
You can test sending some transaction to yourself.
Myself: tested on Linux Ubuntu 18.04

Feat: filter out self transactions from chart algorithms

---

packages/desktop/README.md

On Linux, Firefly relies on the freedesktop.org Secrets API being implemented by the secrets manager that is installed on the system. This commit addresses this requirement in the desktop readme file.
Fixes #852.
- Documentation Fix
I am running Manjaro KDE, a system that currently does not come with an implementation of the freedesktop.org Secrets API. After installing `keepassxc`, the issue described in #850 was fixed.

[Docs] Add information about required Secrets API implementation on Linux

---

packages/backend/bindings/node/native/Cargo.lock

This PR addresses two issues:
- We have revised use of change addresses and syncing to ensure multi-device use works cleanly. We separate change and public address indexes and always generate the latest unused change for sending transfers. 
- When the node had pruned outputs a flaw in the logic led to balance increasing to 18.4Pi.
Fixes #845, #648
tested on Mac

fix: revise use of change addresses and balance fix

---

packages/shared/components/popups/DeleteProfile.svelte
packages/shared/lib/app.ts

When deleting a profile the stronghold could be in an unlocked state, logout locks the stronghold as one of its steps. However because the delete profile did not wait for this completion callback it tried to perform cleanup operations at the same time.
The changes now make the logout an async call so it can be waited on for completion. Other uses of logout have no following processes so behave the same as they always did.
From fresh Firefly
* Create profile 1
* Create profile 2
* Delete profile 2 - confirm storage folder for profile 2 has been removed
* Login to profile 1 - Sync happens and completes successfully
* Delete profile 1 - App return to welcome screen and confirm storage folder for profile 1 has been …

fix: Wait for logout completion before cleaning up profile

---

packages/backend/bindings/node/native/Cargo.lock

- Sync change addresses when used as an input in a transaction
- Ensure outputs are marked as spent
- Use the milestone confirmation to determine the timestamp of messages
Fixes #865
Tested on Mac

fix: syncing and transaction timestamp fixes

---

packages/shared/lib/wallet.ts

If a sync was in progress at the same time as a new transaction arrived the message was not saved, if the sync data did not contain the new message it was lost forever. It looks like this check was put in place to make sure we didn't end up with duplicates messages i.e. in the sync data and the new transaction event. This also meant that we missed notifications more new transactions as sync doesn't do any message notification.
Instead of not doing any updates if syncing this PR will save and notify, but the save will check to see if it already has the message before adding it again.
This reverses some of the changes made in https://github.com/iotaledger/firefly/pull/523/files
Fixes https://github.com/iotaledger/firefly/issues/862 …

fix: New transaction disappears if syncing at same time as arrival

---

packages/shared/components/TitleBar.svelte

The windows maximize icon always filled white in light theme instead of the background color.

fix: Windows maximize icon color does not match background

---

packages/shared/lib/typings/routes.ts
packages/shared/routes/dashboard/settings/views/Advanced.svelte

Hide the settings and navigation for General->Profile and Advanced Settings->State Export until they are implemented.
Fixes https://github.com/iotaledger/firefly/issues/830

fix: Hide the settings profile and export state entry until implemented

---

packages/desktop/App.svelte
packages/desktop/electron/main.js
packages/desktop/public/about.html

The padding top and bottom of the native about dialog is increased along with the height, the width is also increased to maintain the golden ratio.
This also disables image dragging for about and the main app.
Fixes https://github.com/iotaledger/firefly/issues/837

fix: Increase the padding for native About dialog

---

packages/shared/routes/dashboard/wallet/Wallet.svelte

When a new account is created any internal transfer you send is not marked as `internal` as the underlying response coming back from the wallet lib does not set the flag. If you logout/login then they are successfully marked as internal. This points to an underlying issue in wallet lib.
This PR will always flag internal transfer as true which overrides the value that comes back from wallet.rs.
Fixes https://github.com/iotaledger/firefly/issues/863

fix: Always mark internal transfers as true

---

packages/shared/lib/profile.ts
packages/shared/lib/router.ts
packages/shared/routes/dashboard/wallet/Wallet.svelte
packages/shared/routes/dashboard/wallet/views/WalletHistory.svelte

When initially syncing an imported profile increase the gap limit parameter to read a larger number of addresses.
Also increase the gap limit for first manual sync in any session.

fix: Larger initial gap limit for syncing when importing

---

packages/shared/lib/bech32.ts
packages/shared/lib/utils.ts
packages/shared/locales/en.json
packages/shared/routes/dashboard/wallet/views/Send.svelte

The current bech32 validation only checks that the correct character set and format is used, but does not validate the checksum. If you send with an address with an invalid checksum the wallet lib throws an invalid action type exception and you get a "Something went wrong" error.
This PR now verifies the checksum within the bech32 address to guarantee it is valid, the send can then not fail on that address.
In addition the recent change to the order of the amount and address inputs means the validation was performed in the wrong order.
The Bech32 implementation is a copy of the fully unit tested implementation from https://github.com/iotaledger/iota.js/tree/chrysalis
Fixes https://github.com/iotaledger/firefly/issues/899
Tested on …

fix: Improve bech32 validation

---

packages/shared/lib/wallet.ts
packages/shared/routes/setup/Password.svelte

During setup if you navigate past the password stage and then click back you cannot change the password as the stronghold password has already been set.
With this change if a password has already been set in the stronghold `changePassword` is called instead of `setPassword`
Fixes https://github.com/iotaledger/firefly/issues/878

fix: Setup change password

---

packages/shared/components/Button.svelte

The hover effect on the Create button uses the width to animate, this means that any content with spaces tries to wrap. See the video in https://github.com/iotaledger/firefly/issues/902
To fix we apply no wrap to the hover button style.
Fixes https://github.com/iotaledger/firefly/issues/902
Test on windows in Korean

fix: Hover button tried wrapping when content had spaces

---

packages/shared/lib/utils.ts

The time and date used in the stronghold backup filename does not take into account local time zone.
Test on windows from Africa timezone

fix: Stronghold backup time in local time format

---

packages/desktop/App.svelte
packages/shared/lib/marketData.ts
packages/shared/locales/en.json
packages/shared/routes/dashboard/wallet/views/LineChart.svelte

Localization was not applied everywhere during onboarding as the loading of the json was not waited to complete before applying.
In addition the market data timeframe drop down was not localized.
Fixes https://github.com/iotaledger/firefly/issues/890
Test on windows with onboarding in German

fix: Localization during onboarding, localize timeframe dropdown

---

packages/shared/components/Idle.svelte

Although the idle timer was removed in `onDestroy` the events were debounced so they could still call the idle handler after destroy.
Tested on windows with slower debounce

fix: Make sure destroyed Idle component is not triggered from debounce

---

packages/shared/lib/wallet.ts
packages/shared/routes/dashboard/wallet/Wallet.svelte

When account metadata was loaded the loop exited when it reached the account index which was the same as the number of accounts. The accounts sometimes do not come from the wallet in index order, so this loop aborted early.
This fix makes sure all values are taken into account, and sorts the accounts based on their index in other location to make sure similar situations do not occur.
Tested on windows with a stronghold backup which had unsorted accounts.

fix : Invalid balance calculation

---

packages/backend/bindings/node/native/.cargo/config.toml

The `-mmacosx-version-min=` flag needs to be passed to the compiler when building for macOS, otherwise the app will only run on the macOS version it was compiled for (and later). This is 10.15 (Catalina) and later in our case. This PR sets the minimum macOS version to 10.12 (Sierra). It's important to note that only macOS Mojave (10.14) and later still receive security updates from Apple.
Fixes #897 
Before:
```
otool -l /Applications/Firefly\ Beta.app/Contents/Resources/app.asar.unpacked/public/build/index.node| grep LC_BUILD_VERSION -A7
cmd LC_BUILD_VERSION
cmdsize 32
platform 1
minos 10.15
sdk 10.15.6
ntools 1
tool 3
version 609.8
```
(minimum OS 10.15)
After:
```
otool -l index.node | grep LC_VERSION_MIN_MACOSX -A3
cmd …
```

fix(backend/bindings/node): Set min macOS version to 10.12

---

packages/shared/lib/wallet.ts

When a balance update was received if the address was not one that was recognised the balance was discarded. Instead the address is added to those for the account.

fix: Balance update did not record balances for missing addresses

---

packages/shared/routes/dashboard/wallet/views/Send.svelte

If you only have 2 accounts and your perform an internal transfer from account 2 to account 1, on completion the form gets reset and the second dropdown is disabled but is also set to account 1.
Also the account balances shown in the dropdown do not update after tx confirmation.
This PR improves the logic for selecting the accounts and the values in the dropdowns.

fix: Send to account locks and resets dropdown

---

packages/shared/lib/currency.ts
packages/shared/lib/units.ts

The precision used in token formatting was incorrect, instead of passing the dp for the unit type it rounded.
e.g. 55590605665 was converted to 55590.606 Mi instead of 55590.605665 Mi
Tested with value with high `i` precision.

fix: The precision used in the token formatting was incorrect

---

packages/shared/components/popups/BalanceFinder.svelte
packages/shared/routes/dashboard/wallet/Wallet.svelte
packages/shared/routes/dashboard/wallet/views/WalletHistory.svelte

Now that we perform wider searches on the number of accounts reduce the gapLimit so that sync doesn't take as long.

fix: Reduce gap limits now that we have wider account discovery

---

packages/shared/routes/dashboard/wallet/views/Send.svelte

With two accounts if you internal transfer all tokens from account 1 to account 2, hide account 2, then go back into send it reied to set back to internal, which it cant with only one account.

fix: Reset the send route if only one account

---

packages/shared/components/popups/BalanceFinder.svelte
packages/shared/routes/dashboard/settings/views/Advanced.svelte

Balance finder only requires password when stronghold is locked.
Removes double separator around balance finder in settings.

Fix: Balance finder password

---

packages/shared/routes/Splash.svelte

This PR aims to prevent the following screenshot from happening 
N/A
Tested on Ubuntu 18.04

fix: css splash animation not keeping responsive aspect ratio

---

packages/shared/locales/en.json
packages/shared/routes/setup/import/Import.svelte

Add error to seedvault import when file is empty/corrupted
Fixes issue #967
1. Create an text file with a name `whatever.kdbx` or something similar.
2. Import/migrate new wallet using that file
3. Enter password and see the error

feat: add seedvault error message when file is empty/corrupt

---

packages/shared/lib/currency.ts

In some languages the group separator for currency is not found until the test number is larger
e.g in Polish 1111 does not yield the separator, with 1111111 it does
Also added fallbacks for group and decimal separators in case they still are not found.
Test on windows in polish

fix: The number format group separator is not present until numbers are larger

---

packages/shared/locales/en.json
packages/shared/routes/dashboard/settings/views/Security.svelte

The autolock drop down values were not localised.

fix: Missing auto lock localisation

---

packages/shared/components/ActivityDetail.svelte
packages/shared/components/ActivityRow.svelte
packages/shared/lib/wallet.ts
packages/shared/locales/en.json

When a transaction has a remainder the lookups for the activity details did not produce the correct display.
Adds localisation to `Legacy Network`
Tested on windows with multiple internal, external transaction with and without remainders.

fix: Activity detail did not show full details when there was a remainder

---

packages/shared/components/ActivityDetail.svelte
packages/shared/components/ActivityRow.svelte
packages/shared/lib/wallet.ts

For an internal transfer with a reminder the order of addresses meant that sometime the sender account was shown instead of the receiver account. The sender account is now excluded unless there is no other option.

fix: The order of addresses determined which account was displayed

---

packages/shared/lib/shell/walletApi.ts
packages/shared/lib/wallet.ts
packages/shared/routes/dashboard/wallet/Wallet.svelte
packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte

Do not show error notifications for chrysalis node DNS issues. Areas where this is done are address generation, individual account sync and node settings. 
N/A

feat: hide error notifications for chrysalis node dns issues

---

packages/desktop/App.svelte
packages/desktop/electron/preload.js
packages/shared/lib/electron.ts
packages/shared/lib/profile.ts
packages/shared/lib/wallet.ts

Any profiles that have stored folders but are not listed in the app, or listed in the app but have no stored data are cleaned up.
This eliminates debris that cant be caused from failed signups or interruptions.

feat: Cleanup profiles not in app or with no data

---

packages/shared/components/inputs/Input.svelte
packages/shared/components/inputs/Password.svelte
packages/shared/locales/en.json

Displays a caps lock indicator on password input to stop people incorrectly typing passwords in the wrong case.
Fixes https://github.com/iotaledger/firefly/issues/996 https://github.com/iotaledger/firefly/issues/1021

feat: Display a caps lock indicator on password input

---

packages/shared/lib/currency.ts

In languages where the currency formatting started with the currency part and then already included a literal it triggered an exception in the code to insert literals where there wasn't one.
e.g. Portugese Brazilian
Fixes https://github.com/iotaledger/firefly/issues/1005
Tested with all languages

fix: Currency with literal caused exception

---

packages/shared/components/ActivityDetail.svelte
packages/shared/components/ActivityRow.svelte

The styling for the activity rows in dark mode didn't use the account color.
In addition the dark mode transaction details used white on colored background for the account initials which was hard to read.
Tested on windows in dark mode

fix: Activity row dark more styling

---

packages/desktop/package.json

- Improve display of error messages (#1041)
- Display macOS version instead of Darwin kernel version (#1041)
- Do not show error screen for uncaught errors in the renderer process (#1041)

chore(desktop): Bump version to 1.1.1

---

packages/shared/components/popups/BalanceFinder.svelte

The layout of the balance finder popup is incorrect when a password is required.
Updated to

fix: Balance finder with password layout is incorrect

---

packages/shared/lib/chart.ts
packages/shared/lib/typings/message.ts
packages/shared/lib/wallet.ts
packages/shared/routes/dashboard/wallet/Wallet.svelte

When a message with a null payload was encountered an exception was triggered. The app now safely handles messages with no payloads.
**We still need to understand why wallet.rs sent them in the first place**
Tested on windows with a deliberately modified message with no payload.

fix: Empty payloads cause exception

---

packages/desktop/index.js
packages/desktop/webpack.config.js

Renames desktop root level main.js to index.js. The former is confusing given its use in Electron preload.
- Refactor
Starts on Mac

chore: rename entrypoint to index

---

packages/backend/bindings/node/index.ts
packages/shared/lib/network.ts
packages/shared/lib/networkStatus.ts
packages/shared/lib/profile.ts
packages/shared/lib/typings/account.ts
packages/shared/lib/typings/bridge.ts
packages/shared/lib/typings/client.ts
packages/shared/lib/typings/node.ts
packages/shared/lib/typings/wallet.ts
packages/shared/lib/validator.ts
packages/shared/lib/wallet.ts

To keep up with changes involving node authentication in wallet.rs, it's necessary to change the type definitions and others relevant parts of the internal library.
No issue
Tested on:

fix: JWT auth

---

packages/shared/lib/migration.ts
packages/shared/routes/setup/ledger/views/Balance.svelte

1. Display (latest) legacy address on the UI (balance screen). Makes it easier for testers to copy the legacy address and receive funds to it;
2. Log all generated addresses on console. 
Note: This is only temporarily added for testing purposes. 
N/A

feat: display legacy address on the UI

---

packages/desktop/package.json
yarn.lock

This PR updates hw-iota-app to its (current) latest version. No need to use the fork anymore. 
N/A
Manually tested by building and generating address for legacy ledger IOTA app.

chore: update hw-app-iota to latest

---

packages/desktop/electron/lib/Ledger.js
packages/shared/lib/app.ts
packages/shared/lib/migration.ts
packages/shared/routes/dashboard/wallet/views/Security.svelte
packages/shared/routes/dashboard/wallet/views/Send.svelte
packages/shared/routes/setup/Balance.svelte
packages/shared/routes/setup/ledger/views/AccountIndex.svelte
packages/shared/routes/setup/ledger/views/Connect.svelte
packages/shared/routes/setup/migrate/views/Migrate.svelte
packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte

- Close Ledger connection on the js side after finishing getting migration data 
- Remove unnecessary ledger connection status calls
- Unify connection status polling to one global dashboard item in Security
Fixes #1264 
Tested on Mac

fix: ensure js Ledger connection is closed and other fixes

---

packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte

On bundle mining the legacy tx popup was closing too late
N/A
Ubuntu 18.04, Ledger Nano S firmware 2.0.0

Fix: Close tx legacy popup during bundle mining 

---

packages/shared/lib/ledger.ts
packages/shared/lib/typings/ledger.ts
packages/shared/locales/en.json
packages/shared/routes/setup/Balance.svelte
packages/shared/routes/setup/ledger/views/AccountIndex.svelte
packages/shared/routes/setup/migrate/views/Migrate.svelte
packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte

Add toast errors during ledger legacy migration.
_Note: timeout does **not** work on simulator as the simulator doesnt error out_
N/A
Ubuntu 18.04. Tested on real Ledger Nano S & Simulator (see note on "Description of change")

Feat: Add ledger legacy migration toast errors

---

packages/backend/Cargo.lock
packages/backend/bindings/node/native/Cargo.lock
packages/shared/lib/migration.ts
packages/shared/lib/typings/migration.ts

Instead of just checking the inputs returned by wallet library for ledger migration data, also check spend statuses and balance.
N/A

hotfix: keep track of spent addresses during (ledger) migration

---

packages/shared/lib/router.ts
packages/shared/routes/setup/ledger/Ledger.svelte

Fix ledger routing. Before, import from firefly ledger was using the legacy migration route
N/A
Ubuntu 18.04. Ledger simulator

reinitialize ledger route onMount

---

packages/shared/routes/setup/Congratulations.svelte

Add ledger iota app connection check to ledger migration congrats view. This way, we make sure the user reaches the dashboard with the new ledger iota app open, since the last one it had open during migration was the legacy one
N/A
Ubuntu 18.04. Ledger Simulators.
To test, run a ledger simulation and other profile creations to make sure the prompt is only added to ledger legacy migration. 

Feat: check for new ledger app open after migration 

---

packages/shared/components/inputs/Number.svelte
packages/shared/lib/typings/ledger.ts
packages/shared/routes/setup/ledger/views/AccountIndex.svelte

Adds new error type and prevents user from changing account index and page while on that page (which helps prevent the address-index mismatch).
None

fix: Mismatch address-index pair

---

packages/shared/routes/dashboard/Dashboard.svelte

The index pop up was being shown for all ledger profiles. This PR ensures that it is only displayed (once) for migrated profiles. 
N/A

hotfix: only display transaction index pop up for migrated ledger profiles

---

packages/shared/lib/migration.ts
packages/shared/lib/validator.ts
packages/shared/locales/en.json
packages/shared/routes/dashboard/Dashboard.svelte

The aim of this PR is to remove everything around checking when Chrysalis was finally upgraded. This made sense when we first released as Chrysalis was going to be bootstrapped one week after the Firefly release, but not anymore.  
N/A
Ubuntu 18.04

Feat: Remove chrysalis network upgrade checks and notification

---

packages/shared/lib/ledger.ts

- Bundle mining strips the checksum from the TRANSFER... address
- 9 further characters were being stripped again to leave an address length of 72 and yielding incorrect addresses and checksums displayed in ledger migration
Tested on Mac with mined and unmined bundles

fix: ensure correct address display for mined bundles

---

packages/shared/components/popups/Index.svelte
packages/shared/components/popups/LedgerMigrateIndex.svelte
packages/shared/locales/en.json

- Update ledger index migration popup buttons
- Add missing `forceClose` logic to shared X close button and `Escape` key
N/A
Ubuntu 18.04

Feat: update ledger index migration popup buttons

---

packages/shared/components/popups/LedgerConnectionGuide.svelte
packages/shared/components/popups/LedgerTransaction.svelte

- Fix last slide jumping on ledger connection guide
- add missing scroll on ledger transaction popup
N/A
Ubuntu 18.05

Fix: some CSS

---

packages/shared/components/popups/LedgerNotConnected.svelte
packages/shared/lib/ledger.ts
packages/shared/routes/dashboard/Dashboard.svelte
packages/shared/routes/dashboard/wallet/Wallet.svelte
packages/shared/routes/dashboard/wallet/views/Security.svelte
packages/shared/routes/dashboard/wallet/views/Send.svelte

When trying to send funds or generate an address from the dashboard, if ledger was not connected, the ledger status poll was not working because it was colliding with the always running poll that comes from the Security view.
In this PR in introduce a way to interrupt an existing poll and also add a reactive declaration on the dashboard to resume the poll if it was interrupted (wallet poll had to be moved to Dashboard.svelte to ensure a new poll could resume even out of the security view)
N/A
Ubuntu 18.04. Ledger Simulator
Enter dashboard with ledger disconnected and send some funds or generate a new address. Connectin popups should work as expected and the dashboard poll should keep working as …

Fix: dashboard ledger prompt

---

packages/shared/locales/en.json
packages/shared/routes/setup/ledger/views/AccountIndex.svelte

- Shows tooltip to make sure user's device is generating addresses and advises what to do if it isn't
Tested tooltip appearance and disappearance in conjunction with disconnecting device etc.

fix: show account index tooltip immediately when checking for balance

---

packages/shared/routes/dashboard/Dashboard.svelte

The busy state timeout was attempting to close the account index popup post-migration and eliciting a prevent close error.
Tested by simulating busy and account index popup and closure

fix: stop prevent close error on account index popup 

---

packages/shared/lib/wallet.ts
packages/shared/routes/dashboard/Dashboard.svelte

Fixes the issue where the migration stays spinning forever despite the migration bundle being confirmed. 
N/A
Manually tested with ledger device

hotfix: reset migration listeners state when all event listeners are destroyed on the active actor

---

packages/shared/lib/app.ts

This PRs adds the force flag to logout close popups to prevent scenarios like the following 
N/A
Ubuntu 18.04. Logout with a freshly migrated profile which shows the index popup. Do not close it and wait for the Idle component to reach inactivity timeout and logout. The popup should be closed (like all)

Fix: force close popups on logout

---

packages/shared/routes/dashboard/Dashboard.svelte
packages/shared/routes/setup/Balance.svelte
packages/shared/routes/setup/migrate/views/Migrate.svelte
packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte

This PR adds the missing unsubscription that was causing the ledger migration to run multiple times `dispatch('next')` which was causing the Congratulations view to be skipped (only happening for happy ledger migrations). 
N/A
Ubuntu 18.04. Ledger Nano S happy migration

Fix: Ledger migration skipping congratulations view

---

packages/shared/routes/dashboard/settings/views/SettingsHome.svelte
packages/shared/routes/dashboard/settings/views/SettingsViewer.svelte

Remove Migrate Ledger Index setting from non ledger profiles: 
N/A
Login into a ledger profile and a software profile

Fix: remove MigrateLedgerIndex from non ledger profiles

---

packages/shared/routes/dashboard/wallet/views/WalletHistory.svelte

This PR fixes a bug where once transactions have been synced on restored profiles, the initial sync message pops up every subsequent time the user manually syncs the wallet history.
None

fix: New profile transaction history 

---

packages/shared/components/popups/LedgerNotConnected.svelte
packages/shared/lib/ledger.ts
packages/shared/routes/dashboard/Dashboard.svelte
packages/shared/routes/dashboard/wallet/Wallet.svelte
packages/shared/routes/dashboard/wallet/views/Send.svelte

This PR simplifies the ledger connection status polling to ensure no more than one poll is ever active, and that the poll is started and stopped at the correct points.
Tested with log statements and all scenarios involving ledger device polling.

fix: simplify ledger status polling

---

packages/shared/lib/migration.ts

- If a spent Ledger bundle was mined more than once and the old mined bundle was more secure than the new one, the old one was selected for send
- This caused an `cannot read inputs of undefined` error in the `prepareMigrationLog` function due to the state mismatch
Fixes issue #1309
Tested with multiple mined bundles

fix: multi-mined ledger bundles

---

packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte

If you disconnect from internet while migration multiple bundles (software account), the busy state isn't properly set. This PR fixes the issue. 
N/A

hotfix: correctly set busy state during migration

---

packages/shared/routes/dashboard/wallet/views/CreateAccount.svelte

For ledger accounts, if you try to add a new account (provided that the previous account has no history), it fails silently. This PR fixes the issue by making sure that error notification is displayed. 
N/A

hotfix: ensure error notification is displayed on account creation

---

packages/desktop/electron/preload.js

When listing the profiles, we call `readdirSync` on the `__storage__` directory. On the first startup, this directory does not exist, so an error is thrown:
For our purposes of listing the profiles, we can simply return an empty array.
N/A

fix(desktop): Handle missing profile storage path on first start

---

packages/desktop/scripts/notarize.macos.js

Notarization can now be skipped on macOS by setting an environment variable (`MACOS_SKIP_NOTARIZATION=true`)
N/A
N/A

chore(desktop): Allow notarization to be skipped with env var

---

packages/backend/Cargo.lock
packages/backend/Cargo.toml
packages/backend/bindings/node/index.ts
packages/backend/bindings/node/native/Cargo.lock

Firefly has been pointed at the `firefly-testing` branch of [`wallet.rs`](https://github.com/iotaledger/wallet.rs) for a while. While I think versions are the best option to use (easier to be consistent, has more semantic meaning than a commit, etc.), using the same revision as `wallet.rs` would be good. 
To be more specific, `wallet.rs` currently uses the commit `5f8fd262526aa09e2f548b3711964ea8fc18bc0b` for `iota.rs`, which _does_ contain different code. Firefly __must__ also use this revision so that the bindings can compile. Using versions and or commit revisions will alleviate this although it'll be important to make the sure Firefly and `wallet.rs` are using the __same__ version of `iota.rs`.
In summary:
- Changes the following dependencies in `packages/backend/Cargo.toml`:
- …

hotfix: `wallet.rs` branch

---

packages/shared/lib/shell/walletApi.ts
packages/shared/routes/setup/import/Import.svelte

This PR fixes the message on empty or corrupt stronghold import, it was being displayed `Your password is incorrect`
Fixes #967 (#974 already fixed it for seedvault but this PR is for stronghold)
- Create new profile > import file backup
- Use an empty stronghold or a corrupt one: message should be `The backup file was not recognised.`
- Use a correct stronghold with wrong password: message should be `Your password is incorrect.`

Fix: Wrong error message on empty/corrupt stronghold import

---

packages/shared/routes/dashboard/settings/views/Advanced.svelte

Removes "bad" code from `Advanced.svelte` settings page.
N/a
Tested on:

hotfix: Unneeded code

---

packages/shared/components/popups/Index.svelte

This PRs adds the `clickOutside` action to the `Popup` component to be able to be closed (if possible) when you click outside of it. 
_Requested by UX_
N/A
Ubuntu 20.04.

Feat: allow close popup on click outside

---

packages/shared/components/popups/SwitchNetwork.svelte
packages/shared/lib/network.ts
packages/shared/routes/dashboard/settings/views/Advanced.svelte

Fixes some errors in logic around network configuration, namely:
- Un-checking "Include official nodes" will remove all nodes from the last even if they aren't official (__should ONLY__ remove official ones)
- Add fallback / reversion for profile if network switch fails after updating client options and removing wallet accounts
None
Tested on:

fix: Network node list

---

.github/workflows/build-desktop.yml

We should use the exact platforms instead of using `latest` on the workflow that builds Firefly so that we can switch on our own timeline. There may be slight differences between the environments that could introduce potential issues.
N/A
N/A

chore(ci): Avoid using latest to specify CI platforms

---

packages/shared/lib/shell/walletApi.ts

Fix error message to display string instead of {}, in the walletApi.
Partially fixes issue here: https://github.com/iotaledger/firefly/issues/1433

fix: empty receive task error message

---

packages/backend/bindings/node/index.ts

Due to [the way the poll function is used](https://github.com/iotaledger/firefly/blob/9e136e56a5a16bf4f83b2c32718bd0a440ead02d/packages/backend/bindings/node/index.ts#L72) when sending messages to the backend, poll always returns after destroying the actor. There's no real reason to fundamentally refactor the approach here so we can instead swallow the associated error message.
Fixes #1433 
Tested on Mac dev

fix: swallow receiving on a closed channel error

---

packages/desktop/electron/main.js

We currently use `os.release()`, but on macOS this gives us the Darwin version, which then needs to be mapped to a major release of macOS. This PR uses `sw_vers -productVersion` to get the exact macOS version, as this may help debug issues in the future. It also allows us to get the macOS version without needing to add another entry to the map when a new one is released.
N/A

update(desktop): Get more accurate OS version info on macOS

---

packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
packages/shared/routes/dashboard/wallet/views/WalletHistory.svelte

Currently the popup to unlock Stronghold only shows if you sync from the dashboard view. If you try sync from an address view it doesn't ask for the password to unlock Stronghold and generate addresses in syncing.
This PR fixes this issue.
Fixes https://github.com/iotaledger/firefly/issues/1519
Tested on Mac for software and Ledger profiles.

fix: ensure stronghold password is requested if locked when syncing account history

---

packages/shared/components/popups/StakingManager.svelte
packages/shared/lib/participation/api.ts
packages/shared/lib/participation/stores.ts
packages/shared/lib/wallet.ts
packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte

This PR also ensures that newly sent participation messages are added to the local application state.
Manually

Keep track of pending participations

---

packages/shared/lib/participation/api.ts
packages/shared/lib/participation/stores.ts
packages/shared/lib/wallet.ts

Removes code related to maintenance of pending participations. It is no longer needed as we need to maintain only account ids which we are already maintaining.
N/A

fix: remove code related to maintenance of pending participations

---

packages/shared/routes/dashboard/wallet/views/Send.svelte

`$account` is not defined if you try to send directly from the dashboard and it was causing a crash. 

fix: ensure there is no crash when you are sending funds

---

packages/shared/routes/setup/Profile.svelte

When creating a new profile, the profile is initialised after you press next on the create profile page (name and devprofile selection). If they press back after they have already submitted this page, they can change the options (i.e. name and devprofile checkbox). However, it was only deleting the old acter and reinitialising the wallet if the name had changed. This fix makes it so that it happens if the name is changed or the checkbox changes.
Manually.

fix: make change of dev profile checkbox persistent

---

packages/backend/Cargo.lock
packages/backend/Cargo.toml
packages/backend/bindings/node/native/Cargo.lock
packages/backend/bindings/node/native/Cargo.toml
packages/backend/src/lib.rs
packages/shared/components/popups/AddressHistory.svelte
packages/shared/components/popups/BalanceFinder.svelte
packages/shared/locales/en.json

- Fixes balance finder
- Adjusts logic to increase gap limit rather than account index
- Adjust address history to include index and address type
Fixes #1629
Tested with address generation script and using faucet to distribute balance

fix: fix balance finder and adjust address history 

---

.github/workflows/build-desktop.yml

Updates the "verify download" link in the release notes template to point to the wiki. The redirect from `chrysalis.docs.iota.org` is currently not working due to SSL cert issues.
N/A
N/A

chore(ci): Update "verify download" link in release notes template

---

packages/desktop/electron/lib/menu.js
packages/shared/routes/dashboard/settings/views/Help.svelte

The chrysalis documentation was moved from https://chrysalis.docs.iota.org to https://wiki.iota.org/learn/networks/iota-1.5-chrysalis. I changed the url to the chrysalis documentation in the help section and menu bar.
[Discord](https://discord.com/channels/397872799483428865/817057519062614016/920012018805776395)

fix: correct url to chrysalis documentation

---

packages/shared/components/inputs/Amount.svelte

Fixes some broken logic around IOTA -> fiat conversions if the amount is zero.
None
Tested on: 

fix: zero value fiat conversion

---

packages/backend/Cargo.lock
packages/shared/lib/shell/walletApi.ts

This PR covers the following:
- Update the cargo lock file;
- Display a proper (readable) error in error log if the node doesn't have participation plugin enabled
N/A

feat: display a proper node error if participation plugin is not available

---

packages/shared/components/popups/DeleteProfile.svelte
packages/shared/locales/en.json
packages/shared/routes/dashboard/settings/views/Security.svelte

Add an more specific error message when attempting to delete a profile where 1 or more accounts is non empty.
Manually on MacOS

fix: improve error message when trying to delete a non empty profile

---

packages/shared/components/Text.svelte
packages/shared/components/popups/StakingConfirmation.svelte

The logic for disabling UI elements based on the airdrops an account was participating in was incorrect (in `popups/StakingConfirmation.svelte`).
None
Tested on:

fix: airdrop selection for partial stake

---

packages/shared/components/popups/StakingManager.svelte
packages/shared/lib/participation/stores.ts
packages/shared/routes/dashboard/staking/views/StakingSummary.svelte

Account list UI disappears for partial stake items if more than one (only in specific part of the staking / unstaking flow).
None
Tested on:

fix: partial staking UI disappearing

---

packages/shared/components/inputs/Amount.svelte
packages/shared/lib/currency.ts

The amount input component fails to convert values for IOTA and fiat.
None
Tested on: 

fix: amount input

---

packages/shared/components/AccountTile.svelte
packages/shared/components/BalanceSummary.svelte
packages/shared/components/SpentAddress.svelte
packages/shared/components/StakingIndicator.svelte
packages/shared/components/Tooltip.svelte
packages/shared/components/TransactionItem.svelte
packages/shared/routes/dashboard/staking/views/StakingSummary.svelte

This PR aims to refactor the `Tooltip` component and its usage. You dont need to calculate the bounding boxes of the parent anymore, just have to pass an `anchor` component from which the `Tooltip` will position relative to. 
N/A
Ubuntu 20.04. Desktop.
I tried covering all the cases and refactor all its usage.

Feat: refactor tooltip component

---

packages/shared/components/Sidebar.svelte
packages/shared/lib/router.ts
packages/shared/routes/dashboard/settings/Settings.svelte

Added a store to keep track of the previous tab. This way when closing settings etc we don't need to default to the wallet tab home view, we can just go to the previous tab as expected by the user.
Manually on MacOS

fix: make close settings go back to previous tab

---

packages/shared/lib/network.ts

Issue was that staking wasn't loading when the profile was new, until the user went to the networking settings. This was because when the profile is first created it doesn't set any of the official nodes in the official network config to the primary node. I added some code to select a random one as the primary node.
Tested manually on MacOS by recovering a profile using a 24 word mnemonic.

fix: set primary node on new profile

---

packages/shared/components/popups/StakingManager.svelte
packages/shared/lib/participation/participation.ts
packages/shared/lib/participation/types.ts
packages/shared/routes/dashboard/staking/views/StakingSummary.svelte

This fix prevents a user from staking on an account while the account has an unconfirmed transaction.
Tested Manually on MacOS, by sending internal and external transactions and visiting the staking page as soon as they are sent or pending in account. 
Test cases:
- All empty accounts
- All empty accounts with pending transactions
- Some non empty accounts each with pending transactions
- Some non empty accounts with some have pending transactions
- All non empty accounts with some have pending transactions
- All non empty accounts all with pending transactions
- All non empty accounts with partially staked account having pending transaction
Make sure to provide instructions for …

fix: prevent staking on an account while it has unconfirmed transactions

---

packages/desktop/electron/main.js

Added `wiki.iota.org` to the allow list. Hopefully fixes the "Read the documentation" button in the `Help & Information` section.

fix: Restore functionality for button to documentation

---

packages/shared/components/AccountTile.svelte
packages/shared/components/ActivityRow.svelte
packages/shared/components/Button.svelte
packages/shared/components/ButtonCheckbox.svelte
packages/shared/components/StakingAirdropIndicator.svelte
packages/shared/components/icon/Index.svelte
packages/shared/components/popups/Index.svelte
packages/shared/components/popups/StakingConfirmation.svelte
packages/shared/components/popups/StakingManager.svelte
packages/shared/components/popups/Transaction.svelte
packages/shared/routes/dashboard/staking/Staking.svelte
packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte
packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
packages/shared/routes/dashboard/wallet/views/ManageAccount.svelte

- Improve staking view for very wide screens
- General CSS polish on the staking project panes
- Avoid staking animation jump
- Bugfix SVG slow CSS color transition
- Refactor CSS in `AcountTile`: moved from inline to tailwind scss
- Set `yellow-600` for warning and `orange-500` for staking tx
- Update account tile colors and partial staking manager according to latest UI
- Fix account tile name overflow
- Fix text overflows in airdrop selection
- Align updating wallet text on manage Account view 
- Move autofocus on popup to first element to avoid selecting content buttons
N/A
- Update (a change which updates existing functionality): UI
Ubuntu 20.04. Desktop. Test on resolutions from minimum (1280x720px) up to 4k (3840x2160px)

Feat: Polish staking UI

---

packages/shared/routes/dashboard/staking/Staking.svelte

If the node does not return the participation overview while the staking manager is open it can lead to unexpected behaviour when you e.g. hit stake. This PR will automatically close the popup if we enter the inactive staking event (i.e. where a connection to the node couldn't be made)
Tested by disconnecting internet while staking manager is open

fix: close popup on inactive state

---

packages/backend/Cargo.lock
packages/shared/components/AccountTile.svelte
packages/shared/components/StakingAirdropIndicator.svelte
packages/shared/components/StakingIndicator.svelte
packages/shared/components/popups/StakingManager.svelte
packages/shared/lib/network.ts
packages/shared/lib/participation/participation.ts
packages/shared/lib/participation/staking.ts
packages/shared/lib/participation/stores.ts
packages/shared/lib/participation/types.ts
packages/shared/lib/units.ts
packages/shared/locales/en.json
packages/shared/routes/dashboard/staking/views/StakingSummary.svelte

- Adds safe object property access with optional chaining (fixed `ReferenceError` bug with `Cannot read property index of undefined`)
- Adds tooltip in `StakingManager` if account will not reach min rewards for either airdrop (with calculated amount of IOTAs still needed to stake to reach min)
- Changes tooltip text for `StakingIndicator` if events are ended and no account has reached minimum
- Fixes missing store variable reset statements inside `resetParticipation()`
- Cleans up some empty `import` statements
None
Tested on: 

fix: minimum reward time

---

packages/shared/routes/dashboard/staking/views/StakingSummary.svelte

Block staking if the wallets are currently being synced (either through manual sync or from initial load, not background syncing)
Tested manually on Mac

update: block staking if wallets are currently syncing

---

packages/shared/routes/dashboard/wallet/views/Send.svelte

This PR fixes the bug where if a user is in a locale that uses "," as the decimal separator, the `Amount.svelte` component displays the number using "." upon MAX click.
None
Platforms:
Test cases:
- Enter zero and non-zero (including near-zero like `1i`) amounts
- Enter amounts / click MAX for IOTA denominations _and_ profile's selected fiat currency.
- Select different languages and currencies to use for a profile and test the above cases ^

fix: decimal separator in amount

---

packages/desktop/App.svelte
packages/shared/components/Sidebar.svelte
packages/shared/components/modals/ProfileActions.svelte
packages/shared/lib/router.ts

Refactor openSettings function into router lib
use new function for the electron event handler for clicking the settings button.
Manually on MacOS

fix: electron settings menu saves previous tab

---

packages/shared/components/AccountTile.svelte
packages/shared/components/Tooltip.svelte

Fix persistent tooltip on `AccountTile` warning icon click.
⚠️  Please note this is only a patch. Svelte is not destroying the `Tooltip` when its parent `AccountTile` is destroyed and the `Tooltip` is being displayed. Will investigate further and find a better solution.
N/A

Feat: Patch persistent tooltip bug

---

packages/shared/routes/dashboard/wallet/views/ManageAccount.svelte

A condition for disabled state of save button was added, now it will be disabled if the alias input value is equal to account existing alias
- Go to customize wallet screen
- Save button should be disabled
- Add any character at the input
- Save button should be enabled
- Delete the characters added
- Save button should be disabled

Fix: Disable Save button on customise wallet if name has not been changed

---

packages/shared/components/Sidebar.svelte
packages/shared/lib/participation/stores.ts
packages/shared/lib/typings/profile.ts
packages/shared/routes/dashboard/staking/Staking.svelte
packages/shared/routes/dashboard/wallet/views/Send.svelte

This PR aims to:
- Store per profile the first visit on the staking view
- Display the staking sidebar notification when detecting partially staked accounts
N/A

Feat: Show staking sidebar notification per profile and on partial stake

---

packages/backend/bindings/node/index.ts
packages/shared/lib/migration.ts
packages/shared/lib/typings/migration.ts
packages/shared/lib/wallet.ts
packages/shared/routes/setup/ledger/views/GenerateNewAddress.svelte

Generating migration address for ledger was erroring out. This PR fixes the issue. 
N/A
- Tested manually by generating migration address. 
- Did not test generating migration address during the bundle mining & bundle creation process (but it still is passing id so it should work fine)

fix: use account ID instead of index when getting migration address for ledger

---

packages/shared/components/AccountTile.svelte
packages/shared/components/ActivityRow.svelte
packages/shared/routes/dashboard/wallet/views/WalletHistory.svelte

This PR aims to fix 2 reactivity issues:
- Transactions not showing as confirmed in the profile transactions overview. This reactivity issue must have had other effects like new transactions not being displayed in this view if they appear for the first time when you are on this view
- Unstake wallet kept showing in yellow with the below minimum warning.
N/A
- Unstake wallet by sending all its funds and wait in the dashboard profile overview until it shows unstaked
- Move funds between wallets and wait in the dashboard profile overview until it gets confirmed and is not greyed out

Fix: reactivity not working in wallet txs overview & below minimum account tile

---

packages/shared/components/popups/StakingManager.svelte
packages/shared/lib/participation/participation.ts
packages/shared/lib/participation/staking.ts
packages/shared/lib/wallet.ts
packages/shared/locales/en.json

This PR:
- Adds additional logic to disable UI for staking if an account has pending transactions and isn't currently being actioned to stake or unstake
- Fixes CSS to align "Merge" and "Unstake" buttons for partially staked accounts
None
Platforms:
Cases:
- Sending internal transfer and staking / unstaking other accounts
- Sending internal transfer and merging partially staked funds

fix: disable accounts with pending transactions

---

packages/shared/locales/ja.json
packages/shared/routes/dashboard/staking/views/StakingInfo.svelte

This PR:
- Fixes the logic for determining which zen guy animation to display in the `StakingInfo` tile.
- Fixes punctuation typo in the Japanese locale (`shared/locales/ja.json`)
None
Platforms:
Cases:
- Staking one account for both Assembly and Shimmer 
- Staking two accounts: one for Assembly and the other for Shimmer

fix: zen guy for both airdrops

---

packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte

Some UI logic to add extra styling for the remaining airdrop time display uses the existence of a whitespace whereas some locales may not include whitespaces between the number and counter (e.g. "50 Days" is "50日" in Japanese).
None
Platforms:
Cases:
- View staking dashboard for locales that both use do NOT use whitespaces a number and counter (e.g. English vs. Japanese)

fix: use locale agnostic UI logic

---

packages/shared/locales/en.json

Syncs source strings from `feat/staking` (including changes in #1785) to `develop` so they are updated on Crowdin
N/A
N/A

chore(shared): Sync source strings for staking

---

packages/shared/components/popups/StakingConfirmation.svelte
packages/shared/components/popups/StakingManager.svelte

Icons on the StakingManager and StakingConfirmation popups where not consistent sizes relative to other icons on those components. This fix I have manually adjusted the sizes so they all appear to be the same size as the other ones on that popup.

fix: consistent icon sizes

---

packages/shared/routes/dashboard/wallet/views/Account.svelte

All the components within the view `Account.svelte` were being re-mounted based on any current account change. This was causing things like the re-mounting the `Send.svelte` component if the account changed somehow, like finished syncing and pulled changes. 
This PR makes the components re-mount only if the selected account ID changes, which you can do by browsing on the top right account(wallet) navigator.  
N/A

Fix: Re-render account component only by selected account ID

---

packages/shared/components/Sidebar.svelte
packages/shared/lib/participation/stores.ts

Fix logic to use partiallyUnstakedAmount instead of unstakedAmount
Update colours:
- Red colour indicates that the staking feature is new to the user.
- Yellow indicates there is partially staked funds that need action

fix: staking notification badge logic and colour

---

packages/shared/lib/router.ts

When using electron menu to navigate to settings it will not close any popups, so this fix manually calls function to close the popups. 
Manually on MacOS 12.0

fix: close popup on settings navigation

---

packages/shared/components/popups/AirdropNetworkInfo.svelte

Adds a link to the assembly & shimmer network info popup.
Tested on:
- macOS Monterey 12.1

Feat: Learn more in airdrop network info

---

packages/shared/lib/wallet.ts

If `activeProfile` is null, it leads to a crash because we don't do a null check.
N/A
N/A

fix: check for activeProfile object before accessing migratedTransactions prop

---

packages/shared/components/WalletPill.svelte
packages/shared/components/index.js
packages/shared/locales/en.json
packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte
packages/shared/routes/dashboard/wallet/views/AccountNavigation.svelte

This PR aims to add a tooltip to the wallet pills that appear on the airdrop project tiles. In order to achieve so I decided creating a new reusable `WalletPill` component
N/A
- Wallet navigation should behave as usual, no changes.
Now when you hover the mini wallet in the staking tiles it should display the full name of the wallet.

Feat: Add tooltip to wallet staking

---

packages/shared/components/AccountTile.svelte
packages/shared/lib/participation/staking.ts

Fixes the logic for some edge cases around calculating the minimum reward time for either staking airdrops.
None
Platforms:
Cases:
- Stake an account with enough for minimum airdrop reward for either or both airdrops
- Stake an account with enough for minimum airdrop reward for either or both airdrops then send some funds (leaving a a non-zero balance)
- Stake an accounts funds on one address, reaching the minimum for either or both airdrops, then unstake / move funds to another address (on same account) and begin staking again 
- This means that the `rewards` and `rewardsBelowMinimum` fields in the `AccountParticipationOverview` type must __both__ be non-zero

fix: minimum staking reward calculation

---

packages/shared/components/popups/StakingConfirmation.svelte

It was using the auto selected checkbox to decide airdrop selection when merging partially staked funds, this fix changes that to use the active airdrops when the confirmation is for a merge instead of the checkboxes.
Manually on MacOS 12.0
- Merge for Assembly, send more funds to account, merge and watch the wallet icons for each event.
- Merge for Shimmer, send more funds to account, merge and watch the wallet icons for each event.
- Merge for Both, send more funds to account, merge and watch the wallet icons for each event
Add an `x` to the boxes that are relevant to your changes, and delete any items that are …

fix: merge staking selection logic

---

packages/shared/locales/en.json

In previous PRs I had assumed that the category "one" meant only the number 1, so I thought it was appropriate to hardcode it as `1`. It turns out this assumption doesn't hold in the case of languages such as Serbian and Croatian. In these languages, passing `31` (which uses the "one" category) causes the UI to display `1`, which is not correct.
Reported by Wind in Discord

fix(shared): Fix quantity for "one" plural category

---

packages/shared/components/popups/AddNode.svelte
packages/shared/routes/dashboard/settings/views/Advanced.svelte

When editing a node, the new settings are not saved if the URL is changed. This is because we look for which node to update using the new URL, but the state still has the old URL.
Fixes #1862 
Tested on macOS (dev)

fix(shared): Fix issue changing node URL

---

packages/shared/lib/tests/time.test.ts
packages/shared/lib/time.ts

- Fixes the logic for `getBestTimeDuration` (`time.ts`) to return the correct number 
- Fixes test in `time.test.ts`
None
Platforms:
Cases:
- Try various amounts of time (negative, zero, near-zero, and non-zero)

hotfix: best time duration function

---

packages/shared/locales/en.json
packages/shared/routes/setup/Profile.svelte

Localizes the "Advanced options" label so that it can be translated
N/A

fix(shared): Localize "Advanced options" label

---

packages/shared/lib/participation/participation.ts
packages/shared/lib/typings/address.ts
packages/shared/lib/wallet.ts

Block staking on a wallet only if the pending transactions can actually confirm (by comparing UTXO id in message against the UTXO on the address)
Tested invalid pending transactions by double spending (to create one that will never confirm).
Tested valid pending transactions with a normal spend.

fix: ensure syncing message only shows for valid pending transactions

---

packages/desktop/package.json

Creating this pull request in case we feel that this would be beneficial. Specifically when we create alpha or beta builds, windows will install it over the users main firefly application. Switching from the NSIS one click installer to the multi step will allow the user to select the location where they want to install.
Built branch using github actions and test install on windows machine.

chore: allow change of install directory windows

---

packages/shared/components/inputs/Dropdown.svelte

Adds dropdown closing when outside clicking, uses a function from actions lib
Resolves https://github.com/iotaledger/firefly/discussions/1784
Closes https://github.com/iotaledger/firefly/issues/2042
- New (a change that implements a new feature)
Open any dropdown and click outside, it should close the dropdown

feat: close dropdown on click outside

---

packages/shared/components/inputs/Dropdown.svelte

Makes the dropdown menu options searchable with key presses
Resolves https://github.com/iotaledger/firefly/discussions/1541.
Closes https://github.com/iotaledger/firefly/issues/2051
- New (a change that implements a new feature)
Pressing alphanumeric keys should include the text being typed in dropdown placeholder and apply the `includes` string method which should focus on the option that satisfies the condition, I've tested in settings dropdowns

feat: searchable dropdown options

---

packages/shared/components/popups/DeleteProfile.svelte
packages/shared/lib/app.ts
packages/shared/lib/profile.ts
packages/shared/routes/login/Login.svelte
packages/shared/routes/login/views/EnterPin.svelte

Keep track of the last logged-in profile using persistent storage of the active profile id
Resolves #1562
Closes https://github.com/iotaledger/firefly/issues/2050
- Update (a change that updates existing functionality)
- Select a profile
- Refresh the application
- Enter pin screen is the first loaded one and the select profile is the first step one
- Click on the previous button
- Refresh the application
- Select profile screen is the first loaded one

feat: keep track of the last logged in profile

---

packages/shared/components/inputs/Amount.svelte
packages/shared/lib/tests/network.test.ts
packages/shared/tsconfig.json

The input field is changed independent of the IOTA unit field. This creates a bad UX, since users might be unaware that the input has changed, while editing something unrelated to that.
Closes https://github.com/iotaledger/firefly/issues/2092
* Fix (a change which fixes an issue)
Manual testing

enhancement: remove conversion when unit changes on send form

---

packages/shared/components/popups/GovernanceVotingPowerInfo.svelte
packages/shared/components/popups/Index.svelte
packages/shared/locales/en.json
packages/shared/routes/dashboard/governance/Governance.svelte
packages/shared/routes/dashboard/governance/views/GovernanceEvents.svelte
packages/shared/routes/dashboard/governance/views/GovernanceInfo.svelte
packages/shared/routes/dashboard/governance/views/GovernanceVotingPower.svelte
packages/shared/routes/dashboard/governance/views/index.js

Adds the voting dashboard (voting power, info and community treasury event) with the latest updates in Figma
Closes #2139 
Clicked on the governance icon in the sidebar, compared the UI with the Figma one and clicked in "My voting power" to open the popup info (should be closed with the `X` button or `Done` button)

feat: (UI) Voting dashboard: power, info & single event

---

packages/shared/components/popups/Backup.svelte
packages/shared/components/popups/Password.svelte
packages/shared/routes/dashboard/settings/views/Security.svelte
packages/shared/routes/setup/backup/views/BackupToFile.svelte

Add preventDefault on form sumbits needed for mobile to work
[This issue `closes #2205`.](https://github.com/iotaledger/firefly/issues/2205)
Building for browser, Capacitor 3, Android Studio Arctic Fox 2020.3.1, Xcode 13.
Tested on real devices and iOS/Android emulators/simulators.
```bash
$ yarn
$ yarn build
$ yarn android:update
$ yarn ios:update
```

Fix: Mobile form submits

---

packages/shared/routes/dashboard/settings/views/SettingsHome.svelte

- In PR #2155 the settings icons got removed by mistake. This PR brings them back
- Additionally it removes unnecessary `localize` prop
N/A

Fix: restore settings icons

---

packages/backend/Cargo.lock
packages/backend/Cargo.toml
packages/backend/bindings/node/native/Cargo.lock

There was a bug in wallet.rs that was causing a crash if you tried to unlock stronghold after previously deleting a different account in the same session. They have kindly fixed and therefore this PR is to bump to the latest commit of wallet.rs
Fixes #1674 
On MacOS by deleting multiple profiles in a row and testing generic functionality.

fix: resolve crash after deleting profile

---

packages/shared/locales/en.json

This PR fixes some inconsistency in the title section headers (at least for the English locale).
__Before__
__After__
__Alternative__
_None_
Platforms:
- Ubuntu 21.10

fix: setting title consistency

---

packages/backend/bindings/node/index.ts
packages/shared/components/popups/DeleteProfile.svelte
packages/shared/lib/app.ts
packages/shared/lib/profile.ts
packages/shared/lib/shell/walletApi.ts
packages/shared/lib/typings/wallet.ts
packages/shared/lib/wallet.ts
packages/shared/routes/dashboard/settings/views/security/DeleteProfile.svelte

This change allows the user to delete a profile without balance, as it removes the unnecessary calls to delete each account within a profile before deleting the account.
Fixes #2035 
Tested thoroughly, unfortunately there is still a bug after deleting which we are waiting for a response from the wallet team on. More info here: https://github.com/iotaledger/firefly/issues/1674

fix: allow delete profile with balance

---

packages/desktop/electron/lib/aboutPreload.js
packages/desktop/electron/lib/errorPreload.js
packages/desktop/electron/main.js
packages/desktop/electron/preload.js
packages/desktop/index.js
packages/desktop/sentry.js

Each time the Sentry JS module was being imported, initialization code was being run. By using a functional-style export, we can pass a parameter when importing that specifies whether or not to initialize Sentry.
```
- Add import parameter for Sentry JS module, specifying whether or not to initialize Sentry
```
- #2266 
- __Desktop__
- __Mobile__
Test specific scenarios describe in #1603.

feat: Sentry reporting conditional initialization

---

.github/workflows/build-desktop.yml

The autoupdater checks for new updates by looking at the version listed in the `latest.yml`, `latest-mac.yml`, or `latest-linux.yml` files. Since these are served through CloudFront, it can take up to 30 minutes for changes to be reflected to users. This can cause confusion when a new version is announced in Discord, but a new version is not shown in Firefly.
N/A
Closes #2219 
Tested locally

chore(ci): Invalidate CloudFront cache for auto-update files upon release

---

packages/desktop/webpack.config.js

Webpack is currently generating chunks (at the moment named `27.27.js` and `987.987.js`) and outputting them into `desktop/public` when they should be in `desktop/public/build`.
N/A, not user-facing
N/A
- __Desktop__
- __Mobile__
App loads properly

chore(desktop): Output Webpack chunks to build folder

---

packages/mobile/package.json

Without this change, mobile is not able to run the development server since there is a conflict with different Webpack versions.
```
Changed webpack and webpack-cli versions pairing with desktop package.json file.
```
- __Desktop__
- __Mobile__
```bash
./packages/mobile $ yarn
./packages/mobile $ yarn dev
```

Fix Mobile build: Paired Webpack dependencies with desktop versions

---

.husky/pre-commit
package.json

Currently unstaged checks are also checked by the linter. This is quite annoying for developers, since they have to change files that are not yet ready and are also not intended to be committed.
```
- Use lint-staged to only check staged files for linting and formatting
- Use format and linting fixing instead of checking
```
Closes: 
- https://github.com/iotaledger/firefly/issues/2036
- __Desktop__
- __Mobile__

chore: precommit only checks staged

---

.github/workflows/build-desktop.yml
.github/workflows/ci.lint.yml
.github/workflows/ci.test.yml
packages/desktop/README.md

#2381 added `@capacitor/docgen` as a dependency, but it fails to install unless Node.js 14 or later is installed
N/A
N/A
N/A

chore: Use Node.js 14 on CI and update readme

---

packages/shared/components/ActivityDetail.svelte
packages/shared/components/modals/AccountActions.svelte
packages/shared/components/popups/DeleteAccount.svelte
packages/shared/components/popups/HideAccount.svelte
packages/shared/lib/wallet.ts
packages/shared/routes/dashboard/Dashboard.svelte
packages/shared/routes/dashboard/wallet/Wallet.svelte
packages/shared/routes/dashboard/wallet/views/AccountActions.svelte
packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
packages/shared/routes/dashboard/wallet/views/AccountNavigation.svelte
packages/shared/routes/dashboard/wallet/views/BarChart.svelte
packages/shared/routes/dashboard/wallet/views/LineChart.svelte
packages/shared/routes/dashboard/wallet/views/ManageAccount.svelte
packages/shared/routes/dashboard/wallet/views/Receive.svelte
packages/shared/routes/dashboard/wallet/views/Send.svelte
packages/shared/routes/dashboard/wallet/views/WalletActions.svelte
packages/shared/routes/dashboard/wallet/views/WalletHistory.svelte

This PR exposes `selectedAccount` as a global state, replacing the old private context. 
```
chore: move selectedAccount to global state
```
Closes #2359
- __Desktop__
- __Mobile__

chore: Move `selectedAccount` to global state

---

packages/shared/components/popups/GovernanceCastVote.svelte
packages/shared/components/popups/GovernanceVotingPowerInfo.svelte
packages/shared/components/popups/Success.svelte
packages/shared/lib/participation/constants.ts
packages/shared/lib/participation/participation.ts
packages/shared/routes/dashboard/Dashboard.svelte
packages/shared/routes/dashboard/governance/Governance.svelte
packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte
packages/shared/routes/dashboard/governance/views/GovernanceEvents.svelte
packages/shared/routes/dashboard/governance/views/GovernanceInfo.svelte
packages/shared/routes/dashboard/governance/views/GovernanceVotingPower.svelte

Blocked event disabling if event is inactive/ended. UI finalization has to be done in another PR.
```
chevron and popup disabled if event has ended/is inactive.
```
closes: https://github.com/iotaledger/firefly/issues/2348
- __Desktop__
- __Mobile__

fix: disabled popup if event is ended or inactive

---

packages/shared/components/popups/GovernanceCastVote.svelte
packages/shared/routes/dashboard/governance/Governance.svelte
packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte

This PR aims to fix the branch feat/voting after `feat/single-wallet` got merged.
Additionally, I used the time to add reactivity to the event detail page 
```
fix: replace selectedAccountId with selectedAccount
feat: add account reactivity to event details view
```
Closes #2347
- __Desktop__
- __Mobile__
Vote and switch accounts to see the reactivity working.

feat: add account reactivity to voting detail view

---

packages/shared/lib/wallet.ts
packages/shared/routes/dashboard/wallet/Wallet.svelte

This PR aims to fix [this line](https://github.com/iotaledger/firefly/blob/a3710d45da798548e368e3b769eda4c31a8109f1/packages/shared/routes/dashboard/wallet/Wallet.svelte#L148) which was broken in `feat/single-account`, it was being called on every `selectedAccount` change, instead of the selected index. 
```
fix: ledger regenerate address
feat: expose selectedAccountId globally
```
- __Desktop__
- __Mobile__
Please tick all of the …

fix: ledger regenerate address

---

packages/shared/lib/router.ts

The governance router is reset upon logout
```
fix: governance router resets upon logout()
```
closes: https://github.com/iotaledger/firefly/issues/2406
- __Desktop__
- __Mobile__
Go to governance dashboard and view proposal. Log out and log in. If you go to the governance dashboard, you should see the dashboard and not the proposal.

feat: reset governance upon logout

---

packages/shared/components/popups/GovernanceCastVote.svelte
packages/shared/lib/participation/constants.ts

Added a spinner to the disabled button.
```
- upon cast/merge/stop/change vote add spinner message that says 'Broadcasting'
- disable button if account is syncing
```
closes: https://github.com/iotaledger/firefly/issues/2411
- __Desktop__
- __Mobile__

feat: add loading spinner

---

packages/backend/bindings/capacitor/package.json

Reverts iotaledger/firefly#2424 because it includes a breaking change for mobile.

Revert "chore: update capacitor bindings script"

---

packages/backend/bindings/capacitor/package.json
packages/backend/bindings/capacitor/scripts/build.js

An [issue with Yarn](https://github.com/yarnpkg/yarn/issues/4564) is causing yarn workspaces to fail on Windows when there is a script that utilizes a dependency before the yarn workspace is instantiated. The capacitor bindings workspace needs a preinstall script that uses `rimraf` to support its functionality, which is causing Windows to fail.
This PR adds a node script to the capacitor workspace that is instead called in the preinstall script.
```
- Added script to packages/backend/bindings/capacitor/scripts that calls correct dependency path
- Changed package.json scripts to use this new script
```
Closes #2450
Please select any type below that is applicable to your changes, and delete those that …

fix: capacitor binding yarn issue affecting Windows 

---

packages/shared/lib/wallet.ts
packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte
packages/shared/routes/dashboard/staking/Staking.svelte
packages/shared/routes/dashboard/wallet/views/Send.svelte

Adds disconnected ledger popup and ledger tx confirmation popup to voting flow
closes: #2438 
- __Desktop__
- __Mobile__

feat: adds voting ledger UI components

---

packages/backend/bindings/node/index.ts
packages/shared/components/popups/GovernanceCastVote.svelte
packages/shared/lib/participation/api.ts
packages/shared/lib/participation/bridge.ts
packages/shared/lib/typings/walletApi.ts

Merging votes returned an `invalid type of action` error. Before wallet.rs had an exported function `participate_with_remaining_funds`, however this has been replaced by using the regular `participate` function. This PR fixes the issue
```
- removed `participateWithRemainingFunds` from the wallet API
- used `participate` when merging votes
```
closes: https://github.com/iotaledger/firefly/issues/2446
- __Desktop__
- __Mobile__
Please tick all of the following boxes that are relevant to …

fix: merge button not working

---

packages/shared/components/popups/Transaction.svelte

Fix transaction crash by adding optional chaining operator to accountOverview
closes #2444
- __Desktop__
- __Mobile__

fix: transaction crash

---

packages/desktop/tsconfig.json

There was no wildcard symbol in the TS config paths for desktop, causing a failure in building Svelte components where used.
```
- Add wildcard pattern to desktop TS config file
```
_None_
- __Desktop__
- __Mobile__
Used the fix in a refactoring task with `@common/*`.

fix: lib module path aliases

---

package.json
yarn.lock

[`node-abi`](https://github.com/electron/node-abi) is used to map Electron versions to their respective Node.js ABI version. When Electron was updated to 12.2.3, the corresponding ABI version could not be found in the version of `node-abi` we currently use. As a result, native dependencies such as `keytar` would not build properly, causing Webpack to fail to bundle the code and `electron-builder` to show warnings.
When running `yarn build`:
```
Module not found: Error: Can't resolve '../build/Release/keytar.node' in 'firefly/node_modules/keytar/lib'
```
When running `yarn compile:<os>`:
```
Error: Could not detect abi for version 12.2.3 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
```
**Note: you may need to remove the root …

chore: Update `node-abi` to 3.8.0

---

packages/mobile/ios/.gitignore
packages/mobile/ios/App/Podfile
packages/mobile/ios/App/Podfile.lock

Adds missing dependencies to Podfile (running `yarn ios:update` re-adds these). Also adds the Podfile.lock to git so that we  can lock the iOS dependencies for security and stability.
```
- chore: Add missing dependencies to Podfile
- chore: Check in Podfile.lock
```
N/A
- __Desktop__
- __Mobile__
N/A

chore: Add missing deps to Podfile and check in Podfile.lock

---

packages/shared/components/modals/ProfileActions.svelte
packages/shared/locales/en.json

moves stronghold status and action to profile modal for the single account view
closes #2152 
- __Desktop__
- __Mobile__

feat: move stronghold status and action to profile modal

---

packages/mobile/ios/App/App/Info.plist

Adds information related to our use of encryption for US export compliance so that we don't need to provide it to Apple every time we upload a build
```
- Set ITSAppUsesNonExemptEncryption to false for iOS export compliance in Info.plist
```
N/A
N/A
N/A

chore: Add export compliance info to Info.plist

---

packages/backend/bindings/capacitor/FireflyActorSystemCapacitorBindings.podspec
packages/mobile/ios/App/App/Info.plist

To build for production and get *.ipa files we needed to disable bitcode for the bindings plugin, it's related to cargo-lipo.
We do this adding a flag on Pod file.
Also fixed git url.
Closes https://github.com/iotaledger/firefly/issues/2494
- __Desktop__
- __Mobile__
Open Xcode, and open the Product menu and choose Archive.

Fix Mobile Plugin Capacitor Bindings iOS build production

---

packages/mobile/capacitor/lib/barcodeManager.ts

`BarcodeScanner.startScan` is being called when `barcodeManager` is imported, so it is essentially being called at launch and always running.
```
- Avoid calling `BarcodeScanner.startScan` outside of a function
```
N/A
- __Desktop__
- __Mobile__
Tested on iOS simulator, verified that `startScan` wasn't being called by watching logs from Capacitor

fix: Prevent barcode scanner from turning on at launch

---

packages/shared/components/popups/Index.svelte

The developer profile banner was displaying above the loader popup because of a CSS zindez issue. Increasing the popup zindex should fix the issue
```
feat: increase popup zindex to z-20
```
Closes #2677
- __Desktop__
- __Mobile__

feat: increase popup zindex

---

packages/shared/components/popups/Transaction.svelte

Currently, despite the staking events having ended, users are still shown a warning if they haven't reached minimum rewards.
```
- Changes conditional to ensure that min rewards warning only shows if staking is possible
```
#2679
- __Desktop__
- __Mobile__
Tested trying to send mainnet transaction without account that had below min rewards.

fix: minimum rewards popup warning

---

packages/shared/components/StakingAssetTile.svelte

This PR aims to display the warning icon on the asset tile only when the tooltip information is ready
```
fix: delayed asset warning tooltip
```
- __Desktop__
- __Mobile__

fix: delayed asset warning tooltip

---

packages/backend/Cargo.lock
packages/backend/Cargo.toml
packages/backend/bindings/node/native/Cargo.lock
packages/shared/lib/participation/constants.ts

Currently the `develop` branch has the staking event IDs for the devnet environment.
```
- Change constants in "participation" module
- Change wallet-rs revision in backend
```
_None_
- __Desktop__
- __Mobile__
Tested general wallet functionality (e.g. sending a transaction, querying node)

chore: revert staking event IDs

---

.snyk
packages/desktop/electron/main.js

Mitigates [CVE-2022-21718](https://nvd.nist.gov/vuln/detail/CVE-2022-21718), which allows a compromised renderer to access a Bluetooth device without permission. This uses the workaround from [GHSA-3p22-ghq8-v749](https://github.com/advisories/GHSA-3p22-ghq8-v749) and can be removed after updating to Electron 13.6.6 or later.
```
- Cancel any requests to select a Bluetooth device
- Ignore this alert in Snyk
```
- [GHSA-3p22-ghq8-v749](https://github.com/advisories/GHSA-3p22-ghq8-v749)
- [SNYK-JS-ELECTRON-2431353](https://security.snyk.io/vuln/SNYK-JS-ELECTRON-2431353)
- __Desktop__
Add the following code to a function that responds to a user gesture (e.g. a button click) to simulate a compromised renderer requesting access …

fix: cancel any requests to select a Bluetooth device

---

packages/backend/Cargo.lock
packages/backend/Cargo.toml
packages/backend/bindings/node/native/Cargo.lock

Cherry-picks 7bb662a to the `release/1.4.0` branch
```
- Update wallet.rs to fix missing addresses
```
Fixes #2647 
- __Desktop__
N/A

chore: update wallet.rs to fix missing addresses

---

package.json
yarn.lock

Updates `selfsigned` to 2.0.1 and `node-forge` to 1.3.1, fixing multiple vulnerability alerts about `node-forge`. This comes from a `devDependency` (`webpack-dev-server`), so Firefly is not vulnerable in production. 
```
- Updated selfsigned to 2.0.1
- Updated node-forge to 1.3.1
```
- Dependabot alerts related to `node-forge`
- Snyk alerts related to `node-forge`
- __Desktop__
- __Mobile__
N/A

chore: update selfsigned to 2.0.1

---

packages/mobile/App.svelte
packages/shared/lib/core/router/enums/routes.ts
packages/shared/routes/dashboard/TopNavigation.svelte
packages/shared/routes/dashboard/settings/views/SettingsViewer.svelte

Add a global back button to the single account view
To create a full global back button, we would need a global route history. This should be easily achieved by implementing a GlobalRoutes store with a history.
```
Used the new routers to create a back button on settings
Removed back button from settings view
Removed unused route
```
closes: https://github.com/iotaledger/firefly/issues/2428
- __Desktop__
- __Mobile__
Please tick all of the following boxes that are relevant to your …

feat: add global back button

---

packages/shared/components/AccountSwitcher.svelte
packages/shared/locales/en.json

Switching account while voting/staking/transferring/syncing leads to UI inconsistencies.
This is tackled in this PR. The account switcher modal doesn't open and a popup tells 
the user that they need to wait until the corresponding action is finished.
```
Account Switching modal only when no UI inconsistencies could be present
If modal doesn't open, notifications are shown
```
closes: https://github.com/iotaledger/firefly/issues/2688
- __Desktop__
- __Mobile__
Please tick all of the …

fix: disallow account switching

---

packages/desktop/package.json

Currently when running `yarn build` it defaults to the production instance, but as the alpha build is the closest to development we should ideally use that environment, i.e. `build:alpha`.
```
- Change general build script (in desktop) to use alpha environment instead of production
```
None
- __Desktop__
- __Mobile__
Ran `yarn build && yarn start` in desktop directory, resulting in an alpha developer instance.

chore: use alpha in development

---

.github/workflows/build-desktop.yml

Upload debug files for backend bindings on Windows when building a release on CI
```
Upload debug files for backend bindings on Windows when building a release
```
Closes #2650 
- __Desktop__
- __Mobile__
Tested on CI

chore: upload PDB files when building Windows

---

.github/workflows/build-desktop.yml

Increases network timeout threshold for Yarn on CI to reduce the failure rate of Windows builds
```
- Increase Yarn network timeout threshold
```
N/A
- __Desktop__
- __Mobile__

chore: increase network timeout for Yarn on CI

---

packages/desktop/App.svelte
packages/shared/components/popups/DeleteProfile.svelte
packages/shared/lib/app.ts
packages/shared/lib/appSettings.ts
packages/shared/lib/profile.ts
packages/shared/lib/wallet.ts
packages/shared/routes/dashboard/settings/views/general/ChangeProfileName.svelte
packages/shared/routes/login/views/EnterPin.svelte
packages/shared/routes/setup/Congratulations.svelte
packages/shared/routes/setup/Profile.svelte

To fix a number of issues with renaming account (namely on windows the folder could not be renamed because of a lock, and on both platforms we could not lock stronghold if the folder had moved), we have decided to change the folder names to the profile id, rather than the profile name.
```
- Added functions to rename all profile folder names from profile name to profile id
- Conditionally call this on app load if it has not been called before
- Change logic everywhere that finds profile folder based on name to now use id
- Remove the rename folder function from the ChangeProfileName component
```
- Fixes #2643
- Fixes #2644
- Fixes #2645
Please select any platforms where your changes have been …

fix: rename account issues for 1.4.0

---

packages/shared/routes/dashboard/wallet/views/AccountAssets.svelte
packages/shared/routes/dashboard/wallet/views/AccountBalance.svelte
packages/shared/routes/dashboard/wallet/views/Receive.svelte

Upon receiving the generate address button is centered in the middle of the screen. This is moved to the top
```
move generate address to the top
```
closes: https://github.com/iotaledger/firefly/issues/2690
- __Desktop__
- __Mobile__

fix: place receive at the top instead of middle

---

packages/desktop/electron/main.js

When JS errors are caught and handled by the `handleError` function, we create a new `Error` with a message containing the original error information (including the stacktrace) as JSON. As a result, the real stacktrace is truncated by Sentry because an error message is usually shorter:
(2nd and 3rd lines are the real stacktrace, while the rest of the lines are the stacktrace seen by Sentry)
Since Sentry doesn't treat it like a real stacktrace, it won't be unminified, which makes it much easier to determine the location of the error in our codebase. It also uses `handleError` as the function causing the error, causing Sentry to group all errors passed to `handleError` together since the stacktrace has precedence in error grouping.
```
- Retain original error structure and stacktrace when …
```

fix: retain original error structure when sending error to Sentry

---

packages/shared/routes/dashboard/staking/views/StakingInfo.svelte

Cancelling a participation transaction in ledger created a UI error on the staking animation. This reveals the underlying problem that `participations` are updated as soon as the staking manager is opened after a transaction is sent to the ledger for signing. The current fix is to rely on the staked funds and not on participations (which is not guaranteed to be correct in case of ledger). The proper fix is that `participations` are only handled after the transaction is signed and broadcasted. This requires an event to be emitted from ledger upon sending the transaction or a change in wallet.rs.
```
- animation is based upon stakedFunds instead of participations
- refactored StakingInfo.svelte
```
closes: https://github.com/iotaledger/firefly/issues/2689
Please select any type below that …

fix: reactivity issue when cancelling particpation

---

packages/desktop/electron/main.js

To make the traffic light controls look a bit nicer on Mac, specifically within the new top navigation I have changed the titleBartype for electron windows from `hidden` to `hiddenInset`
```
- add inset to window controls on mac
```
- __Desktop__
- __Mobile__
Please tick all of the following boxes that are relevant to your changes, and delete those that …

fix: inset window controls on mac

---

packages/shared/components/TextHint.svelte
packages/shared/components/popups/NewStakingPeriodNotification.svelte
packages/shared/components/popups/StakingManager.svelte
packages/shared/locales/en.json

Have to change staking manager UI per new designs.
```
- Add extra CSS to TextHint component
- Used TextHint in StakingManager and NewStakingPeriodNotification popups
- Added hint locale for English
```
- Closes #2757 
- __Desktop__
- __Mobile__
Manually opened both `StakingManager` and `NewStakingPeriodNotification` popups from the staking dashboard.

feat: adjust staking manager UI for single account

---

packages/shared/components/popups/StakingConfirmation.svelte
packages/shared/locales/en.json

This is to make the staking confirmation popup dynamic to the number of airdrops.
```
This will only show body text if there is more than one airdrop active or if the user is merging funds.
This also only shows the airdrop checkbox if that airdrop exists.
And it only auto selects the airdrop if it exists and the user will reach minimum rewards.
```
- __Desktop__
- __Mobile__
Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your …

enhancement: make staking confirmation dynamic to number of airdrops

---

packages/shared/routes/dashboard/Dashboard.svelte

When creating a new account, it should navigate to the newly created one
closes #2745 
- __Desktop__
- __Mobile__

fix: set selected account to newly created one

---

packages/shared/components/modals/AccountActions.svelte

When hiding an account, we should navigate to one of the non-hidden accounts
closes #2744 
- __Desktop__
- __Mobile__

fix: select unhidden account when hiding one

---

packages/backend/Cargo.lock
packages/backend/Cargo.toml
packages/backend/bindings/node/native/Cargo.lock

Updates wallet.rs to https://github.com/iotaledger/wallet.rs/commit/cd13b94cb61087e5957d4229a8a5e816fa2a94f0 in order to update `rust-rocksdb` so that issues with Unicode paths are fixed (see https://github.com/rust-rocksdb/rust-rocksdb/pull/623)
```
- Updated wallet.rs to fix Unicode paths on Windows
```
Fixes #2771 
- __Desktop__
1. Create a new user with a username that contains Unicode characters (e.g. `rájïv`)
2. Create a new profile in Firefly

chore: update wallet.rs to fix Unicode paths on Windows

---

packages/shared/components/popups/BalanceFinder.svelte

This change simply makes a call to cache all the previous staking rewards if the balance finder has been run at least once.
This is so we can check if additional addresses or accounts found have staking rewards. And also a fail safe incase the original caching didn't work.
```
- Add call to cacheallrewards for shimmer and assembly when the balance finder popup is destroyed (only if the finder has been run)
```
- __Desktop__
- __Mobile__ …

enhancement: re cache all staking rewards on balance finder

---

packages/shared/components/modals/Modal.svelte
packages/shared/components/modals/ProfileActions.svelte

- add `disableOnClickOutside` prop to `Modal.svelte`
- disable click outside on profile modal while unlocking stronghold
- fix `i18n` type import
```
feat: prevent profile modal from closing while unlocking stronghold
```
Closes #2781
- __Desktop__
- __Mobile__

feat: prevent profile modal from closing while unlocking stronghold

---

packages/shared/components/Profile.svelte

If a user clicks on the `Profile` component on the `EnterPin` screen, the app will report an error. In dev, this is reported as a warning when it renders:
```
- Check if an onClick handler is defined before calling it
```
Fixes #2788 
Click on the profile icon on the `EnterPin` screen

fix: check if an onClick handler is defined before calling it

---

packages/shared/routes/dashboard/Dashboard.svelte

This single account guide popup was showing each time the profile changed if the user did not explicitly clicked on the button to acknowledge the changes. This PR aims to fix the reactivity around this problem
```
fix: single account guide display reactivity
```
- __Desktop__
- __Mobile__
- Login to your profile and do not accept the single account guide popup, just close it but clicking anywhere
- do anything that would update the profile: create/add account, modify something in the settings...
- the popup should not be shown again until the next time you login 
- if you accept the …

fix: single account guide popup display reactivity

---

packages/shared/components/modals/AccountSwitcher.svelte
packages/shared/lib/core/router/helper.ts

This PR aims to fix the following feedback provided after testing 1.5.0 alpha
> Popup elements from Wallet tab (send,receive, customise) stay opened when switching between wallets while Tx history resets its tab. Not sure if intended 
```
feat: reset account router on account switch
```
Closes #2797
- __Desktop__
- __Mobile__

feat: reset account router on account switch

---

packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte

This PR applies a min-height to the staking airdrop tile when assembly staking is possible to align both tiles
```
feat: polish airdrop tile rewards alignment when ASMB staking is possible
```
Closes #2804
- __Desktop__
- __Mobile__

feat: polish airdrop tile rewards alignment when ASMB staking is possible

---

packages/shared/routes/dashboard/staking/views/StakingInfo.svelte

There is a bug displaying `{duration}` in the rendered locale because of a bad conditional check.
```
- Improve conditional checking whether user is currently staking or not
```
Fixes #2815 
- __Desktop__
- __Mobile__

fix: missing duration arguments during staking

---

packages/shared/components/AccountSwitcher.svelte
packages/shared/components/modals/AccountSwitcher.svelte

Moves the prevent switching logic to inside the account switcher so you can at least open it for the guide
closes #2810
- __Desktop__
- __Mobile__

fix: moves prevent account switch logic to account buttons

---

packages/shared/components/modals/Modal.svelte

Switching between wallets something closes the dropdown automatically, and other times it will just stay open, and you need to click the same wallet twice to close the dropdown.
We added before a timeout for modal closing and opening which prevents the race condition between click outside and toggle button (that is outside of modal).
But seems that the amount of time was too high and causes problems when interactions are fast enough, so the timeout milliseconds have changed from 500 to 200 in this PR.
closes #2809
- __Desktop__
- __Mobile__
Please tick all of the following boxes that are relevant to your changes, and delete those that …

fix: changes modal interaction timeout

---

packages/shared/routes/setup/protect/views/RepeatPin.svelte

Autofocus is missing on confirm pincode page so I've added the reset and focus function to it on mount
closes #2806
- __Desktop__
- __Mobile__

fix: adds reset and focus function to repeat pin on mount

---

packages/desktop/electron/main.js

Because the controls where on mac where previously too close to the top, specifically within the new top navigation. We changed the title bar style, from `hidden` to `hiddenInset`. This change changes that back for all OS accept mac. 
```
Made title bar style for electron widows conditional on os
```
- __Desktop__
- __Mobile__
Please tick all of the …

fix: only inset window controls on mac

---

packages/shared/locales/en.json

Reworded the title of the backup notification slightly to make it clear that they are backing up all of their wallets.
```
- Updated wording of backup notification title
```
- __Desktop__
- __Mobile__

fix: wording of backup notification title

---

packages/shared/components/ActivityRow.svelte
packages/shared/components/StakingAssetTile.svelte

The `StakingAssetTile` needed more emphasis when in the warning state.
```
- Stop "airdrop" CSS from overwriting the warning state CSS
- Move warning icon to left of token holdings
- Add hover states for asset tile and transaction item tile
- Add "---" as placeholder for fiat info
- Change presentation logic conditionals because empty arrays are truthy
```
Fixes #2836 
- __Desktop__
- __Mobile__
Hard-coded necessary values as true to test CSS.

enhancement: add warning emphasis for asset tile 

---

packages/shared/lib/wallet.ts

Account names are not consistent when restoring from a profile.
```
- Add logic to set account aliases upon syncing new accounts
- Change type from unknown to WalletAccount
```
Fixes #2841
- __Desktop__
- __Mobile__
Restore a profile with funds on a wallet whose index is at least 1 or more (using 0-based indices). Upon restoration the names will be "Wallet 1, 2, ..., N" and should be the same after logging out and back in.

fix: make account naming consistent

---

packages/shared/components/modals/AccountSwitcher.svelte
packages/shared/components/popups/HideAccount.svelte
packages/shared/lib/app.ts
packages/shared/lib/common/deep-links/types/wallet-context.type.ts
packages/shared/lib/common/deep-links/wallet-context-handler.ts
packages/shared/lib/core/router/helper.ts
packages/shared/lib/typings/sendParams.ts
packages/shared/routes/dashboard/wallet/views/Send.svelte

As we have deeplinks, and the user could also be initiating a send and then realise they are on the wrong address. We should persist the send and recieve form as well as any inputs when the user switches tabs.
```
- change sendParams.amount to string
- update areas of code to cast or convert amount
- add toWalletAccount to sendParams for internal transactions
- update sendParams when inputs changes
- fix updateFromSendParams on send form so the form accurately gets filled in from sendParams
```
- …

enhancement: persist send and recieve form when switching wallet

---

.github/workflows/crowdin.yml

Re-enables the Crowdin workflow on the `develop` branch. It was previously disabled so that strings needed for 1.4.x versions would not be removed from Crowdin.
```
- Re-enabled Crowdin workflow on `develop`
```
Closes #2828 
N/A

chore: Re-enable Crowdin translations on `develop` branch

---

packages/shared/routes/dashboard/staking/views/StakingInfo.svelte

In some cases while the wallets were still syncing, the duration argument for a specific locale was missing.
```
- Change logic for constructing duration argument for locale
```
Fixes #2815
- __Desktop__
- __Mobile__
Open staking tab while wallets are still syncing and wait to verify that a proper time duration is shown.

fix: adjust logic for constructing duration args

---

packages/shared/lib/shell/walletErrors.ts
packages/shared/lib/typings/events.ts

Error Type was not aligned with the error type returned from backend. Now changing this gives us the correct error message.
```
Updated error type and link to error message locale.
```
- __Desktop__
- __Mobile__
Try and send an amount that is less that leaves less than 1Mi in a wallet.
Please tick all of the following boxes that are relevant to your …

fix: leaving dust error message

---

packages/shared/locales/en.json

Some string used in the profile modal and sidebar modals had a capital for each word. This PR simply puts any non nouns and first character in the string to lowercase.
```
- update profile modal ledger strings
- update network modal strings
```
- __Desktop__
- __Mobile__
Please tick all of the following boxes that are relevant to your changes, and …

fix: decapatilise some translation strings

---

packages/shared/components/popups/NewStakingPeriodNotification.svelte
packages/shared/lib/participation/constants.ts
packages/shared/locales/en.json

Previously, we weren't using a dynamic date for the staking event information. 
```
- Change hard-coded data to locale arguments
- Add ASSEMBLY_EVENT_START_DATE constant, used in the changed locale
```
Fixes #2860
- __Desktop__
- __Mobile__
Hard coded `openPopup({ type: 'newStakingPeriodNotification' })` in the `Staking.svelte` dashboard route file.

fix: use dynamic date for staking event

---

packages/shared/components/StakingAssetTile.svelte
packages/shared/lib/assets.ts

Formatted the stakingRewardTiles so that the warning symbol sticks close to the asset name, and the asset balance is formatted to 2 decimal places.
```
- move warning component to inside the grid column next to the text
- format balance to two decimal places
```
- __Desktop__
- __Mobile__
Please tick all of the following boxes that are relevant to your …

fix: improve formatting on staking asset tile

---

packages/backend/Cargo.lock
packages/backend/Cargo.toml
packages/backend/bindings/node/index.ts
packages/backend/bindings/node/native/Cargo.lock
packages/shared/components/popups/StakingManager.svelte
packages/shared/lib/participation/api.ts
packages/shared/lib/participation/bridge.ts
packages/shared/lib/participation/participation.ts
packages/shared/lib/typings/walletApi.ts
packages/shared/lib/walletApiListeners.ts
packages/shared/routes/dashboard/staking/Staking.svelte

So that we don't need to store and update the event Id in wallet.rs, this change simply passes the assembly event id to wallet.rs when calling the getParticipationOverview function.
```
- Update wallet.rs revision
- Update getParticipation bindings
- Update getParticipation call to pass in assembly event Id.
```
wallet.rs changelog
https://github.com/iotaledger/wallet.rs/compare/ec6b3cb5bdf007ab59546505e56425eeec12f215...c1fae913dc58e6804ea756ce4c25d5b030513731
Please select any platforms where …

refactor: pass assembly event id to participationOverview call

---

packages/shared/routes/dashboard/TopNavigation.svelte
packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte

```
feat: add top bar back button to voting detail route
```
Close #2700
- __Desktop__
- __Mobile__

feat: add top bar back button to voting detail route

---

packages/shared/routes/dashboard/staking/views/StakingInfo.svelte

If the user has rewards from a previous period, they are not taken into account when determining exactly which zen guy staking animation should be displayed.
```
- Fix staking animation display logic to use total rather than current rewards
```
_None_
- __Desktop__
- __Mobile__
Test with rewards from a previous or current staking period.

fix: use total rewards for staking animations

---

.github/workflows/crowdin.yml

Fix Crowdin sync by bumping Crowdin action to 1.4.8.
```
- Bump Crowdin action to 1.4.8
```
https://github.com/actions/checkout/issues/760
https://github.com/crowdin/github-action/issues/114
Tested on GitHub Actions

chore: bump Crowdin action to 1.4.8

---

packages/shared/lib/participation/constants.ts
packages/shared/locales/en.json
packages/shared/routes/dashboard/staking/views/StakingInfo.svelte

We need to be using a dynamic date for the locales.
```
- Change to dynamic date for locales used in the StakingInfo component
- Update constant for Assembly staking starting date
```
Closes #2906 
- __Desktop__
- __Mobile__
Manually set event state to confirm date was displayed correctly.

enhancement: add dynamic dates in staking info

---

packages/shared/components/popups/StakingManager.svelte

There is an inaccuracy in how the merge funds flow shows the UI.
```
- Change conditionals for what HTML / CSS to use
```
_None_
- __Desktop__
- __Mobile__
Test merge stake flow.

fix: change reactivity in merge stake flow

---

packages/desktop/App.svelte
packages/desktop/electron/electronApi.js
packages/shared/lib/appSettings.ts
packages/shared/lib/profile.ts

This is needed because in 1.4.+ we rename the profile folders to use the profile index, this means that we can freely name and rename profiles. However, this store is not cleared when downgrading versions so this can only occur once.
in 1.4.0-1.4.2 there are bugs that meant people where downgrading to 1.3.3, because the folders had been renamed they where cleared and in 1.3.3 the user had to make there profiles again. If they then upgrade to 1.5.0, the profiles will wipe again as they are using 1.3.3- naming convention. This change simply attempts to rename profiles everytime the app loads in 1.5.0 so that people are able to upgrade.
We can fix this better or change it back once the majority of users …

fix: attempt rename profile folder everytime app is run

---

packages/shared/components/popups/StakingConfirmation.svelte

Because the wallet backend only stores participations in the local db, when restoring they do not exist in the wallet. And this leads to problems merging stakes. To prevent this, and because there is only one event in the next round of staking, we have hardcoded the staking confirmation screen to use the Assembly staking id when merging stakes.
```
Use STAKING_EVENT_IDS instead of active participations for partial stake (merge).
```
- __Desktop__
- __Mobile__
Please describe the specific …

fix: enable merging of assembly stake after restoring

---

packages/shared/components/ActivityRow.svelte

fix: reactivity issue on tx history icon & color
```
fix: reactivity issue on tx history icon & color
```
N/A
- __Desktop__
- __Mobile__

fix: reactivity issue on tx history icon & color

---

packages/shared/routes/dashboard/staking/views/StakingInfo.svelte

If there is no participation data detected for the selected account nor a participation plugin available on the node then there should be no animation.
```
- Remove staking animation when no participation detected
```
Closes #2931
- __Desktop__
- __Mobile__

enhancement: remove staking animation when participation not detected

---

packages/shared/components/popups/StakingManager.svelte

Below min stake tooltip was positioned wrong due to incorrect variable usage.
```
Fixes below min staking tooltip positioning
```
- __Desktop__
- __Mobile__
If a wallet does not have enough tokens to reach the minimum airdrop when you try to stay a warning icon/tooltip will appear when trying to stake.

fix: min stake warning tooltip positioning

---

packages/shared/components/AccountSwitcher.svelte

When switching networks, the profile data is restored causing the currently selected account name to become undefined. For a quick fix, this PR simply adds a placeholder as backup.
```
- Add "---" as placeholder backup in case of undefined name 
```
Fixes #3031 
- __Desktop__
- __Mobile__
Test switching networks and make sure "undefined" / "null" is NOT displayed.

fix: handle undefined name in account switcher

---

.eslintrc.js
package.json
packages/shared/components/Text.svelte
packages/shared/package.json
yarn.lock

As we have upgrade svelte version to make use of new features, such as <svelte:element>. We need to update the linting dependencies as they are complaining about some of the new features. 
```
- chore: increment eslint-plugin-svelte3 to 3.4.1
- chore: prettier-plugin-svelte to 2.7.0
```
- __Desktop__
- __Mobile__
Committed a change in Text.svelte
Please tick all of the following boxes that are relevant to your changes, and delete those …

chore: bump linting dependencies as we have upgraded svelte version

---

packages/shared/routes/dashboard/Dashboard.svelte
packages/shared/routes/dashboard/wallet/Wallet.svelte

Accounts loaded was not being set in the right place and account id was not being set before initialization of the syncing queue.
```
Changes ordering of activities on loading accounts, fixes consequential issues
```
- __Desktop__
- __Mobile__
Check everything loads fine.

fix: account load processing

---

packages/backend/Cargo.lock
packages/backend/Cargo.toml
packages/backend/bindings/node/native/Cargo.lock

After sending a transaction, we currently wait until the next poll cycle before we pick up confirmation (~30 seconds). We can instead poll for the confirmation of that isolated transaction. This visibly improves the experience for users across sending, staking and voting (<=10s).
```
- Update wallet-rs version
- Poll for transaction confirmation 
```
- __Desktop__
- __Mobile__
Try send, stake or vote and observe confirmation speed

enhancement: improve transaction confirmation detection speed

---

packages/shared/components/Sidebar.svelte
packages/shared/routes/dashboard/TopNavigation.svelte

Previously, the back button text was not reactive to the locale changing.
```
- Make back button text reactive to the locale
```
- Closes #3166
- Fixes #3179 
- __Desktop__
- __Mobile__
Switch between different locales and ensure that back button text updates accordingly.

fix: locale reactivity in back button

---

.github/workflows/build-desktop.yml

It turns out that even though we include the debug info in the Linux backend bindings that we ship with Firefly, Sentry does not symbolicate errors from them (in the `firefly-desktop` package) without receiving the debug info through a CLI upload. Therefore, we can upload the debug info to Sentry during the CI build and then strip it from the bindings that will be included in a build in Firefly. This reduces the size of the bindings from approximately 701 MB to approximately 37 MB.
```
- Strip debug info from Linux Node.js bindings during CI build
- Upload debug info to Sentry
```
Fixes #2568 
- __Desktop__
- __Mobile__
Triggered crashes to check if Sentry recognized the corresponding debug file. Also tested upload with GHA

chore: strip Linux backend debug info and upload to Sentry

---

packages/shared/routes/setup/import/views/BackupPassword.svelte

The back button on the password screen (after choosing a Stronghold to import) did not work because we were checking `isGettingMigrationData`, which is a store, instead of its value (with `$isGettingMigrationData`).
```
- Fix back button on Stronghold password screen
```
N/A
- __Desktop__
- __Mobile__
Try importing a Stronghold, then click the back button when asked for the password to decrypt the Stronghold

fix: fix back button on Stronghold password screen

---

packages/shared/lib/profile.ts

Disables "Firefly has changed" popup if the user is creating a new profile, or recovering an existing one.
```
- Updates profile builder to set hasFinishedSingleAccountGuide to true
```
- __Desktop__
- __Mobile__

fix: disable firefly changed popup on setup

---

packages/desktop/electron/electronApi.js

This PR fixes an error introduced in the previous mobile merge, where the Electron API was lacking a function (saveStrongholdBackup) to avoid an error when saving Stronghold file.
```
```
- __Desktop__
- __Mobile__

fix: add lacking function to Electron API

---

packages/shared/components/Button.svelte

This PR aims to fix the broken styled in the node configuration options by adding the missing `unstyled` prop
```
fix: add missing unstyled prop to button component
```
- __Desktop__
- __Mobile__

fix: add missing `unstyled` prop to button component

---

packages/shared/components/popups/GovernanceManager.svelte
packages/shared/lib/participation/api.ts
packages/shared/lib/participation/stores.ts
packages/shared/lib/participation/types.ts
packages/shared/lib/walletApiListeners.ts
packages/shared/locales/en.json
packages/shared/routes/dashboard/governance/views/GovernanceEventInfo.svelte
packages/shared/routes/dashboard/staking/views/StakingSummary.svelte

This PR aims to add voting loaders to the governance event detail view
```
Feat: add participation loaders
```
Close #3169 
- __Desktop__
- __Mobile__

Feat: add participation loaders

---

packages/shared/components/popups/Transaction.svelte

This PR aims to calculate `isAccountVoting` only based on the treasury vote participations
```
Fix: `isAccountVoting` included staking participations
```
- __Desktop__
- __Mobile__

Fix: `isAccountVoting` included staking participations

---

packages/shared/components/popups/GovernanceManager.svelte

Fixes a crash because `nextVote` is not persisted
```
- Fixes crash on vote tab switch
```
- __Desktop__
- __Mobile__

fix: voting tab switch crash

---

packages/shared/routes/dashboard/governance/views/GovernanceEventInfo.svelte

This PR aims to fix this:
```
fix: voting CSS winner&selected not visible in light mode
```
- __Desktop__
- __Mobile__

fix: voting CSS winner&selected not visible in light mode

---

packages/shared/routes/dashboard/TopNavigation.svelte

This PR aims to fix the following situation (visible in Korean)
```
feat: prevent back button text from breaking words into multiple lines
```
- __Desktop__
- __Mobile__

feat: prevent back button text from breaking words into multiple lines

---

packages/desktop/README.md
patches/dmg-builder+22.9.1.patch

In macOS 12.3, the pre-installed Python 2.7 [was removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). We still need this as the DMG script from our version of `electron-builder` uses Python 2. This PR applies a change similar to https://github.com/electron-userland/electron-builder/pull/6789 so that the path revealed by `which python` is used to execute the DMG script, instead of assuming that Python is located at `/usr/bin/python` (for example, on my computer it's now at `/Library/Frameworks/Python.framework/Versions/2.7/bin/python`). Note that for macOS 12.3+, if you want to build a DMG for macOS, you need to download [Python 2.7.18 from the Python website](https://www.python.org/downloads/release/python-2718/) (it's not available through …

chore: fix building DMG on macOS 12.3+

---

packages/shared/components/popups/GovernanceManager.svelte
packages/shared/components/popups/StakingManager.svelte
packages/shared/locales/en.json

Merging a stake automatically merges a vote and vice versa. We need to warn users this will happen.
```
- Add merge warnings if a user is voting and staking at the same time
```
- __Desktop__
- __Mobile__

enhancement: merge warnings

---

packages/mobile/ios/App/Podfile
packages/mobile/ios/App/Podfile.lock

- Lock `IotaWalletInternal` to 0.2.0
- Sync Podfile with iOS Capacitor plugins (`CapacitorSecureFilesystemAccess` was missing)
```
- Lock `IotaWalletInternal` to 0.2.0
- Add missing`CapacitorSecureFilesystemAccess` pod
```
N/A
- __Desktop__
- __Mobile__
Ran `pod install` and built iOS project successfully

chore: fix Pods installation

---

packages/mobile/.gitignore
packages/mobile/README.md
packages/mobile/capacitor.config.ts

This PR combines `capacitor-sample.config.ts` and the gitignored `capacitor.config.ts`. `capacitor.config.ts` used to contain developer-specific settings such as the local IP, so it was not checked in to Git. By putting it in Git and using environment variables, we can ensure that changes to things such as plugin configurations are mirrored to all developers, but developers can still set their local IP without having to change a file that is under version control. This also makes the workflow easier for CI, because `capacitor.config.ts` would need to be modified with `jq` or `sed` otherwise.
```
- Use environment variables to set Capacitor server
- Update docs
```
N/A
- __Desktop__
- __Mobile__
Verified that `capacitor.config.json` is generated properly when using environment variables …

chore: make Capacitor setup easier and CI-friendly

---

packages/mobile/android/app/src/main/java/org/iota/firefly/mobile/alpha/MainActivity.java
packages/mobile/android/app/src/main/java/org/iota/firefly/mobile/alpha/WebViewSettingsPlugin.java

This PR implement a Capacitor plugin inside the Android project folder to set default settings on webview and delete webview cache at the activity stop state.
```
- Implement "internal" Capacitor plugin only for Android to set default webview settings.
- Implement clean webview cache at `Stop` activity state change.
```
Remember close manually
- __Desktop__
- __Mobile__

feat: android capacitor webview settings new*

---

packages/mobile/App.svelte
packages/mobile/public/index.html

Current behavior:
1- The splash screen hides before locales are loaded, notably visible at loading them.
2- There is a type mismatch when loading the css main file. Also based on this info:
- https://web.dev/preload-scanner/
- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload
seems that there is room for improvment.
This PR uses the `tick` Svelte function to wait until the locales are applied to finally hide the splash screen.
Also removes the `type` property on the `link` tag.
Lastly I added the `link` tags with `preload` value for CSS and JS main files ["...to start loading early in the page lifecycle, before browsers' main rendering machinery kicks in. This ensures they are available earlier and are less likely to block the page's render, improving …

fix: init performance on mobile

---

packages/shared/components/organisms/AccountActivity.svelte
packages/shared/lib/core/profile-manager/api/events/newOutput.ts
packages/shared/lib/core/profile-manager/api/events/newTransactionInclusionEvent.ts
packages/shared/lib/core/profile-manager/api/events/subscribe.ts
packages/shared/lib/core/profile-manager/api/events/unsubscribe.ts
packages/shared/lib/core/profile-manager/api/index.ts
packages/shared/lib/core/profile-manager/api/types/transactionInclusionEvent.ts
packages/shared/lib/core/profile/actions/active-profile/login.ts
packages/shared/lib/core/profile/actions/active-profile/logout.ts
packages/shared/lib/core/wallet/actions/trySend.ts
packages/shared/lib/core/wallet/classes/activity.class.ts
packages/shared/lib/core/wallet/stores/all-account-activities.store.ts
packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts

The TransactionInclusion event gets handled by searching through all activities and updating one if the transaction id matches.
To test that, i needed to add a transaction instantly after sending one.
```
- update inclusion state via event
- add activity for new transactions
```
Closes #3370 
- __Desktop__
- __Mobile__

Feat: Handle Transaction inclusion event

---

packages/shared/components/inputs/ImportTextfield.svelte
packages/shared/lib/core/profile/actions/new-profile.ts
packages/shared/routes/setup/Password.svelte

Fixed the rust error upon importing an existing account with a recovery phrase
```
- Stronghold initiliazed without a password
- Better rust error logging
```
https://github.com/iotaledger/firefly/issues/3432
- __Desktop__
- __Mobile__

fix: create password upon recovery

---

packages/shared/lib/core/profile-manager/api/events/newOutput.ts
packages/shared/lib/core/profile-manager/api/events/newTransactionInclusionEvent.ts
packages/shared/lib/core/profile-manager/api/events/spentOutput.ts
packages/shared/lib/core/profile-manager/api/events/subscribe.ts
packages/shared/lib/core/wallet/stores/all-account-activities.store.ts

Handle spent out event. Update balance when a new spent output event is emitted. 
This PR also removes the iteration over all accounts. We receive `accountId` from wallet-rs so it should be used and only the account for which the event is received should be updated. 
```
```
- __Desktop__
- __Mobile__

feat: handle spent output event

---

packages/shared/components/Text.svelte

Previously, any checkbox text when unchecked then re-checked, the styling does not update accordingly.
```
- Added logic to ensure text colors are updated properly
```
Closes #3167
- __Desktop__
- __Mobile__
Navigate to where there is a checkbox, and check/uncheck it, making sure the colors update accordingly.

fix: checkbox text component

---

packages/shared/routes/setup/OnboardingNetwork.svelte
packages/shared/routes/setup/OnboardingProtocol.svelte
packages/shared/routes/setup/Profile.svelte

Fixed the onboarding routes so it correctly creates a developer or normal profile
```
- Get developer setting from newProfile that is set when navigating to new profile flow
- Change where a profile is created for developer profile after they select network
- Updated feature flags for protocol page to be based of protocol and network when not a developer profile
```
...
- __Desktop__
- __Mobile__
> Please describe the …

fix: fix onboarding route network selection and back buttons

---

packages/shared/components/inputs/UnitInput.svelte

Needed to add some checks to the unit input so that it would only set the unit if one was not provided or if the token metadata had changed
```
- modify reactive setting in UnitInput
```
- __Desktop__
- __Mobile__

fix: persist unit on back from send confirmation popup

---

packages/shared/components/inputs/Dropdown.svelte
packages/shared/components/inputs/Dropdown2.svelte
packages/shared/components/inputs/Pin.svelte
packages/shared/lib/utils/isNumberLetterOrPunctuation.ts

Replaced `keyCode` with `key`and `code` property of `KeyboardEvent`
```
- replaced `keyCode` with `key`and `code` in Pin/Dropdown/Dropdown2
- replaced arrow functions with regular functions
- added missing types
```
closes: https://github.com/iotaledger/firefly/issues/3359
- __Desktop__
- __Mobile__

fix: deprecated keyCode

---

packages/shared/components/inputs/Input.svelte

Surrounding an `x` by numbers in input causes to format the `x` as a multiplication character because of the OpenType font features
```
- Adds font-feature-settings CSS attribute to Input
```
closes #1037 #2014
- __Desktop__
- __Mobile__
Type `3x3` inside an input

fix: disables "calt" font feature in Input [stardust-develop]

---

packages/shared/components/Profile.svelte

Adds truncate and fixed width for profile name because if the name is too big it will obscure others in the Profile selection screen
closes #1721
- __Desktop__
- __Mobile__

fix: adds truncate to profile name [develop]

---

packages/shared/components/inputs/InputContainer.svelte

Adds tabindex condition to InputContainer's button, so it is set as -1 when the component's slot is not empty
closes #3584 
- __Desktop__
- __Mobile__
Try tabbing inputs in a form like the add node one

fix: input tabbing

---

packages/shared/components/inputs/Input.svelte

Surrounding an `x` by numbers in input causes to format the `x` as a multiplication character because of the OpenType font features
```
- Adds font-feature-settings CSS attribute to Input
```
closes #1037 #2014
- __Desktop__
- __Mobile__
Type `3x3` inside an input

fix: disables "calt" font feature in Input [develop]

---

packages/shared/components/Button.svelte
packages/shared/components/inputs/InputContainer.svelte
packages/shared/components/popups/PasswordPopup.svelte

Adds type button to InputContainer's button, because the default is type submit and it was always emitting a submit event when clicked.
Moves the handle submit function call to on:submit of containing form because the button of type submit tries to submit its parent form element and emits the submit event on it.
closes #3582 
- __Desktop__
- __Mobile__
- Try any action that shows the password popup
- Write the password and press the Enter key
- It should submit the password correctly

fix: password key submit

---

packages/shared/components/atoms/tiles/ActivityTile.svelte

Claiming button doesn't jolt vertically or horizontally if spinner is loading.
...
```
- Fixed horizontal spacing (relative spacing)
- Fixed vertical spacing (set pixels)
```
closes: #3594 
...
- __Desktop__
- __Mobile__
...

ui: persist activity tile width

---

packages/shared/lib/core/profile/actions/active-profile/login.ts
packages/shared/routes/setup/Congratulations.svelte

When we make a new profile with a new seed then we will only have 1 account and no addresses used, therefore we don't need to use the recoverAccounts method to find accounts.
```
- check if profile is not new setup type before recovering accoutns
```
...
- __Desktop__
- __Mobile__
> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes work as …

fix: don't restore accounts on new profile

---

packages/shared/components/inputs/Password.svelte
packages/shared/routes/setup/Password.svelte

When long passwords are used to create a new profile, the app freezes because of the zxcvbn password strength algorithm, and I've limited the number of characters being used in this function as [recommended in lib's repo readme](https://github.com/dropbox/zxcvbn#user-content-performance)
```
- adds wrapper function to check password strength
```
closes #1172
- __Desktop__
- __Mobile__
Create a new profile, copy and paste a password with 256 characters like this:
```
qt\V;;W-hÄP".^bWeWjs}Uds"^.9eGUa;{lV|E?u3ü)l-7~cmzZ4SfggQsYzi.1^hWZVU!NsLICj0X*%>epd\ÜmcZPS!eBLQ P>NKIDh71?Zvb_<Cbgs%yöyoyX4Q8taü${8|'Xf+HJ9{V0"3kREfSAOßÜ@_&1ku3Gßö8;9LPlPIo{BPB<5N 5|(9cHJx3?k.c}%*q7Z2PKÄö(BAb/t%gv%bFfJ!6zü7e8ä9apqV'574v@''ü}{W_eCN%O7e
```
Please …

fix: freezing long password [develop]

---

packages/shared/components/Drawer.svelte
packages/shared/components/popups/Index.svelte
packages/shared/locales/de.json
packages/shared/locales/en.json

Added close buttons to mobile popups.
```
- Added an option to enable a close button for the drawer component
```
Closes #3656
- __Desktop__
- __Mobile__
...

chore: add close buttons to mobile popups

---

packages/shared/components/atoms/tiles/ActivityTile.svelte
packages/shared/components/popups/ActivityDetailsPopup.svelte
packages/shared/lib/core/wallet/actions/hideActivity.ts
packages/shared/locales/en.json

Temporarily changing the reject wording to hide until we implement the hide or return functionality.
```
- Rename reject to hide in the activity tile and popup button as well as on confirmation popup and notifications.
```
...
- __Desktop__
- __Mobile__
...
> Please tick all of …

fix: change reject activity wording to hide

---

packages/shared/components/SettingsMenu.svelte

In desktop the icons in the settings homepage are gray, and blue when hovered. This PR brings that back
```
fix: desktop settings homepage wrong icons color
```
...
- __Desktop__
- __Mobile__
...

fix: desktop settings homepage wrong icons color

---

packages/mobile/App.svelte

On mobile devices, the navigator language is loaded regardless of whether another language is configured or not.
```
- Changed the language setup
```
...
- __Desktop__
- __Mobile__

fix: wrong locals are loaded on mobile

---

packages/shared/components/MainMenu.svelte

This PR aims to set the profile circle always blue because Firefly is not yet compatible.
Additionally, I polished a bit the style of the profile circle to match figma
```
style: set profile icon circle always blue
```
Close #3714
- __Desktop__
- __Mobile__
...
> Please tick all …

style: set profile icon circle always blue

---

packages/shared/routes/login/Login.svelte

Re-enable last logged profile check for mobile to display the pin screen directly if there is a previously logged profile stored
```
- feat: re-enable last logged profile for mobile
```
Close #3219
- __Desktop__
- __Mobile__
... …

feat: re-enable last logged profile for mobile

---

packages/mobile/App.svelte

On app start, the locales where not being loaded on the first screen and that was before the components were mounted before the locale was ready. This PR aims to fix that by making sure it first loads the locale and then mounts the components.
Additionally, in this PR I added some minor changes that I felt were needed in `App.svelte `: 
- Show splash screen for 3 seconds at least to avoid quick flashes (this can be reduced if we want)
- Replace `fetchMarketData` with `pollMarketData`
```
```
> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-req …

fix: route components mounted before locale loaded (mobile)

---

packages/shared/routes/dashboard/settings/Settings.svelte

Adjusted the bottom margin of the settings list with a css safe-area variable
```
- Changed the bottom margin calculation of the settings component
```
Closes #3699
- __Desktop__
- __Mobile__
...

fix: settings bottom safe area

---

packages/shared/components/Idle.svelte
packages/shared/routes/dashboard/wallet/Wallet.svelte

This PR aims to fix 2 issues:
- If you had the receive QR drawer open when the idle timeout was triggered, the app crashed because the `Wallet.svelte` component wasnt destroyed at a right time because of the child transitions. Adding `|local` to the transitions fixes the issue and allows the component to destroy on time without the need to wait for the transitions. [Source](https://svelte.dev/docs#template-syntax-element-directives-transition-fn-transition-events): `Local transitions only play when the block they belong to is created or destroyed, not when parent blocks are created or destroyed.`
- On mobile, for the idle timeout to start, the user had to do some explicit interaction to the screen, …

fix: crash idle logout & mobile initialization

---

packages/shared/lib/appSettings.ts

This PR sets the `appSettings.theme` to `system` the first time the user uses Firefly. 
⚠️ This change affects both **desktop** and **mobile**.
```
```
Close #3653
- __Desktop__
- __Mobile__
... …

feat: initialize firefly theme to `system` by default on every platform

---

packages/shared/components/drawerContent/AccountSwitcher.svelte
packages/shared/components/drawerContent/AddressHistory.svelte
packages/shared/components/drawerContent/ExportTransactionHistory.svelte
packages/shared/components/drawerContent/HideAccount.svelte
packages/shared/routes/dashboard/wallet/views/ManageAccount.svelte

This PR centers the headers of all wallet actions and adjusts the padding.
```
- Wallet actions drawer headers centered
- Wallet actions drawer padding changed to 20px (except top: 24px)
```
Closes #3749
- __Desktop__
- __Mobile__
...

chore: center wallet action headers and adjust paddings

---

packages/shared/routes/dashboard/settings/views/SettingsHome.svelte

This PR should hide all settings not needed for the current mobile version.
```
- Hides NetworkStatus
- Hides CrashReport 
```
Closes #3717
- __Desktop__
- __Mobile__
...

chore: hide settings for mobile

---

packages/shared/components/organisms/AccountActivity.svelte
packages/shared/components/popups/SendConfirmationPopup.svelte
packages/shared/lib/stronghold.ts

Closes send confirmation popup after sending output 
closes #3753
- __Desktop__
- __Mobile__
- Go through the send transaction flow with the stronghold locked
- Go through the send transaction flow with the stronghold unlocked

fix: send confirmation popup close

---

packages/backend/bindings/capacitor/android/src/main/java/org/iota/fireflyactorsystem/WalletPlugin.java
packages/backend/bindings/capacitor/ios/Plugin/Plugin.swift

This Pr fix the Capacitor bindings wallet plugin at `listen` function. There was only needed to resolve Capacitor call and return without cancel the call 😅
Closes #3709
- __Desktop__
- __Mobile__
...

fix: bindings capacitor login crash

---

packages/mobile/android/app/src/main/java/org/iota/firefly/mobile/alpha/WebViewSettingsPlugin.java

This PR disables the text size change through androids accessibility features. 
```
- Set the text zoom webview setting to 100 
```
Closes #3097
- __Desktop__
- __Mobile__
...

chore: disable accessibility text size changes

---

packages/shared/components/drawerContent/AccountSwitcher.svelte

This PR removes the action sheet button for exporting an account's transaction history. 
```
- Removed action sheet button for transaction history export
```
Closes #3786
- __Desktop__
- __Mobile__
...

chore: disable csv export of transaction history

---

packages/shared/components/inputs/Address.svelte
packages/shared/routes/dashboard/wallet/views/Send.svelte

This PR changes the style of the address textarea to display the entire address.
I disabled the floating-label for mobile, so it doesn't change the textarea size, when focused. Let me know, If the floating-label should definitely be shown, then I will change it back.
@amadeu2 The one line solution was hard/not to implement with the textarea. I discussed that with Begoña and we came to the conclusion that it is better to do it more like in desktop. At least for the time being.
@begonaalvarezd I realised that the line break doesn't work on android (Don't know why) so I added a space before:
`placeholder={"${localize('general.sendToAddress')} \n${addressPrefix}..."}`
No focus:
Focus:
```
- Changed mobile styling of the address component's textarea
- Disabled the floating-label for mobile
``` …

style: change address input style to display the entire address

---

packages/shared/routes/dashboard/wallet/views/Send.svelte

This PR adds a touch padding to the send flows QR code button
```
- Added touch padding of 12px to the send flows QR code button
```
Closes #3825
- __Desktop__
- __Mobile__
...

chore: add touch padding to QR code button

---

packages/shared/components/drawerContent/AccountSwitcher.svelte
packages/shared/routes/dashboard/wallet/views/Send.svelte

This PR should fix the crash when an action sheet is called again before the last call has finished.
```
- Added flag to check if the action sheet has been called
```
Closes #3782
- __Desktop__
- __Mobile__
...

fix: action sheet crash

---

packages/desktop/electron/main.js
packages/desktop/package.json
yarn.lock

Reverts iotaledger/firefly#3826
This PR is needed because the refresh issue is slowing in development, I was investigating but it was inconclusive.
We still need to update the Electron version for sure, but solving this issue is a priority.
closes #3849

Revert "chore: update electron"

---

packages/shared/components/molecules/ExpirationTimePicker.svelte
packages/shared/components/popups/SendConfirmationPopup.svelte

set default expiration time if storage deposit is required
```
- fix race condition by adding a reactive statement to it
- remove unused part of the code
```
Closes #3902 
...
- __Desktop__
- __Mobile__
...

fix: set default expiration time if storage deposit is required

---

packages/shared/lib/participation/staking.ts

The way of formatting and displaying Shimmer tokens has changed.
```
- Adjust logic of SMR token formatting
```
Closes #3959 
- __Desktop__
- __Mobile__
Use a profile that has at least one account with Shimmer token rewards from the first staking period.
> Please tick all of the …

fix: SMR token amount formatting

---

.github/workflows/crowdin.yml

Adds a new branch to Crowdin for Stardust strings. Existing strings from `develop` will be carried over.
Note: Once stardust-develop is merged back into develop we need to revert the workflow changes.
...
```
- Updates crowdin workflow for Stardust
```

Adds Crowdin

---

packages/mobile/ios/App/Podfile
packages/mobile/ios/App/Podfile.lock

This PR aims to fix the weird Svelte stores updates on iOS
...
```
```
...
- __Desktop__
- __Mobile__
...

fix: revert to Cocoapods 1.11.2

---

packages/mobile/App.svelte
packages/mobile/android/app/src/main/java/org/iota/firefly/mobile/alpha/WebViewSettingsPlugin.java
packages/shared/components/Drawer.svelte

This PR fixes the exit app issue on Android.
...
```
- Added logout() before call exitApp()
- Clean webview cache at exit app.
- Added drawer methods to implement in the future.
```
Closes #3930 
- __Desktop__
- __Mobile__
...

fix: Android exit app without crashing

---

packages/shared/components/StakingAssetTile.svelte
packages/shared/locales/en.json
packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte

...
```
```
...
- __Desktop__
- __Mobile__
...

enhancement: add tooltip for glow units

---

packages/shared/components/molecules/VerificationBadge.svelte

We decided to only show the grey unverified badge when the asset is new. Now if the user skips we remove the badge all together.
```
- Remove verification badge on skipped verified assets.
```
...
- __Desktop__
- __Mobile__
... …

fix: verification badge on new assets only

---

packages/shared/components/TextHint.svelte
packages/shared/components/popups/ConfirmationPopup.svelte

This is to standardise and align the textHint across the app
```
- Remove border of text hint
- Update colours
- Add opacity to darkmode
```
...
- __Desktop__
- __Mobile__
...

fix: text hint colours and styles

---

packages/shared/components/inputs/AssetDropdown.svelte
packages/shared/components/molecules/AssetIcon.svelte

We need to display the accurate asset icon in the drop down of the send form.
```
- Make asset icon component reactive to asset
- Add AssetIcon to dropdown
- Make asset tile bg transparent in darkmode for the asset dropdown
```
...
- __Desktop__
- __Mobile__
...
> Please tick …

fix: use asset icon in dropdown

---

packages/backend/Cargo.lock
packages/backend/Cargo.toml
packages/backend/bindings/node/native/Cargo.lock

Bump wallet.rs rev to get the optional gap limit for background syncing
```
- Bump wallet.rs rev to get the optional gap limit for background syncing
```

Update wallet.rs rev

---

packages/shared/components/inputs/Pin.svelte

This PR aims to fix the Android edge case at Pin component.
```
- Removed isAndroid check, since the behavior described here https://trello.com/c/6WHc9HqN/96-button-doesnt-become-active-after-entering-the-pin
is like it's not applied, I reviewed the Capacitor code but just in case, since this change does not affect iOS.
- Added inputmode="numeric", this change allow us to change input type from `tel` to `password`,
- Added the attribute autocomplete=off the auto-suggest feature or other event might follow the keydown event and invalidate it. More details here: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values
```
Closes #4010 
- __Desktop__
- __Mobile__
> Please describe the specific …

fix: pincode android edge case

---

packages/shared/components/inputs/AssetAmountInput.svelte
packages/shared/components/popups/SendFormPopup.svelte

On "available balance" click, in german a decimal dot was used
```
- On "available balance" click, use decimal comma in german
```
Closes #4095 
- __Desktop__
- __Mobile__
...

fix: german decimal comma on send

---

packages/desktop/package.json

With a recent update for `Ubuntu 22.04`, the Electron development environment does **NOT** work anymore unless run with the `--no-sandbox` flag. 
This PR makes changes that allow the developer instance to run on Linux, and **only affects development; NOT production environments**.
See more on this [issue](https://github.com/ebkr/r2modmanPlus/issues/735).
```
- Add "--no-sandbox" flag to "start:electron" NPM script
```
_N/a_ …

fix: update desktop `package.json` file 

---

packages/shared/components/inputs/RecipientInput.svelte

This PR aims to fix what was reported here https://github.com/iotaledger/firefly/pull/4171/files#r940298304
```
fix: modal.open crash in recipient input on single wallet profiles
```
...
- __Desktop__
- __Mobile__
...
> Please tick all of the following boxes that are relevant to …

fix: `modal.open` crash in recipient input on single wallet profiles

---

packages/shared/components/modals/AssetActionsMenu.svelte

This PR fixes the issue, that after hiding a token in `TokenInformationPopup`, all values become `undefined`
```
- Locally update asset instead of getting it from the store
```
Closes #4146 
- __Desktop__
- __Mobile__
...

fix: fix tokeninfo after hiding token

---

packages/mobile/capacitor/plugins/secure-filesystem-access/android/src/main/java/org/iota/plugins/securefilesystemaccess/SecureFilesystemAccessPlugin.java

This PR modifies only on Android the current filesystem export action by using Sharesheet with the aim to simplify the Stronghold backup flow. Allowing to use quick share classic actions, nearby device share with bluetooth, wifi, usb cable, or uploading to Google Drive app or any app desired to transfer the file to an external device.
The same Sharesheet could be used to export transaction history or any file desired. Still we've to implement it, but it's way simpler.
Tested with Android 7, 8, 9, 10, 11, 12.
Closes #2473 
...
> Please select any platforms where your changes …

feat: implement export Stronghold with Android Sharesheet

---

packages/shared/components/Toast.svelte

Removes dismiss button duplication in mobile, so the generic dismiss button will only appear when there are no actions.
```
- Fixes conditions for displaying the generic dismiss button
- Fixes the styling of generic dismiss button
```
closes #4185
- __Desktop__
- __Mobile__
- Test different types of toast ('info', 'warning', 'error') and with and without actions (like the toast after the migration flow)

fix: if toast has action do not show generic dismiss button

---

packages/shared/components/inputs/Amount.svelte

The keyboard for amount input in iOS doesn't have a decimal point in it, so I've changed the `Input` prop `type` from `tel` to `number` in mobile and added the `inputmode` prop with the value `decimal` and now the iOS keyboard shows the decimal point
...
```
- Changed the `Input` prop `type` from `tel` to `number` in mobile
- Added the `inputmode` prop with the value `decimal` in it
```
closes #4021
- __Desktop__
- __Mobile__

fix: amount input with decimal point in iOS

---

packages/backend/bindings/capacitor/ios/Plugin/Plugin.swift
packages/mobile/android/app/src/main/AndroidManifest.xml

Auto backup of sensitive data is not good for the app security so this PR should address this issue
```
- Sets allowBackup flag from AndroidManifest application to `false`
- Sets resource value as `true` for excluding storagePath from backup for iOS Capacitor plugin
```
closes #4147 
- __Desktop__
- __Mobile__
...

feat: disable auto backup

---

packages/shared/components/ProfileActions.svelte
packages/shared/tailwind.config.js

closes #3700 
- __Desktop__
- __Mobile__
- Open the Profile Menu on mobile
- Switch between dark and light themes

fix: adjusts styling of ProfileActions as figma

---

.github/workflows/build-desktop.yml
.github/workflows/ci.lint.yml
.github/workflows/ci.snyk.yml
.github/workflows/ci.test.yml
.github/workflows/handbook.yml

GitHub actions with hosted runners are not working because `ubuntu-18.04` has been removed from them, so we need to update to `ubuntu-20.04` or `ubuntu-22.04`, in this PR I've updated to `ubuntu-20.04`
https://github.com/actions/runner-images/issues/6002

fix: updates deprecated version of ubuntu for github hosted runners

---

packages/desktop/package.json
packages/shared/package.json
yarn.lock

We optimized the building of packages in wallet.rs for the latest electron versions. Additionally, we updated keytar so that the N-API native module is used which enhances build speed by downloading it from GH as a prebuilt binary. I opened an issue for wallet.rs to do the same https://github.com/iotaledger/wallet.rs/issues/1382
...
```
- updated @iota/wallet to alpha.21
- update keytar to 7.9.0
- updated yarn.lock
```
https://github.com/iotaledger/firefly/issues/4163
...
- __Desktop__
- __Mobile__
Run `yarn && cd packages/desktop && yarn build && yarn compile:alpha:OS_TYPE`
CI pipeline for building desktop app: https://github.com/iotaledger/firefly/actions/runs/2909696348
...
> Please tick all of the following boxes that …

update: wallet-rs to 21

---

packages/mobile/App.svelte
packages/shared/routes/dashboard/settings/views/SettingsHome.svelte

This PR removes the notification settings from the settings list for the upcoming production release as system notifications for mobile are not implemented yet.
```
- Removed notification item from the settings list
- Disabled notifications as default
```
Closes #4304
Closes #4311
- __Desktop__
- __Mobile__
...

fix: disable notification settings

---

packages/shared/components/popups/Backup.svelte

This PR fixes an issue that prevents the password popup of the profile backup from being canceled/closed
...
```
- Removed preventClose flag from password popup call 
```
Closes #4275
- __Desktop__
- __Mobile__
...

fix: remove prevent close flag from password popup call

---

packages/shared/routes/setup/backup/views/VerifyRecoveryPhrase.svelte

Fixes error when recovery phrase verification is completed too quickly
...
```
- Stop additional verification choices once mnemonic has been verified
```
Fixes #4195
...
- __Desktop__
- __Mobile__
Try verify a mnemonic by pressing lots of random words on device
...

fix: mnemonic was already stored error

---

packages/mobile/App.svelte
packages/shared/components/popups/AddNode.svelte
packages/shared/components/popups/BalanceFinder.svelte
packages/shared/components/popups/CreateAccount.svelte
packages/shared/components/popups/DeleteProfile.svelte
packages/shared/components/popups/HideAccount.svelte
packages/shared/components/popups/Password.svelte
packages/shared/lib/app.ts
packages/shared/routes/dashboard/settings/views/security/ChangePincode.svelte
packages/shared/routes/dashboard/wallet/views/ManageAccount.svelte
packages/shared/routes/dashboard/wallet/views/Send.svelte
packages/shared/routes/login/views/EnterPin.svelte
packages/shared/routes/setup/Password.svelte
packages/shared/routes/setup/Profile.svelte
packages/shared/routes/setup/import/views/BackupPassword.svelte
packages/shared/routes/setup/import/views/TextImport.svelte
packages/shared/routes/setup/protect/views/Pin.svelte
packages/shared/routes/setup/protect/views/RepeatPin.svelte

Ensures clean keyboard open and close animations on iOS and Android 
...
```
- Updates keyboard close/open animation transition speeds
```
- __Desktop__
- __Mobile__

improvement: polish keyboard open and close animations

---

packages/shared/components/ToastContainer.svelte
packages/shared/routes/login/views/EnterPin.svelte

In mobile, each time you logged in, multiple actors were being created such as you will have as many active actors as times you logged in +1. This lead the Nduplicated notifications appearing, one per actor. This PR aims to fix that.
Additionally, for the notifications, in order to avoid re-rendering the array, I removed the `#key` and substituted it by a keyed `each` loop- 
```
- fix: duplicated actors
```
Closes #4353
- …

fix: duplicated actors

---

packages/shared/routes/dashboard/settings/views/security/ChangePassword.svelte
packages/shared/routes/dashboard/settings/views/security/ChangePincode.svelte

Adds prevent default to ChangePin's and ChangePassword's submit event to prevent the app to reload after changing one of them.
- Add preventDefault event modifier to on:submit in ChangePin.svelte form
- Add preventDefault event modifier to on:submit in ChangePassword.svelte form
closes #4351 
- __Desktop__
- __Mobile__
- Change password
- If the app does not reload so the fix is working
- Change pin
- If the app does not reload so the fix is working

fix: adds prevent default to change pin and password

---

packages/shared/routes/setup/backup/views/RecoveryPhrase.svelte

closes #4358 
- __Desktop__
- __Mobile__

fix: adds bottom padding to recovery phrase setup title

---

packages/shared/components/MainMenu.svelte

This PR removes the horizontal scroll showed only on Android at sub menu transitions, as we forced to show scroll as workaround to show scrolls on inner divs.
```
```
...
- __Desktop__
- __Mobile__
...

fix: disable horizontal scroll on main div

---

packages/shared/routes/dashboard/settings/views/security/ChangePassword.svelte

For smaller screens is needed to hide the title and text to allow the user tap the button to confirm action.
```
```
...
- __Desktop__
- __Mobile__
...

fix: hide title at show keyboard for mobile

---

packages/shared/lib/core/wallet/utils/transactions/getSenderFromInputs.ts

Correctly get subject if expired output is contained
...
```
- Add extra condition for fetching address from expired unlock condition
```
closes: https://github.com/iotaledger/firefly/issues/4365
...
- __Desktop__
- __Mobile__
...

fix: correct subject if expired output

---

packages/shared/components/ActivityDetail.svelte

This PR removes the copy buttons in the activity details and adds copy via address click instead.
```
- Removes address copy button
- Adds set to clipboard function to address text
```
Closes #4387
- __Desktop__
- __Mobile__
...

chore: add address click to copy for activity details

---

packages/shared/components/inputs/Amount.svelte
packages/shared/components/inputs/Input.svelte

This PR changes the input component to select the right decimal sign no matter if a comma or dot is pressed via keyboard.
...
```
```
Closes #4379
Closes #4393 
- __Desktop__
- __Mobile__
...

fix: force the right decimal sign for the amount calculation

---

package.json
packages/desktop/package.json
yarn.lock

Update packages that have high severity vulnerabilities.
...
```
- Update electron to 19.0.16
- Update electron-builder to 23.5.1
- Fix shell-qoute subdependency to 1.7.3 to mitigate vulnerability
```
closes: https://github.com/iotaledger/firefly/issues/4525
...
Try also compiling the app locally, since electron-builder also changed.
- __Desktop__
- __Mobile__
...

chore: upgrade electron

---

packages/shared/lib/core/router/enums/routes.ts

> Adapted the link to FAQ and documentation 
...
Changed the links from 
https://wiki.iota.org/learn/wallets/firefly/faq-and-troubleshooting --> 
https://wiki.iota.org/wallets/firefly/faq-and-troubleshooting
> Please list any related issues using [development keywords]().
fixes #4561 
[FAQ - Link is broken](https://github.com/iotaledger/firefly/compare/develop...hadze:firefly:hadze-patch-wronglink?expand=1#top)
...
- __Desktop__
- __Mobile__
...

Fixed wrong links for FAQ and documentation sites

---

packages/shared/components/popups/SendConfirmationPopup.svelte

Fixes the issue that on a transaction with required storage deposit the default expiration time isnt used
```
- fix default expiration time
```
Closes #4595 
- __Desktop__
- __Mobile__
...

fix: fix default expiration time

---

packages/shared/routes/onboarding/views/ledger-setup/views/ConnectLedgerView.svelte
packages/shared/routes/onboarding/views/storage-protection-setup/views/SetupPinProtectionView.svelte

To improve UX, it is better to initiate the Ledger Nano status polling a few pages earlier before it's actually checked in the connection view. 
The PIN setup page was chosen as that was the common view between all Ledger flows that was closest to connection check view. If the views were chosen where the user decides between software vs Ledger or mnemonic vs Stronghold vs Ledger, then there would have been duplicate logic to initiate and clear any status polling.
```
- Remove Ledger Nano status polling from connection check view
- Add Ledger Nano status polling to
```
> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking- …

fix: initiate Ledger Nano polling earlier in the onboarding flow

---

packages/shared/components/BottomNavigation.svelte
packages/shared/routes/dashboard/wallet/Wallet.svelte
packages/shared/routes/dashboard/wallet/views/AccountAssets.svelte
packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte

This PR fixes the issue that items of the asset list or transaction history are cut off through the bottom navigation.
- Adds a bottom offset calculation for the main views content area
Closes #4207
- __Desktop__
- __Mobile__
...

fix: content scroll overflow

---

packages/shared/components/QRScanner.svelte
packages/shared/routes/dashboard/wallet/views/Send.svelte

This PR fixes an issue that causes the app to close when the back button is pressed while the QR scanner is open
```
- Added back button logic for QR scanner
```
Closes #4490
- __Desktop__
- __Mobile__
...

fix: qr scanner back button closes app

---

packages/shared/components/modals/AccountActionsMenu.svelte
packages/shared/components/popups/DeleteAccount.svelte
packages/shared/lib/core/profile-manager/actions/deleteAccount.ts

This PR hides the delete wallet button when it is not available
```
- Only show delete wallet button when it is available
- Removes hasMultipleAccounts props in DeleteAccount.svelte and the code around it
```
closes #4462 
- __Desktop__
- __Mobile__

fix: only show delete wallet when available

---

packages/shared/routes/onboarding/views/shimmer-claiming/views/ClaimRewardsView.svelte

Currently the UI allows the user to continue making claimed transactions if they searched after making a previous one. The library logic does not support it, so we must enforce it also on the UI level.
```
- Only allow searching if no claiming transactions have been made
```
Closes #4664
- __Desktop__
- __Mobile__
> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ …

fix: enforce one claiming transaction per account

---

packages/shared/lib/address.ts
packages/shared/lib/app.ts
packages/shared/lib/common/deep-links/enums/wallet-context.enum.ts
packages/shared/lib/common/deep-links/types/deep-link-request.type.ts
packages/shared/lib/common/deep-links/types/wallet-context.type.ts
packages/shared/lib/common/deep-links/wallet-context-handler.ts
packages/shared/lib/typings/sendParams.ts
packages/shared/locales/en.json
packages/shared/routes/dashboard/Dashboard.svelte
packages/shared/routes/dashboard/wallet/views/Send.svelte

Implemented deep linking parsing for `swapOut`.
...
```
- Added swapOut operation parser
- Disable index, receiverAddress and chainId field when regular tx
```
closes: #4540
closes: #4542
...
- __Desktop__
- __Mobile__
Use the following deep link:
iota://wallet/swapOut/atoi1qz0mvjzjfwt5wcy8j8daw6avh67z77kquwkwzr5fvuu6pfzpjqgz7cptqex/?amount=1000&chainId=4002&receiverAddress=0xF65e3cCbe04D4784EDa9CC4a33F84A6162aC9EB6
...

feat: parse deep link

---

packages/shared/lib/core/profile-manager/actions/events-handlers/handleSpentOutputEvent.ts

The problem with the claim bug:
if i send some native tokens, it always uses an output which bundles all of my native tokens (https://explorer.shimmer.network/testnet/transaction/0xc30bb63eea931c9eb9538b8f9a7e2dc58c1d20ee6cc55246fc84acf0f538217e). Then we get the output for the recipient (outputA) and the remainder back to me which contains all remaining native tokens (outputB). 
When i send another portion of native tokens, i get the event that outputB  is spent. Because we matched the spent event with the activity by transactionid we think that it is claimed. Now i match the spent event with the activity by outputId 
```
- fix claim status for native tokens
```
Closes #4721 
- __Desktop__
- __Mobile__
> Please describe …

fix: fix claim status for native tokens

---

packages/shared/components/atoms/buttons/TooltipIcon.svelte
packages/shared/components/atoms/tiles/TransactionActivityTile.svelte
packages/shared/components/inputs/OptionalInput.svelte

Fix TooltipIcon style
Add min width to claim/reject Buttons
- __Desktop__
- __Mobile__

fix: tooltips icons buttons

---

packages/mobile/App.svelte
packages/mobile/capacitor/capacitorApi.ts
packages/shared/lib/tests/mocks/platform.ts
packages/shared/lib/typings/platform.ts

The App still uses english as initial language. This RP changes the initial selection to the system language. 
```
- Selects the navigator language when the app is started for the first time
```
- __Desktop__
- __Mobile__
...

fix: set system language as initial language

---

packages/shared/lib/keyboard.ts
packages/shared/routes/dashboard/settings/views/security/ChangePassword.svelte
packages/shared/routes/setup/Password.svelte

This PR adds the possibility for iOS to tab through the input fields of the password create and change forms via pressing enter.
```
- Adds a function to enable tabbing for form input fields via enter key
- Adds tab change with enter key for password creation form
- Adds tab change with enter key for password change form
```
Closes #4472
- __Desktop__
- __Mobile__
...

chore:  adds tab change between input fields for iOS

---

packages/shared/components/inputs/NumberInput.svelte
packages/shared/components/inputs/TextInput.svelte

Number input needs to have the native HTML `type=number`, otherwise it leads to problems in parsing numbers as it is happening with big.js
So in this PR I've changed the component to not be a wrapper for TextInput, but have the same customizability as it
```markdown
- Changes from `TextInput` to `Input` in `NumberInput`
- Adds text props in `NumberInput`
- Improves code readability in `TextInput`
```
closes #4769 
- __Desktop__
- __Mobile__
- Try to type `.` in AssetAmountInput
- If the app is still interactable so the fix has worked

fix: NumberInput

---

packages/shared/components/popups/Transaction.svelte

Get rid of the custom UI elements on the confirmation page
...
```
- Remove custom elements from confirmation popup
```
closes: #4791 
- __Desktop__
- __Mobile__
...

enhancement: polish UI

---

packages/mobile/components/AccountSwitcher.svelte
packages/mobile/components/TopBar.svelte
packages/mobile/components/buttons/AccountActionsButton.svelte
packages/mobile/components/buttons/ProfileActionsButton.svelte
packages/mobile/components/buttons/index.js
packages/mobile/components/index.js
packages/mobile/features/features.ts
packages/mobile/routes/dashboard/DashboardRouter.svelte
packages/shared/components/atoms/buttons/AccountActionsButton.svelte

This PR initializes the dashboard header
```
- Adds a header section inside the dashboard
- Adds a top bar with buttons for the profile menu, account actions and account switcher to the dashboard header
- Adds a balance display to the dashboard header
- Adds send and receive buttons to the dahsboard header
```
Closes #4934 
Closes #4935 
Closes #4936 
Closes #4937 
Closes #4938
In order to test, you have to:
- in `packages/desktop/index.js` replace `import App from './App.svelte'` with `import App from '../mobile/App.svelte'`
- in `packages/shared/lib/core/profile/actions/active-profile/login.ts` replace `import { loginRouter } from '@core/router'` with `import { loginRouter } from '../../../../../../mobile/lib/core/router'`. 
Activate features in './packages/mobile/features/features.ts': …

ui: dashboard header setup

---

packages/mobile/components/Drawer.svelte
packages/mobile/components/index.js
packages/mobile/features/features.ts
packages/mobile/lib/core/router/dashboard-router.ts
packages/mobile/lib/core/router/enums/dashboard-route.enum.ts
packages/mobile/lib/core/router/helper.ts
packages/mobile/routes/dashboard/DashboardRouter.svelte
packages/mobile/routes/dashboard/wallet/drawers/ReceiveDrawer.svelte
packages/mobile/routes/dashboard/wallet/drawers/index.js

This PR includes the following:
- drawer component
- dashboard drawers based on routing
- receive drawer (without share button because we dont have a share feature)
- split send and receive feature flags and enable receive because the drawer is implemented in this PR
```
feat: add mobile receive drawer
```
Close #4942
- __Desktop__
- __Mobile__
> Please describe the specific instructions, configurations, and/or test cases …

feat: add mobile receive drawer

---

packages/shared/components/inputs/Amount.svelte
packages/shared/components/inputs/KeyValue.svelte
packages/shared/lib/utils.ts
packages/shared/locales/en.json
packages/shared/routes/dashboard/wallet/views/Send.svelte

This PR enables a tag and metadata being sent on the IOTA network.
...
```
- Add tag and metadata for default send flow
- Add generic validation rules
- Disable only when transferring
```
closes: #4916 
...
- __Desktop__
- __Mobile__
...

enhancement: generic tag and metadata

---

packages/shared/components/ActivityRow.svelte
packages/shared/lib/wallet.ts

There is a bug concerning the recipient that was shown in the transaction history. This PR aims to fix it.
**Once this has been merged it should be ported onto mobile as well!**
...
```
- Finds correct recipient from tx payload.
```
closes: #4521
- __Desktop__
- __Mobile__
...

fix: transaction details

---

packages/shared/components/QR.svelte
packages/shared/routes/dashboard/wallet/views/Receive.svelte

It is not possible to scan the QR code with an Android device when the desktop app is in dark mode. This PR adds a white background.
```
- Adjust QR presentation in dark mode
```
Tested on Mac OS, scanning with both iOS and Android.
- __Desktop__
- __Mobile__
Scan the receive address QR code.

fix: QR background colour in dark theme

---

packages/shared/components/inputs/ExpirationDateTimePicker.svelte

ExpirationDatePicker now defaults to the current date
```
- add default value to ExpirationDatePicker
```
Closes #5139 
- __Desktop__
- __Mobile__
...

fix: add default date to expiration date picker

---

packages/shared/components/atoms/ColoredCircle.svelte
packages/shared/components/atoms/index.js
packages/shared/components/atoms/labels/AccountLabel.svelte
packages/shared/components/inputs/RecipientInput.svelte
packages/shared/components/interfaces/option.interface.ts
packages/shared/components/molecules/SelectorInput.svelte
packages/shared/lib/core/account/utils/getAccountColorById.ts
packages/shared/lib/core/account/utils/index.ts

...
```
- Add generic coloured circle component
- Use coloured circle in recipient selector
- Use coloured circle in account label
```
...
- __Desktop__
- __Mobile__
...

enhancement: add account colour to recipient input

---

packages/shared/components/popups/TokenInformationPopup.svelte

This PR fixes the "Send"-button click on TokenInformationPopup , such that it opens the Asset SendForm
```
- open Asset SendForm with the selected asset, if the users clicks on AssetInformationPopup on "Send"
```
Closes #5291
- __Desktop__
- __Mobile__
...

fix: fix send on token-info-popup

---

packages/shared/components/inputs/NetworkInput.svelte
packages/shared/lib/core/utils/crypto/utils/validateEthereumAddress.ts

Fixes the destination network selection when going backwards in send flow
```
- Changes initial value of `selected` in NetworkInput
```
closes #5275 
- __Desktop__
- __Mobile__

fix: NetworkInput initial value given by network address

---

packages/shared/lib/core/layer-2/constants/network-address.constant.ts

Adds the mainnet configuration to the network selector for private networks
...
```
- Added DestinationNetwork.Shimmer to private network addresses.
```
closes: #5300 
...
- __Desktop__
- __Mobile__
...

fix: custom network for l2 destination

---

packages/desktop/views/dashboard/Sidebar.svelte

With this PR the router gets reset if you click the corresponding Sidebar Tab.
```
- reset router on tab change
```
Closes #5317 
- __Desktop__
- __Mobile__
...

enhancement: reset router on tab change

---

packages/shared/components/inputs/RecipientInput.svelte

Smaller height for recipient input, so it fits the screen on minimum size
...
```
- maxHeight set to max-h-48
```
closes: https://github.com/iotaledger/firefly/issues/5314
...
- __Desktop__
- __Mobile__
...

fix: height recipient input

---

packages/desktop/views/dashboard/collectibles/views/DetailsView.svelte
packages/shared/components/inputs/AssetAmountInput.svelte
packages/shared/components/inputs/AssetDropdown.svelte
packages/shared/components/inputs/NftInput.svelte
packages/shared/components/modals/CollectibleDetailsMenu.svelte
packages/shared/components/molecules/SelectorInput.svelte
packages/shared/components/popups/TokenInformationPopup.svelte
packages/shared/components/popups/send/SendFormPopup.svelte
packages/shared/lib/core/wallet/types/new-transaction-details.type.ts

This PR improves the send flow if navigated through the NFT or Native Token "SendButton". In both cases, the asset selection will be disabled
```
- add flag in SendForm if navigated with NFT or Native Token "SendButton"
- disable Tabs
- disable AssetSelection
- disable NFT selection
```
Closes #5316 
- __Desktop__
- __Mobile__
...

enhancement: disable nft/asset select if using nft/asset send button

---

packages/shared/components/inputs/AssetAmountInput.svelte
packages/shared/components/inputs/NftInput.svelte
packages/shared/components/molecules/SelectorInput.svelte

`readonly` prop should have an initial value of null or undefined, because svelte is adding the attribute in the HTML, and the HTML does not understand the `readonly` attribute with false or true value, just understand the absence of `readonly` prop
```
- Sets the initial value of readonly prop in SelectorInput to null
```
- __Desktop__
- __Mobile__

fix: selector input unwanted readonly

---

packages/shared/components/atoms/BalanceSummarySection.svelte
packages/shared/components/popups/StorageDepositBreakdownPopup.svelte
packages/shared/locales/en.json

...
```
```
...
- __Desktop__
- __Mobile__
...

enhancement: storage deposit breakdown per output

---

packages/shared/lib/core/profile-manager/actions/events-handlers/handleTransactionInclusionEvent.ts

Fixes an error that is thrown by the event callback in case the activity is not found
...
```
- add optional chaining to activity
```
- __Desktop__
- __Mobile__
Send an internal transaction with 1 glow and then accept it from your other wallet. No error should be seen in the console.

fix: callback error

---

packages/shared/lib/core/collectibles/enums/attribute-display-type.enum.ts
packages/shared/lib/core/collectibles/enums/index.ts
packages/shared/lib/core/collectibles/enums/standard.enum.ts
packages/shared/lib/core/collectibles/index.ts
packages/shared/lib/core/collectibles/interfaces/attribute.interface.ts
packages/shared/lib/core/collectibles/interfaces/index.ts
packages/shared/lib/core/collectibles/interfaces/nft.interface.ts
packages/shared/lib/core/collectibles/types/attribute.type.ts
packages/shared/lib/core/collectibles/types/collection.type.ts
packages/shared/lib/core/collectibles/types/index.ts
packages/shared/lib/core/collectibles/types/royalties.type.ts

There are two NFT related folders in `lib/core`: `collectibles` and `nft`. `collectibles` is deprecated in favor of `nft` and an artifact of initial work on the NFT milestone.
```
- Delete collectibles folder from lib/core
```
...
- __Desktop__
- __Mobile__
...
> Please tick all …

Refactor: remove collectibles folder from core library

---

packages/shared/components/molecules/NftActivityDetails.svelte
packages/shared/components/molecules/NftImageOrIconBox.svelte
packages/shared/components/molecules/NftMedia.svelte
packages/shared/components/popups/ActivityDetailsPopup.svelte

When receiving / minting NFTs, users might want to easily access the details view of the specific NFT without needing to traverse through the CollectiblesGallery and find the specific NFT. Adding a direct link to the DetailsView from the ActivityDetails component would make this much easier for the user.
```
- Add button to NftActivityDetails that is shown when nft is in selectedAccountNfts
- Fix placeholder borders showing behind loaded image
- Fix viewOnExplorer button taking up full parent width
```
> Please list any related issues using [development keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using …

enhancement: link to nft details from nft activity popup

---

packages/shared/components/popups/AuthenticationRequiredPopup.svelte
packages/shared/components/popups/Index.svelte
packages/shared/components/popups/NodeAuthRequiredPopup.svelte
packages/shared/components/popups/RegisterProposalPopup.svelte
packages/shared/locales/en.json

Opens the node authentication popup when the register proposal function error returns messages related to auth.
Extra: adds default value for node URL input
closes #5257 
- __Desktop__
- __Mobile__

feat: adds node authentication flow in voting

---

packages/desktop/views/dashboard/governance/views/DetailsView.svelte
packages/shared/components/organisms/ProposalCard.svelte
packages/shared/lib/contexts/governance/interfaces/index.ts
packages/shared/lib/contexts/governance/interfaces/proposal-state.interface.ts
packages/shared/lib/contexts/governance/stores/proposals-state.store.ts

Update proposals state so that it is per profile
```
- Update proposals sate interface
```
closes: #5452 
Add the following line of code to reset proposalsState: https://github.com/iotaledger/firefly/blob/fix/correct-proposal-state-store/packages/shared/lib/contexts/governance/stores/proposals-state.store.ts#L10
`proposalsState.set({})`
- __Desktop__
- __Mobile__
...

fix: correct proposal state store

---

packages/shared/components/popups/ManageVotingPowerPopup.svelte
packages/shared/components/popups/RegisterProposalPopup.svelte
packages/shared/lib/contexts/governance/interfaces/proposal-state.interface.ts
packages/shared/lib/core/error/handlers/handleError.ts
packages/shared/lib/core/error/handlers/handleGenericError.ts
packages/shared/locales/en.json

The register proposal popup needed to be slightly more robust.
```
- Add de-bouncing / spinner to action button in register proposal popup
- Improve error handling around registering a proposal
- Cleanup some import statements, mainly alphabetizing them
```
Closes #5480 
- __Desktop__
- __Mobile__
> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your …

fix: de-bounce buttons on Governance actions

---

packages/shared/components/inputs/AssetAmountInput.svelte

If clicked on the available balance, a non-grouped amount will be inserted into the input
```
- If clicked on the available balance, a non-grouped amount will be inserted into the input
```
Closes #5529 
- __Desktop__
- __Mobile__
...

fix: fix on available balance click

---

packages/mobile/views/dashboard/drawers/send/views/AmountView.svelte

Add fiat value to send amount
Please note that the design of the input itself needs to be improved because based on the size of the input value, the text is not centered, need to discuss with UX/UI
```
feat-mobile: add fiat value to send amount
```
Close https://github.com/iotaledger/firefly/issues/5103
- __Desktop__
- __Mobile__
> Please describe the specific instructions, configurations, and/or test cases necessary to …

feat-mobile: add fiat value to send amount

---

packages/shared/components/popups/NodeAuthRequiredPopup.svelte

We don't have to support username/password in node auth, so this needed to be removed
- __Desktop__
- __Mobile__

fix: removes username and password from NodeAuthRequiredPopup

---

packages/shared/components/popups/VoteForProposalPopup.svelte
packages/shared/locales/en.json

Removed because we don't need it
- __Desktop__
- __Mobile__

fix: remove text hint in VoteForProposalPopup

---

packages/shared/components/popups/VoteForProposalPopup.svelte
packages/shared/locales/en.json

If the user has no voting power, they are not warned or hinted that they need to increase it. 
```
- Add text hint back
- Remove unneeded locale
```
- __Desktop__
- __Mobile__
Try voting with no voting power and some voting power.

fix: add hint if no voting power

---

packages/desktop/electron/main.js

When we change something in a `.ts` file. webpack tries to refresh the browser, there `localhost` gets opened.
This PR includes a fix such that locahost doesnt get opened externally, but internally. Currently something on the walletrs side crashes, so a `ctrl`+`r` is necessary. 
If we're on a prod build, every localhost gets blocked immediatly to prevent errors
```
- block `localhost` on prod builds
- use default behavior for `localhost` in development
```
- __Desktop__
- __Mobile__
...

fix: open locahost in electron instead of external browser

---

docs/guides/developer-tips.md

Added section on where profile information is stored to handbook.
...
```
- Added information to handbook on where profiles are stored
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have added or modified tests that prove my changes …

feat: add location where profiles are stored to handbook

---

packages/desktop/views/dashboard/governance/views/DetailsView.svelte
packages/shared/locales/en.json

@MyMonk089 has opened a bug report about not being able to vote in the `Announcement` phase and then @Phyloiota commented that the UI should highlight that it is not possible to vote. So the design has changed and this PR implements it.
```
- Removes `Cancel` and `Vote` buttons in the  `Announcement` and `Closed` phases
- Adds TextHint in `Announcement` phase
```
closes #5628 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
-   [x] I have verified that new and …

enhancement: event phases disabled vote

---

packages/shared/components/atoms/boxes/CopyableBox.svelte

The Key-Value box is a specific `button` component, where we didnt set the `type` to `button`. This means, a click always dispatches the `submit` event to the parent form. 
```
- `type=button` to key value box
```
Clsoes #5620 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …

fix: remove submission if key value box is clicked

---

packages/shared/components/ProposalQuestion.svelte
packages/shared/lib/contexts/governance/interfaces/index.ts
packages/shared/lib/contexts/governance/interfaces/proposal-answer-percentages.interface.ts
packages/shared/lib/contexts/governance/utils/getPercentagesFromAnswerStatuses.ts
packages/shared/lib/contexts/governance/utils/tests/getPercentagesFromAnswerStatuses.test.ts

Percentages object should never be undefined otherwise it throws an error if the variable is undefined and the code is trying to access a property from it
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
-   [x] I have added or modified tests that prove my changes work as intended

fix: percentages undefined

---

packages/shared/lib/contexts/governance/utils/isAnyAccountVotingForSelectedProposal.ts

The error in the image is caused because by removing an account, it only updates the `activeAccounts` store, but not the `profile.metadata` (somehow even on loggout). Therefore, if an account had a proposal registered, and is then removed, the error `{type: "accountNotFound", text: "12"}` gets thrown
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I …

fix: fix details view if account with proposal gets deleted

---

docs/glossary.md
docs/guides/developer-tips.md
docs/specifications/governance.md
docs/standard-operating-procedures/development/documentation.md

Fix: typos

---

packages/shared/components/inputs/AssetAmountInput.svelte

The min and max under the slider input should be in the selected unit
```
- update value and unit of min/max under slider input
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have added …

enhancement: show correct unit on slider min max

---

packages/mobile/android/app/build.gradle
packages/mobile/ios/App/App.xcodeproj/project.pbxproj

This PR is also updating targetSdk to 31 as it is the new minimum on Google Play. As a result, Android Studio now requires that we avoid using the `minSdk` variable, we need to use the number in order to build.
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have commented my code, …

chore: bump mobile version

---

packages/shared/components/Button.svelte

The Button component is changing its size suddenly after changing states, it is happening because of the CSS performance, to solve this, the dynamic values were replaced by static by avoiding calc() functions with CSS variables.
```
- Simplify button sizing by replacing the dynamic calculations with variables for static values
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
-   [ ] I have commented on my code, particularly in hard-to-understand areas
-   [x] I have verified that new and existing unit tests pass locally with my …

fix: Button size changing suddenly after loading state

---

packages/desktop/views/dashboard/collectibles/views/CollectiblesGalleryView.svelte
packages/shared/components/atoms/buttons/ReceiveButton.svelte
packages/shared/components/popups/ReceiveAddressPopup.svelte

Based on a discussion on Discord, I changed the name of `Receive funds` to `Deposit NFTs` on the Deposit NFTs popup.
```
- Added title prop to Receive Address popup
- Changed title of Receive Address popup
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …

fix: correct name for deposit NFTs popup

---

packages/shared/components/popups/AliasConfirmationPopup.svelte
packages/shared/components/popups/ManageVotingPowerPopup.svelte
packages/shared/lib/contexts/governance/actions/setVotingPower.ts
packages/shared/lib/contexts/governance/actions/stopVotingForProposal.ts
packages/shared/lib/contexts/governance/actions/vote.ts
packages/shared/lib/core/wallet/actions/burnAsset.ts
packages/shared/lib/core/wallet/actions/burnNft.ts
packages/shared/lib/core/wallet/actions/consolidateOutputs.ts
packages/shared/lib/core/wallet/actions/mintNativeToken.ts
packages/shared/lib/core/wallet/actions/sendOutput.ts
packages/shared/lib/core/wallet/utils/processAndAddToActivities.ts

Fixes an issue where we logout while awaiting the sending of a transaction from wallet.rs. This resulted in an error, since we were fetching the`selectedAccount` from the store that had been cleared at that point in time.
...
```
- Remove redundant await
- Pass account parameter to proccessAndAddToActivities()
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …

fix: add selected account as a parameter in case store is cleared

---

packages/desktop/views/onboarding/views/profile-setup/views/SetupNewView.svelte

Correctly awaits initialization of the profile manager.
...
```
- Add async/await to initialiseProfileManager
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …

fix: await initialization correctly

---

packages/mobile/components/ActivityList.svelte
packages/mobile/components/AssetList.svelte
packages/mobile/components/filters/FilterItem.svelte
packages/mobile/views/dashboard/drawers/filter/FilterDrawer.svelte

This PR implements 2 changes:
- Polish spacing in token & activity tabs for search & filter
- Remove svelte transitions in filter drawer because there was something causing an odd jump in the activity amount filter
Close https://github.com/iotaledger/firefly/issues/5868
```
- feat-mobile: polish filter styles
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
...
- …

feat-mobile: polish filter styles

---

packages/shared/components/VotingPower.svelte
packages/shared/components/popups/ManageVotingPowerPopup.svelte
packages/shared/components/popups/RevotePopup.svelte
packages/shared/components/popups/VotingPowerToZeroPopup.svelte

Correctly disable the revote button and the confirm button on manage voting power popup
...
```
- use hasPendingGovernanceTransaction instead of isTransferring
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have added or modified tests that …

fix: correctly disable governance buttons

---

packages/shared/lib/core/stronghold/actions/checkOrUnlockStronghold.ts
yarn.lock

Enforce closing a popup before opening the unlockStrongholdPopup
...
```
- Update yarn.lock
- Add closePopup(true)
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I …

fix: manage voting power when stronghold locked

---

packages/desktop/components/filter/Filter.svelte

This PR updates the `Apply` button on the filter modal, such that it doesnt get active when i change an inactive filter
```
- update condition for activated apply button
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …

enhancement: improve apply filter button

---

packages/mobile/App.svelte

After #5889 the mobile app is not rendering and it is related to the import ordering, this PR fixes it
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS

fix: revert mobile App.svelte import order changes

---

packages/shared/lib/auxiliary/deep-link/errors/index.ts
packages/shared/lib/auxiliary/deep-link/errors/invalid-asset-id.error.ts
packages/shared/lib/auxiliary/deep-link/handlers/wallet/operations/handleDeepLinkSendConfirmationOperation.ts
packages/shared/lib/core/utils/crypto/utils/index.ts
packages/shared/lib/core/utils/crypto/utils/validateAssetId.ts
packages/shared/locales/en.json

Deeplink's assetId already has a validation that checks for the account assets being held, but it needs a validation of format and this PR implements this solution
```
- Creates validateAssetId function
- Adds validateAssetId function in handleDeepLinkSendConfirmationOperation
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
- Test deeplinks using developer tools:
`firefly-alpha://wallet/sendConfirmation?address=rms1qpwed3kpaju5rwe4nhplaj3ya6tujzvyuepypya4us95yf2rkp80u5ja230&amount=1&assetId=trololololo10`
`firefly-alpha://wallet/sendConfirmation?address=rms1qpwed3kpaju5rwe4nhplaj3ya6tujzvyuepypya4us95yf2rkp80u5ja230&amount=1&assetId=4218`
`firefly-alpha://wallet/sendConfirmation?address=rms1qpwed3kpaju5rwe4nhplaj3ya6tujzvyuepypya4u …

fix: validate asset id from deeplinks

---

packages/mobile/App.svelte
packages/shared/components/ToastContainer.svelte

```
- Adds showDismiss prop with default false value in ToastContainer
- Sets showDismiss prop to true inside mobile App's ToastContainer
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS

fix: only show dismiss button by default in mobile app

---

packages/shared/components/Toast.svelte
packages/shared/components/ToastContainer.svelte

...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …

fix: fix toasts

---

packages/desktop/views/dashboard/settings/views/security/AppLock.svelte
packages/mobile/components/drawers/profile/views/settings/views/AppLockView.svelte
packages/shared/components/Idle.svelte

adds default constant of lockScreenTimeoutInMinutes as a fallback to prevent #5770 from happening again
closes #5770 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
-   [ ] I have commented on my code, particularly in hard-to-understand areas

fix: adds default constant of lockScreenTimeoutInMinutes as fallback

---

packages/mobile/views/onboarding/views/profile-recovery/views/BackupPasswordView.svelte

We had an extra `style={$isKeyboardOpen && `margin-bottom: ${$keyboardHeight}px`}` so the available space was shrinked because we already do that calculation in `OnboardingLayout`. This PR removes it and also cleans a bit the file
Close https://github.com/iotaledger/firefly/issues/6451
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
> Please tick the following boxes that are relevant to your …

fix: not visible enter password input in import from stronghold flow

---

packages/desktop/electron/main.js

About Electron browserWindow didn't have a title bar on Windows so users could not exit it without using Alt + F4 or using the task bar. Added an option for users to exit out of the window.
```
- Added a titleBarOverlay to About Electron window on Windows OS
```
-   [x] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [x] I have followed the contribution guidelines for …

enhancement: add exit button to About Window for windowsOS

---

packages/mobile/components/drawers/DateTimePickerDrawer.svelte

closes #6583 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [x] iOS
- Go to activity list
- Touch the filter icon
- Toggle the "Date" filter
- Touch the date input
- The confirm button should be disabled
- Select a date by touching it
- The confirm button should be enabled
-   [x] I have made …

fix-mobile: disable confirm when no date selected in DateTimePickerDrawer

---

packages/mobile/components/drawers/DeleteAccountDrawer.svelte
packages/shared/lib/core/profile-manager/actions/deleteAccount.ts

These changes fix mobile account delete flow
Closes #6605 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [x] iOS
- Delete wallets
- Try to delete a wallet that is the only one in a profile

fix: wallet deletion

---

packages/mobile/components/drawers/send/SendRouter.svelte

closes #6572 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
- Try to send a native token, the storage deposit shouldn't be 0 in the SendRoute.Review
-   [ ] I have commented on my code, particularly in hard-to-understand areas
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting

fix-mobile: default native token storage deposit

---

packages/mobile/components/drawers/SelectedTokenDrawer.svelte

Burn button is appearing twice on native tokens and appearing for SMR tokens as well. This was the result of a merge mistake. PR #6382 code was initially correct. 
```
- Removed burn button outside of conditional
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [x] iOS
...
-   [ ] I have performed a …

mobile-fix: burn button appearing twice

---

packages/shared/components/inputs/ImportTextfield.svelte

When pasting the recovery phrase into the mnemonic recovery input field, carriage returns and newlines are replaced with an empty string. This causes an issue where the last word in a line and the first word of the following line are joined. Fixed this issue by replacing the lines with a space instead. 
```
- Replaced carriage returns and newlines with space instead of empty string
```
-   [x] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS …

fix: recovery phrase autoformat issue

---

packages/shared/components/inputs/NetworkInput.svelte

Allow dropdown  when selecting the network for normal profiles.
...
```
- Seat readonly attribute to false, to show the dropdown list
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
... …

fix: set readonly attribute to false

---

packages/mobile/components/drawers/send/SendRouter.svelte
packages/mobile/components/drawers/send/views/AmountView.svelte
packages/mobile/components/drawers/send/views/ReviewView.svelte
packages/mobile/views/dashboard/DashboardView.svelte
packages/shared/components/molecules/BasicActivityDetails.svelte
packages/shared/lib/core/wallet/utils/getOutputOptions.ts

closes #6574 
```
- Prevents send functions to go to the next route in sendRouter if the send drawer is closed
- Use transactionDetails in a local variable on AmountView.svelte to prevent errors from getting the global store newTransactionDetails
- Uses nullish coalescing operator where necessary to prevent errors when converting a string to a Number
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [x] iOS
- Login into a profile
- Unlock stronghold
- Go through the send flow until the final step
- In the final step click on "Send button" and then immediately close the drawer
- Try to quickly send again
-   [ ] I have …

mobile-fix: undefined send transaction

---

packages/shared/tsconfig.json

A last second change to use `include` instead of `files` in the `packages/shared/tsconfig.json` file is causing issues in type checking outside of the included files. Switching it back to files fixes the issue.
```
- Switch from include to files and reestablish list of correct files
```
-   [x] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [x] I have followed the …

hotfix: tsconfig not error checking

---

.github/workflows/build-desktop.yml
manual-patches/windows_cargo_toml.patch
packages/backend/bindings/node/native/Cargo.toml

- Use Rust toolchain 1.67.0
- Use `windows-latest` and Visual Studio 2022
- Only install Python 2.x on macOS
- Install `node-gyp` 9.3.1
- Patch neon-sys (make https://github.com/neon-bindings/neon/pull/785 work for our version of Electron) and node-gyp (https://github.com/nodejs/node-gyp/issues/2673#issuecomment-1239619438)
N/A
-   [x] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
App should launch and run properly
Builds are available [here](https://github.com/iotaledger/firefly/actions/runs/4999181058)
-   [x] I have commented my code, particularly …

ci: Fix Windows build

---

packages/desktop/views/dashboard/send-flow/views/TransactionSummaryView.svelte

When the transaction summary is accessed, the `selectedTimelockperiod` needs to be initialized if the timelock was set. With this, the item in the details will be displayed
```
- initialize `selectedTimelockperiod`
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …

fix: timelock not shown on tx summary

---

packages/desktop/components/popups/TokenInformationPopup.svelte

Display the Asset tile in Token Information Popup to match the Assets List
closes #6940 
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS

enhancement: show asset tile in token information popup

---

packages/desktop/components/popups/NodeInfoPopup.svelte

Closes #6899 
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have verified that my …

fix: improve readability of node info metrics value

---

packages/shared/lib/contexts/governance/constants/default-proposal-filter.constant.ts

Closes #7276 
> Fix literals in phase filter texts in the Governance view
```
- Modify locale text
```
-   [ ] MacOS
-   [X] Linux
-   **Mobile**
-   [ ] iOS
- Go to the governance screen
- Click on the filters and apply `phase`
- Check that the text of the options is correct
-   [x] I have verified that my latest …

fix: phase filter locale in the Governance view

---

packages/desktop/views/onboarding/views/create-profile/views/ChooseCreateProfileFlowView.svelte
packages/shared/lib/contexts/onboarding/helpers/buildInitialOnboardingProfile.ts
packages/shared/lib/core/profile/actions/active-profile/saveActiveProfile.ts
packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
packages/shared/lib/core/profile/constants/profile-version.constant.ts
packages/shared/lib/core/profile/interfaces/persisted-profile.interface.ts

Closes #7291 
> dont store stronghold version on ledger profiles
```
- Remove strongholdVersion in Ledger profiles
- Dont store stronghold version when creating ledger profiles
```
-   [ ] MacOS
-   [X] Linux
-   **Mobile**
-   [ ] iOS
- Check in the `localStorage` that the `strongholdVersion` of the Ledger profiles no longer appears
- Create a new ledger profile and check that `strongholdVersion` is not stored
-   [ ] I have verified that new and existing unit tests …

fix: dont store stronghold version on ledger profiles

---

.github/workflows/build-desktop.yml
packages/backend/Cargo.lock
packages/backend/Cargo.toml
packages/backend/bindings/node/index.ts
packages/backend/bindings/node/native/Cargo.lock
packages/backend/bindings/node/native/Cargo.toml
packages/backend/bindings/node/native/src/lib.rs
packages/desktop/package.json
packages/shared/lib/stronghold.ts
packages/shared/routes/login/views/EnterPin.svelte
patches/dmg-builder+22.9.1.patch

...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …

release: desktop 1.7.3

---

packages/desktop/electron/main.js

Closes #7306
> Fix error screen randomly after coming back to machine
```
- Add optional chaining to prevent app from crashing when suspended
```
-   [ ] MacOS
-   [X] Linux
-   **Mobile**
-   [ ] iOS
> Login to a profile and `suspend` the machine
-   [ ] I have made corresponding changes to the …

fix: cannot read properties of null (reading `webContents`) using `powerMonitor` on macOS

---

packages/desktop/components/popups/send/SendConfirmationPopup.svelte

> Adds a check so that the `preparedOutput` won't be recomputed after "Stronghold unlocking" step and `sendOutputAndClosePopup` callback execution.
Previously we had the case where, after ` checkActiveProfileAuth` (stronghold unlock step), the `SendConfirmationPopup` component would be re-mounted, also recomputing `preparedOutput` before executing the callback, causing the wallet to throw an error on this subsequent `prepareOutput()` because the output was already "locked" in the previous execution.
Closes https://github.com/iotaledger/firefly/issues/7373
```
- Fixed a misleading insufficient funds error (visible only in dev mode) cause by trying to lock the same output(s) twice 
```
-   [x] MacOS
-   [ ] …

fix: misleading insufficient funds on send

---

packages/desktop/components/popups/send/SendConfirmationPopup.svelte
packages/shared/lib/core/wallet/utils/send/validateSendConfirmation.ts

- Simplified `validateSendConfirmation`  by removing available balance check because that validation is already done in the previous step in `SendFormPopup`
- add try catch to `prepareOutput` in SendConfirmationPopup
resolves #7396 
-   [ ] MacOS
-   [x] Linux
-   [ ] I have made corresponding changes to the …

Fix: Simplify validateSendConfirmation

---

packages/shared/package.json
yarn.lock

Closes #7432 
> bump SDK version
```
- Bump latest SDK version
```
-   [ ] MacOS
-   [X] Linux

chore: bump @iota/sdk to 1.0.11

---

packages/shared/lib/core/wallet/utils/generateActivity/generateActivitiesFromBasicOutputs.ts
packages/shared/lib/core/wallet/utils/outputs/preprocessOutgoingTransaction.ts
packages/shared/lib/core/wallet/utils/transactions/getNonRemainderBasicOutputsFromTransaction.ts

- Refactor `getBurnedNativeTokens` logic for identifying burned native tokens.
- Update logic to determine `remainder` in `convertTransactionOutputTypeToWrappedOutput`
- Update logic `getNonRemainderBasicOutputsFromTransaction` to use `remainder` property
resolves #7107 
-   [ ] MacOS
-   [x] Linux
-   [x] I have verified that my latest …

Fix: Enhanced logic for identifying burned native tokens.

---

packages/shared/lib/core/network/constants/default-chain-configurations.constant.ts
packages/shared/lib/core/network/enums/chain-id.enum.ts
packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
packages/shared/lib/core/profile/constants/profile-version.constant.ts

Close https://github.com/iotaledger/firefly/issues/7621
```
```
-   [ ] MacOS
-   [ ] Linux
... …

feat: add support for new shimmer evm testnet

---

packages/desktop/components/popups/send/SendNftForm.svelte
packages/desktop/components/popups/send/SendTokenForm.svelte
packages/shared/lib/core/layer-2/interfaces/index.ts
packages/shared/lib/core/layer-2/interfaces/layer2-gas-estimate-payload.interface.ts
packages/shared/lib/core/layer-2/utils/getEstimatedGasForTransferFromTransactionDetails.ts
packages/shared/lib/core/wallet/utils/getOutputParameters.ts
packages/shared/locales/en.json

Close https://github.com/iotaledger/firefly/issues/7693

fix: do not allow sending if failed to request `estimategas-onledger`

---

packages/desktop/components/WalletSwitcher.svelte
packages/desktop/components/index.js
packages/desktop/components/popups/Popup.svelte
packages/desktop/views/dashboard/TopNavigation.svelte
packages/shared/lib/auxiliary/deep-link/handlers/handleDeepLink.ts
packages/shared/lib/auxiliary/popup/enums/popup-id.enum.ts

Depends on https://github.com/iotaledger/firefly/pull/7796
Closes https://github.com/iotaledger/firefly/issues/7792

refactor: Hide wallet switcher

---

packages/shared/lib/core/wallet/utils/getDefaultTransactionOptions.ts

Closes #8041 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …

feat: update getDefaultTransactionOptions interface

---

packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/FundConfirmationView.svelte
packages/shared/lib/core/wallet/actions/events-handlers/handleNewOutputEvent.ts
packages/shared/locales/en.json

Closes #7979 
TODO comment added in #8055
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …

feat: display hint with ed25519 address when low mana generation in implicit account creation

---

packages/desktop/views/dashboard/account-management/AccountManagement.svelte
packages/shared/locales/en.json

Closes #8205 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …

fix: crash accounts if not selected output

---

packages/desktop/components/popups/BalanceBreakdownPopup.svelte
packages/shared/locales/en.json

Close https://github.com/iotaledger/firefly/issues/7964
Close https://github.com/iotaledger/firefly/issues/8125
```
```
-   [ ] MacOS
-   [ ] Linux
...
-   [ ] I …

feat: add mana rewards and base token locked funds to balance breakdown

---

packages/desktop/components/AccountManagementDetails.svelte
packages/desktop/components/popups/ActivityDetailsPopup.svelte
packages/desktop/components/popups/MintNativeTokenConfirmationPopup.svelte
packages/desktop/components/popups/MintNftConfirmationPopup.svelte
packages/desktop/components/popups/send/SendConfirmationPopup.svelte
packages/desktop/views/dashboard/Dashboard.svelte
packages/shared/components/tiles/tileFooters/AsyncActivityTileFooter.svelte
packages/shared/lib/core/wallet/utils/hasWalletMainAccountNegativeBIC.ts
packages/shared/lib/core/wallet/utils/index.ts

Closes #8267
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …

feat: block and display negative BIC error when main account has negative BIC

---

packages/shared/lib/core/network/constants/explorer-urls.constant.ts
packages/shared/lib/core/network/constants/faucet-urls.constant.ts
packages/shared/lib/core/network/constants/official-node-urls.constant.ts
packages/shared/lib/core/network/tests/network.test.ts
packages/shared/lib/core/network/utils/getNetworkIdFromNetworkName.ts

Closes https://github.com/iotaledger/firefly/issues/7868

chore: update node and faucet urls for nova testnet

---

.github/workflows/build-and-release-desktop.yml
.github/workflows/build-desktop.yml
README.md
packages/desktop/package.json
packages/desktop/product.js
packages/shared/lib/core/network/constants/explorer-urls.constant.ts
packages/shared/lib/core/network/constants/faucet-urls.constant.ts
packages/shared/lib/core/network/constants/official-node-urls.constant.ts
packages/shared/lib/core/network/tests/network.test.ts
packages/shared/lib/core/network/utils/getNetworkIdFromNetworkName.ts

...
```
```
-   [ ] MacOS
-   [ ] Linux
... …

release: desktop canary 3.0.0

---

packages/desktop/components/ManaBox.svelte
packages/desktop/components/popups/AllotManaPopup.svelte
packages/shared/locales/en.json

> Closes #8526 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …

Fix: add error when cannot allotment

---

packages/desktop/components/ManaBox.svelte
packages/desktop/components/popups/ActivityDetailsPopup.svelte
packages/desktop/components/popups/AllotManaPopup.svelte
packages/desktop/components/popups/BurnNativeTokensConfirmationPopup.svelte
packages/desktop/components/popups/BurnNftPopup.svelte
packages/desktop/components/popups/ClaimDelegationRewardsPopup.svelte
packages/desktop/components/popups/ConsolidateOutputsPopup.svelte
packages/desktop/components/popups/CreateDelegationPopup.svelte
packages/desktop/components/popups/MintNativeTokenConfirmationPopup.svelte
packages/desktop/components/popups/MintNftConfirmationPopup.svelte
packages/desktop/components/popups/send/SendConfirmationPopup.svelte
packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/AccountCreationView.svelte
packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/FundConfirmationView.svelte
packages/desktop/views/onboarding/views/restore-profile/views/ClaimFinderView.svelte

Closes #8505 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …

fix: reactivity issue after user gets enough mana to cover the block cost

---

packages/desktop/features/onboarding.features.ts
packages/desktop/views/onboarding/views/network-setup/views/ChooseNetworkView.svelte
packages/shared/locales/en.json

> Closes #8532 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …

feat: update onboarding network selection buttons

---

packages/desktop/components/popups/AllotManaPopup.svelte

Closes #8524 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …

fix: custom mana allotment should send to itself

---

packages/desktop/components/modals/AccountActionsMenu.svelte
packages/desktop/package.json
packages/shared/lib/core/layer-2/enums/destination-network.enum.ts
packages/shared/lib/core/network/constants/default-chain-configurations.constant.ts
packages/shared/lib/core/network/enums/chain-id.enum.ts
packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
packages/shared/lib/core/profile/constants/profile-version.constant.ts

...
```
```
-   [ ] MacOS
-   [ ] Linux
... …

release: desktop iota 2.0.11

---

packages/desktop/App.svelte
packages/desktop/components/popups/AppDeprecationPopup.svelte
packages/desktop/components/popups/Popup.svelte
packages/desktop/components/popups/SwitchToWalletExtensionPopup.svelte
packages/desktop/views/dashboard/Dashboard.svelte
packages/shared/lib/auxiliary/popup/enums/popup-id.enum.ts
packages/shared/lib/core/app/constants/external-allowed-links.constant.ts

fixes https://github.com/iotaledger/firefly/issues/8663
...
```
```
-   [ ] MacOS
-   [ ] Linux
...
-   [ ] I have verified that new and existing unit tests pass locally with …

feat: add deprecation disclaimer and popup

---

.github/workflows/build-and-release-desktop.yml
packages/desktop/package.json

...
```
```
-   [ ] MacOS
-   [ ] Linux
... …

Fix: windows build
