iotaledger/firefly

packages/shared/components/popups/DeleteProfile.svelte, packages/shared/locales/en.json
When deleting a profile the prompt to delete now includes a password request.
Fixes https://github.com/iotaledger/firefly/issues/775
=> fix: Delete profile requests wallet password

packages/backend/Cargo.lock, packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock, packages/backend/src/actors.rs, packages/backend/src/lib.rs
Removed ManagerStorage from backend
=> fix: atomic balance updates, remove metaData mqtt event and watch all change addresses

packages/shared/lib/wallet.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/settings/views/Advanced.svelte
Adds the missing resyncAccounts description.
Adds a confirmation notification when the syncAccounts is triggered from settings.
Fixes https://github.com/iotaledger/firefly/issues/629
=> fix: Add the missing resyncAccounts description and a confirmation notification

packages/shared/lib/chart.ts, packages/shared/lib/profile.ts, packages/shared/routes/dashboard/wallet/views/LineChart.svelte
Persist chart selected currency and timeframe
Fixes issue #713
Electron Linux
=> feat: persist chart selectors

packages/shared/routes/dashboard/wallet/views/LineChart.svelte
Remove old duplicated logic caused after merge
N/A
Linux Electron
=> fix: remove old duplicated logic caused after merge

packages/desktop/App.svelte, packages/shared/lib/marketData.ts
Regularly check for updates to the market data instead of just on app startup.
Fixes https://github.com/iotaledger/firefly/issues/680
=> fix: Poll the market data in the background

packages/desktop/App.svelte, packages/shared/components/modals/AccountActions.svelte, packages/shared/components/popups/AddressHistory.svelte, packages/shared/locales/en.json
Add account address history.
_Note: date is dummy._ 
N/A
Electron Linux
=> Feat: add address history

packages/backend/bindings/node/native/Cargo.lock
Updates to the latest wallet.rs which includes various breaking changes and fixed including:
- Move to RocksDB
- Move messages out of account object 
- Ensures balance updates across accounts are atomic
- Fixes a crash on Stronghold lock
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
Tested on Mac
=> fix: replace sqlite with rocksdb, schema changes and other fixes

packages/desktop/electron/lib/notificationManager.js, packages/desktop/electron/main.js, packages/shared/lib/electron.ts, packages/shared/lib/notifications.ts, packages/shared/lib/wallet.ts, packages/shared/routes/dashboard/Dashboard.svelte
When a system notification is clicked it attempt to open the app at the relevant account page.
=> feat: Activate the application when notifications are clicked

.github/workflows/build-desktop.yml, packages/backend/bindings/node/native/.cargo/config.toml
- Force static linking to Windows C Runtime
- Install LLVM and Clang on Windows CI
N/A
N/A
=> fix: Fix Windows build issues

packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock
Updates wallet.rs to include fixes:
- Adds primary node support
- Syncs full address space on first poll after Stronghold unlock
Tested on Max
=> fix: add primary node functionality and cross-device syncing fix

packages/shared/components/inputs/Input.svelte, packages/shared/components/popups/AddNode.svelte, packages/shared/components/popups/RemoveNode.svelte, packages/shared/lib/actions.ts, packages/shared/lib/helpers.ts, packages/shared/lib/network.ts, packages/shared/lib/profile.ts, packages/shared/lib/typings/client.ts, packages/shared/lib/wallet.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/settings/views/Advanced.svelte, packages/shared/routes/dashboard/wallet/Wallet.svelte, packages/shared/routes/setup/protect/Protect.svelte
Adds a more fully featured custom node settings module.
Enabled the PoW setting.
Fixes https://github.com/iotaledger/firefly/issues/541
=> feat: New configurable node settings

packages/backend/bindings/node/native/Cargo.lock
Messages were not included in stronghold export or import.
Tested on Mac
=> fix: ensure messages are exported to and imported from strongholds

packages/desktop/electron/preload.js, packages/shared/components/popups/DeleteProfile.svelte, packages/shared/lib/profile.ts, packages/shared/lib/wallet.ts, packages/shared/routes/setup/Setup.svelte
Due to the order in which the steps were performed during a profile delete the actor and other components were not successfully cleaned up, leading to exceptions when trying to create new profiles.
Fixes https://github.com/iotaledger/firefly/issues/833 https://github.com/iotaledger/firefly/issues/834
=> fix: Deleting a profile did not release the actor

packages/backend/bindings/node/native/Cargo.lock
- Ensures the correct pow field is used for node queries
Tested on Mac
=> fix: node response PoW field

packages/backend/bindings/node/native/Cargo.lock
- Fixes an issue with timestamp deltas from milestone
=> fix: ensures timestamps are correctly set from milestone

packages/shared/lib/marketData.ts
When the market data endpoint is down currency conversion displays NaN. The currency formatting PR partially resolves this by not displaying conversions if it can't perform them.
This PR keeps a cache of the last valid response from the market data endpoint and load this on startup to make sure we have at least some data.
Fixes https://github.com/iotaledger/firefly/issues/909
Test on windows with no connection
=> fix: Market data not available causes NaN values

packages/desktop/electron/main.js, packages/shared/lib/typings/routes.ts, packages/shared/routes/dashboard/Dashboard.svelte, packages/shared/routes/dashboard/settings/views/Advanced.svelte
Disable deep links in electron and settings until full implemented.
=> fix: Disable deep links

packages/backend/bindings/node/native/Cargo.lock
=> fix: Cargo.lock

packages/shared/routes/dashboard/wallet/views/WalletHistory.svelte
https://github.com/iotaledger/firefly/issues/924
N/A
=> feat: do not show error notification of history refresh

packages/backend/bindings/node/native/Cargo.lock
Updates to latest Stronghold
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> chore: update wallet.rs

packages/desktop/electron/main.js, packages/shared/components/popups/Version.svelte, packages/shared/locales/en.json
Disable windows auto update with message until the cert vulnerability is fixed.
Update button opens web site.
Tested on windows with auto updater
=> feat: Disable windows auto update

packages/shared/routes/setup/backup/Backup.svelte
Re-enable the mnemonic verification page in onboarding workflow.
=> feat: Enable mnemonic verification

packages/shared/components/ActivityDetail.svelte
Improve the formatting of the amounts in activity detail
=> fix: Activity details amount formatting

packages/shared/routes/setup/Legal.svelte
Update legal text requested by the legal department
N/A
N/A
=> feat: update legal text

packages/shared/components/ActivityDetail.svelte, packages/shared/locales/en.json, packages/shared/routes/dashboard/wallet/views/WalletActions.svelte, packages/shared/routes/login/views/SelectProfile.svelte, packages/shared/routes/setup/Legal.svelte
- Fix account tile right alignment
- Fix select profile alignment 
N/A
Ubuntu 18.04. 
=> Feat: minor css fixes

packages/desktop/electron/lib/menu.js, packages/desktop/electron/main.js, packages/shared/components/popups/MissingBundle.svelte, packages/shared/lib/typings/routes.ts, packages/shared/routes/dashboard/settings/views/Help.svelte, packages/shared/routes/setup/Setup.svelte, packages/shared/routes/setup/migrate/views/BundleMiningWarning.svelte, packages/shared/routes/setup/migrate/views/SecuringSpentAddresses.svelte
Add the missing help links to onboarding, Settings->About and native menu.
=> feat: Add missing help links

packages/shared/routes/setup/Legal.svelte
Remove phone from legal text
N/A
N/A
=> Fix: remove phone from legal text

packages/shared/lib/migration.ts, packages/shared/routes/Splash.svelte, packages/shared/routes/dashboard/Dashboard.svelte, packages/shared/routes/dashboard/wallet/Wallet.svelte, packages/shared/routes/login/Login.svelte, packages/shared/routes/login/views/EnterPin.svelte
Adjusts polling logic for snapshot check
Tested on Mac
=> fix: snapshot check logic

packages/desktop/electron/lib/keychain.js
=> chore: Update keychain name

.github/workflows/build-desktop.yml, packages/desktop/package.json, packages/desktop/scripts/notarize.macos.js
Change the app version to 1.0.0
=> chore: Update version

packages/desktop/electron/lib/menu.js, packages/desktop/electron/main.js
Disable devtools in packaged version
Tested on windows with full electron packaged build
=> chore: Disable devtools in packaged version

packages/backend/bindings/node/native/Cargo.lock
Fixes createAccount in wallet.rs by hardcoding correct hrp
=> chore: fix hrp

packages/shared/routes/setup/migrate/views/Migrate.svelte
Fixes missing link
Tested on Mac
=> fix: missing link

packages/shared/locales/en.json
The descriptions in settings were inconsistent with their use of full stops at the end of their descriptions. See linked issue for screen shot
Fixes https://github.com/iotaledger/firefly/issues/987
=> fix: Settings descriptions are not consistent with dots at end

.github/workflows/build-desktop.yml
Add AppImage signing
N/A
Built version on CI and verified signature
=> feature(ci): Add AppImage signing

.github/workflows/build-desktop.yml
Adds a link to the verification instructions in the changelog template
N/A
N/A
=> feature(ci): Add link to verification instructions in changelog template

.github/workflows/build-desktop.yml, packages/backend/bindings/node/native/.cargo/config.toml
Sets minimum macOS version to 10.12. #907 did not resolve the issue
Fixes #897 
Before:
```
nm /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node | grep chkstk   
U ____chkstk_darwin
```
After:
```
nm /Volumes/Firefly/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node | grep chkstk
<nothing>
```
=> fix(ci): Set minimum macOS version to 10.12

packages/desktop/electron/main.js, packages/desktop/electron/preload.js, packages/desktop/main.js, packages/desktop/public/error.html
Don't report unhandled promise rejections in render context.
Improve display of error message.
Improve OSX detection
=> fix: Improve exception handling

packages/desktop/package.json
Reverts iotaledger/firefly#1044
=> Revert "chore(desktop): Bump version to 1.1.1"

packages/desktop/electron/preload.js, packages/desktop/main.js, packages/desktop/public/error.html
Improve the exception message display.
=> fix: Improve exception formatting

.github/workflows/build-desktop.yml
Please write a summary of your changes and why you made them. 
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix
=> chore(ci): Upload DMGs to S3

packages/desktop/package.json, packages/desktop/webpack.config.js, patches/node-hid+2.1.1.patch, patches/usb+1.7.1.patch
Because of issues with the `bindings` package, we need to hardcode the paths to the bindings
N/A
Tested on macOS in dev and prod
=> fix(desktop): Fix issues loading HID and USB bindings

packages/shared/components/popups/LedgerConfirmation.svelte, packages/shared/components/popups/LedgerNotConnected.svelte, packages/shared/lib/ledger.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/wallet/Wallet.svelte, packages/shared/routes/dashboard/wallet/views/Security.svelte, packages/shared/routes/setup/ledger/views/AccountIndex.svelte, packages/shared/routes/setup/ledger/views/Balance.svelte, packages/shared/routes/setup/ledger/views/Create.svelte, packages/shared/routes/setup/ledger/views/FireflyImport.svelte, packages/shared/routes/setup/ledger/views/GenerateNewAddress.svelte, packages/shared/routes/setup/ledger/views/InstallLedgerApp.svelte
Changes Ledger connection polling logic:
- Only polls after detecting a disconnect
Still testing
=> fix: Ledger disconnect polling

packages/shared/components/popups/Index.svelte, packages/shared/components/popups/LedgerAppGuide.svelte, packages/shared/lib/ledger.ts, packages/shared/locales/en.json, packages/shared/routes/setup/ledger/Ledger.svelte, packages/shared/routes/setup/ledger/views/InstallationGuide.svelte
Adds a new onboarding page to the Ledger migration flow. The page contains a popup guide with steps for properly configuring the Ledger devices for migration.
None
Tested on:
=> feat: Ledger migration popup guide

packages/shared/lib/router.ts
Reduce gapLimit for ledger accounts because the address generation is much slower
Recovered an account
=> Reduce gapLimit for ledger accounts

.github/pull_request_template.md
Adds new change types to the PR template to help increase clarity and consistency.
None
- Documentation fix
N/a
=> fix: PR change types

packages/shared/lib/shell/walletErrors.ts, packages/shared/locales/en.json
Provides a more descriptive error message for when the user is asked to confirm the transaction on his or her device but chooses to reject it.
None
Tested on (real Ledger Nano S):
=> fix: Ledger transaction error

packages/shared/lib/ledger.ts, packages/shared/routes/dashboard/wallet/views/Send.svelte
Ensures that the Ledger device is connected before it needs to sign the transaction
None
=> feat: Ledger connection on send

packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock, packages/shared/lib/migration.ts, packages/shared/routes/setup/ledger/views/GenerateNewAddress.svelte, packages/shared/routes/setup/migrate/views/Migrate.svelte
The user is prompted to "Ok" the newly generated migration addresses on the Ledger device.
None
Tested on:
=> feat: Ledger migration address confirmation

packages/desktop/electron/lib/Ledger.js
=> feat: add account index offset

packages/shared/routes/setup/Balance.svelte
Move variable to the top of the file to avoid access before initialization
N/A
=> Fix: Balance view variable access

packages/shared/lib/migration.ts
Updates migration nodes to Ledger testnet
Tested on Mac
=> chore(temp): add ledger migration node

packages/backend/Cargo.lock, packages/backend/Cargo.toml, packages/backend/bindings/node/index.ts, packages/backend/bindings/node/native/Cargo.lock, packages/backend/src/lib.rs, packages/shared/components/popups/Index.svelte, packages/shared/components/popups/LedgerAddress.svelte, packages/shared/components/popups/LedgerTransaction.svelte, packages/shared/lib/notifications.ts, packages/shared/lib/profile.ts, packages/shared/lib/shell/walletApi.ts, packages/shared/lib/typings/bridge.ts, packages/shared/lib/typings/events.ts, packages/shared/lib/validator.ts, packages/shared/lib/wallet.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/wallet/Wallet.svelte, packages/shared/routes/dashboard/wallet/views/Account.svelte, packages/shared/routes/dashboard/wallet/views/AccountActions.svelte, packages/shared/routes/dashboard/wallet/views/Receive.svelte, packages/shared/routes/dashboard/wallet/views/Send.svelte
Adds a prompt to ensure user always validates receive address against the one displayed on the Ledger device
Tested on Mac
=> feat: add receive address prompt for Ledger 

packages/backend/Cargo.lock, packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock
This PR updates firefly backend.
N/A
N/A
=> chore: point backend to latest wallet-rs

packages/backend/README.md
Add instructions how to update wallet.rs in the backend
- Docs (changes to the documentation)
=> Add instructions how to update wallet.rs in the backend

packages/shared/components/popups/LedgerAddress.svelte, packages/shared/lib/wallet.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/wallet/Wallet.svelte, yarn.lock
Added more error handling in generating an address for Ledger devices.
#1266 
=> fix: Ledger null addresses

packages/desktop/electron/lib/Ledger.js
This PR removes some unnecessary code added [previously](https://github.com/iotaledger/firefly/pull/1251) related to ledger simulator setup. 
N/A
- Refactoring
=> refactor: remove unnecessary code related to ledger simulator

packages/backend/Cargo.lock, packages/backend/Cargo.toml, packages/backend/bindings/node/index.ts, packages/backend/bindings/node/native/Cargo.lock, packages/backend/src/actors.rs, packages/backend/src/lib.rs, packages/shared/lib/shell/walletApi.ts, packages/shared/lib/typings/account.ts, packages/shared/lib/typings/bridge.ts, packages/shared/lib/validator.ts, packages/shared/lib/wallet.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/Dashboard.svelte
Disables automatic polling on account initialisation and instead triggers polling from the dashboard
Tested on Mac and observed Rust side logging
=> feat: manually trigger polling from dashboard

.github/workflows/build-desktop.yml
This is much easier to type than `4a1dd...`
N/A
- Chore
N/A
=> chore(ci): Upload releases to firefly bucket prefix

packages/shared/lib/router.ts, packages/shared/lib/wallet.ts, packages/shared/routes/dashboard/wallet/Wallet.svelte
This PR de-duplicates some code containing logic for gathering account sync information.
None
=> chore: Sync account logic

packages/shared/components/popups/LedgerLegacyTransaction.svelte, packages/shared/lib/ledger.ts, packages/shared/lib/migration.ts
- Remove checksum from end of ledger output
- Fix imports
- Unify `removeAddressChecksum`
N/A
Ubuntu 18.04. Real Ledger Nano S
=> Feat: Remove checksum from end of ledger output

packages/shared/routes/setup/ledger/views/LegacyIntro.svelte
Adds an external link to the Ledger intro migration page.
#1263
=> chore: Ledger migration link

packages/shared/components/popups/LedgerAppGuide.svelte, packages/shared/components/popups/LedgerLegacyTransaction.svelte, packages/shared/components/popups/LedgerNotConnected.svelte, packages/shared/locales/en.json, packages/shared/routes/dashboard/wallet/views/Security.svelte, packages/shared/routes/setup/Congratulations.svelte, packages/shared/routes/setup/ledger/views/InstallationGuide.svelte, packages/shared/routes/setup/ledger/views/SwitchApps.svelte
- Remove from translation files legacy transaction strings that are not translated by Ledger as we are trying to match exactly what Ledger displays. 
- Make "IOTA Legacy" a constant string 
N/A
Ubuntu 18.04. Real Ledger Nano S
=> Fix: Hardcode non-translatable ledger strings

packages/shared/components/popups/LedgerAppGuide.svelte, packages/shared/components/popups/LedgerConnectionGuide.svelte, packages/shared/locales/en.json, packages/shared/routes/setup/Congratulations.svelte
- Transform ledger guide locales from array to numbered json because of the `values` we need to pass, wasnt working with the array
- Fix congratulations crash
N/A
Ubuntu 18.04. Ledger Nano S
=> Fix: ledger locales

packages/shared/locales/en.json
Changed "you" to "the"
[https://crowdin.com/translate/iota-firefly/32/en-de#5431](https://crowdin.com/translate/iota-firefly/32/en-de#5431)
=> Fixed typo

packages/shared/components/popups/BalanceFinder.svelte, packages/shared/components/popups/LedgerLegacyTransaction.svelte, packages/shared/lib/ledger.ts, packages/shared/lib/typings/ledger.ts, packages/shared/lib/wallet.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/wallet/Wallet.svelte, packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte, packages/shared/routes/dashboard/wallet/views/CreateAccount.svelte, packages/shared/routes/dashboard/wallet/views/Send.svelte, packages/shared/routes/setup/Balance.svelte, packages/shared/routes/setup/ledger/views/AccountIndex.svelte, packages/shared/routes/setup/ledger/views/Connect.svelte, packages/shared/routes/setup/ledger/views/GenerateNewAddress.svelte, packages/shared/routes/setup/ledger/views/RestoreFromLedger.svelte, packages/shared/routes/setup/ledger/views/SwitchApps.svelte, packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
Handles more cases of Ledger device state errors.
None
=> fix: Ledger state errors

packages/shared/lib/network.ts
This PR updates the default network node.
N/A
N/A
=> chore: update node

packages/shared/components/Link.svelte, packages/shared/routes/setup/ledger/views/Connect.svelte, packages/shared/routes/setup/ledger/views/InstallationGuide.svelte, packages/shared/routes/setup/ledger/views/LegacyIntro.svelte
- Add `icon` prop to `Link.svelte` component
- Add info icon to "Read migration FAQs"
N/A
Ubuntu 18.04. Ledger Nano S. 
Ledger migration flow
=> Feat: Icon link

packages/backend/Cargo.lock, packages/backend/bindings/node/native/Cargo.lock, packages/shared/lib/network.ts
This PR updates the backend to latest (some fixes were pushed to `firefly-testing` branch of wallet rs).
N/A
=> chore: update backend

packages/shared/lib/router.ts, packages/shared/routes/setup/Congratulations.svelte, packages/shared/routes/setup/ledger/Ledger.svelte
Reinitialize ledger routing only when we are not in the middle of a ledger flow
N/A
=> Fix: reinit ledger route only on fresh onboardings

packages/shared/components/popups/LedgerAppGuide.svelte, packages/shared/components/popups/LedgerConnectionGuide.svelte, packages/shared/locales/en.json
- Fix ledger guides steps length not working on the continue button UI logic
- Remove unused locales
N/A
Ubuntu 18.04
=> Fix: ledger guides locales

packages/shared/components/popups/LedgerMigrateIndex.svelte, packages/shared/routes/dashboard/Dashboard.svelte
This adds a fix that prevents the automatic closing of a migration popup in the wallet dashboard.
_NOTE: This PR depends on the `feat/ledger-next` branch._
#1306
=> fix: Automatic popup closes

packages/shared/routes/dashboard/wallet/Wallet.svelte
Removes the error occurring on load for Ledger users if his or her device is not in the `Connected` state.
None
=> fix: Ledger error on load

packages/shared/lib/migration.ts, packages/shared/routes/setup/Balance.svelte, packages/shared/routes/setup/import/views/FileImport.svelte
- Remove `legacyAddressForTesting`
- Cleanup one leftover unused variable
N/A
Ubuntu 18.04
=> Feat: Remove `legacyAddressForTesting`

packages/shared/routes/dashboard/Dashboard.svelte, packages/shared/routes/dashboard/wallet/views/Security.svelte, packages/shared/routes/dashboard/wallet/views/WalletActions.svelte, packages/shared/routes/dashboard/wallet/views/WalletBalance.svelte
This PR implements:
- Remove waiting for funds dashboard lock
- Fix waiting for funds notification appearing multiple times
- Replace missing usage of isLedgerProfile
N/A
Ubuntu 18.04. Ledger simulators
=> Feat: Remove waiting for funds dashboard lock

packages/shared/locales/en.json, packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
This PR adds a fix for the migration spinning forever. The fix somewhat relies on the tooltip in #1317 b/c only if the user reconnects the device will the spinning stop.
None
=> fix: Ledger migration connection

packages/shared/lib/migration.ts
- Mined index bundle checksum was calculated from a shortened address incorrectly
Tested both mined and unmined checksum calculation
=> hotfix: ensure correct mined bundle checksum

packages/shared/locales/en.json
Sync strings from `feat/ledger` so they are synced on Crowdin
N/A
=> Sync strings from feat/ledger

packages/shared/lib/typings/events.ts, packages/shared/routes/dashboard/wallet/Wallet.svelte
Mask the errors displayed to do with Ledger on login (they are an eye sore).
Tested by simulating error message types
=> fix: mask ledger errors on login

packages/backend/bindings/node/index.ts, packages/shared/lib/shell/walletApi.ts, packages/shared/lib/typings/account.ts, packages/shared/lib/typings/bridge.ts, packages/shared/lib/wallet.ts, packages/shared/routes/dashboard/Dashboard.svelte, packages/shared/routes/setup/ledger/views/LegacyIntro.svelte
Starts migration on the dashboard, and stops it when a user migrates.
Enabled logging and observed syncing stopping and starting
=> fix: stops background syncing during migration of additional indexes

packages/shared/components/popups/LedgerLegacyTransaction.svelte
- Improve ledger transaction distance CSS 
N/A
Ubuntu 18.04. Ledger simulators, playing around migrations
=> Fix: some CSS

packages/shared/locales/en.json
Made small adjustment to locale data scenario when user has too many low-balance addresses.
None
=> chore: Adjust balance string

packages/shared/locales/en.json, packages/shared/routes/setup/ledger/views/AccountIndex.svelte
Only display info to check addresses after a 3 minute period and adjust the UI
Tested by setting a shorter timeout
=> fix: adjust address index ux when taking a while

packages/shared/lib/validator.ts
Adjusts validator to better handle undefined response
Tested by simulating undefined response.
=> fix: better handle cannot read id of undefined error

packages/shared/lib/migration.ts, packages/shared/locales/en.json, packages/shared/routes/setup/ledger/views/AccountIndex.svelte, packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
- De-duplicates code for gather migration bundles. 
- Adds text-centering for earlier UI fix
Not necessarily a fix, but addresses #1309 
- Chore
=> fix: Undefined migration inputs

packages/desktop/public/index.html, packages/shared/components/Video.svelte, packages/shared/lib/migration.ts
Add final ledger video url
N/A
Ubuntu 18.04. 
Click click click to import a ledger wallet and enjoy the new video 📺
=> Feat: add final ledger video

packages/desktop/public/index.html, packages/shared/lib/migration.ts
Update ledger video
N/A
Ubuntu 18.04. 
Import a trinity ledger wallet until you get to watch the new video 🥂
=> Feat: update ledger video

.github/ISSUE_TEMPLATE/bug_report.yml
Rename bug report form and update description to make it more explicit that it is for reporting bugs
=> chore: Update bug report form

packages/shared/components/popups/Version.svelte
Changed the locale for the button 'cancel' to 'close' when no update is available.
fixes issue #1083 
not
- [x ] I have followed the contribution guidelines for this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
=> fix: Close Button instead of cancel

packages/backend/README.md
Changed the linktext for the link to  "README" from "REAMDE"
- Docs (changes to the documentation)
Looked at the preview of the readme/doc
=> Fixed a typo

packages/backend/Cargo.toml, packages/backend/bindings/c/Cargo.toml, packages/backend/bindings/capacitor/WalletActorSystemCapacitorBinding.podspec, packages/backend/bindings/capacitor/package.json, packages/backend/bindings/node/native/Cargo.toml, packages/backend/bindings/node/package.json
Change author names for consistency. Bee & stronghold use _IOTA Stiftung_ and we should probably stick with the same. 
N/A
=> chore: change author name(s)

packages/desktop/package.json, yarn.lock
Reverts iotaledger/firefly#1496
=> Revert "chore(desktop): Update Electron to 12.2.1"

packages/shared/lib/network.ts, packages/shared/routes/dashboard/settings/views/Advanced.svelte
- Ensure the node is not updated unnecessarily
- Ensure that the primary node is not overwritten when we add official nodes
Tested on Mac with log statements to ensure correct node is set as primary at all times.
=> fix: network config issues

packages/shared/components/StakingIndicator.svelte, packages/shared/components/Tooltip.svelte
Make tooltip play nicer. Note this is not a longterm solution and better logic needs implementing.
Tested in end state
=> feat: adjust staking tooltip positioning

packages/shared/locales/en.json
Changed "repspective" to "respective".
=> fix: another typo

packages/shared/lib/participation/staking.ts, packages/shared/lib/utils.ts
Fixed formatting for reward amounts.
None
Tested on:
=> fix: reward formatting

packages/backend/Cargo.lock, packages/shared/lib/network.ts, packages/shared/lib/participation/participation.ts, packages/shared/lib/shell/walletApi.ts
Also, reinitialise polling when a user changes node
N/A
=> feat: stop participation overview poll if node does not have the plugin

packages/shared/routes/dashboard/wallet/views/LineChart.svelte
Clean up code to prevent warning on logout.
Manually on MacOS
=> fix: remove warning on logout

packages/shared/components/StakingIndicator.svelte, packages/shared/components/popups/StakingManager.svelte, packages/shared/locales/en.json, packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte, packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Finalises staking strings
Manually tested all staking phases and variants
=> update: finalise staking strings

packages/shared/locales/en.json
Merges staking strings ready for translators
=> chore: add staking strings

packages/shared/lib/participation/api.ts, packages/shared/lib/participation/stores.ts
Change the staked / unstaked balance calculation logic.
N/A
=> fix: change the way we calculate staked / unstaked balance

packages/shared/lib/participation/api.ts, packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Disconnecting and reconnecting to internet wasn't updating the state of some UI elements. This PR fixes the issue. 
N/A
=> fix: update UI elements when staking event state changes

packages/shared/routes/setup/Legal.svelte
Update Terms & Conditions
N/A
- Update (a change which updates existing functionality): Legal text
=> Feat: Update T&Cs

packages/shared/components/ButtonCheckbox.svelte, packages/shared/components/ButtonRadio.svelte, packages/shared/components/StakingAirdropIndicator.svelte, packages/shared/components/Tooltip.svelte, packages/shared/components/popups/Backup.svelte, packages/shared/components/popups/Index.svelte, packages/shared/components/popups/StakingConfirmation.svelte, packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte, packages/shared/routes/setup/backup/views/VerifyRecoveryPhrase.svelte
- Bugfix tooltip where it was duplicated causing flicker on edge mouseover and possibly the tooltip sometimes not being removed
- Bring back popup autofocus but make it possible to disable on selected popups: disabled on staking manager to avoid confusion
- CSS cleanup
- Retouch airdrop account pills
N/A
- Update (a change which updates existing functionality): UI
Ubuntu 20.04.
=> Feat: Polish Staking UI

packages/shared/routes/dashboard/staking/Staking.svelte
This PR aims to fix the delayed "welcome to staking" message on the first time you go there. 
N/A
=> Fix: welcome to staking dashboard message delay

packages/shared/lib/tests/mocks/i18n.ts
This PR fixes failing tests for `time.test.ts`
N/A
Tests
By running `yarn test`
=> Update time.ts unit tests

packages/shared/components/BalanceSummary.svelte
Remove tooltip from the balance summary, and just allow click to change precision.
=> update: remove balance tooltip

packages/shared/components/AccountTile.svelte, packages/shared/routes/dashboard/wallet/views/WalletActions.svelte
This change simplifies the styling of account tiles. Consulted UX but waiting for Charlies green light, hence it is in a draft.
=> fix: improve account tile styling

packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Add correct staking info link
Tested manually
=> fix: add correct staking link

packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock, packages/shared/lib/migration.ts
This PR fixes the issue where an exception was thrown during legacy ledger migration.
N/A
Manually tested with ledger device
=> fix: pass correct account id during legacy ledger migration

packages/shared/components/DeveloperProfileIndicator.svelte, packages/shared/routes/dashboard/Dashboard.svelte
- Overlay dev indicator rather than pushing down UI
- Adjust text styling
Tested on mac
=> fix: dev indicator styling

packages/desktop/electron/lib/menu.js, packages/shared/routes/dashboard/settings/views/Help.svelte
Updates links to point to the Firefly page of the wiki
Fixes #1999 
=> fix: Update links to wiki

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/create-task.yml
Updated the the bug report form
Added a create task form
Updated contact links for new issues
Example of this can be found here: https://github.com/nicole-obrien/demo-open-source-repo/issues/new/choose
=> chore: improve issue templates

.github/workflows/add-bugs-to-project.yml
Adds an action that is run when an issue is labeled, if the bug label is added then this issue is added to the [Bug Management project](https://github.com/iotaledger/firefly/projects/1) in the Needs triage column.
Tested in seperate repo: https://github.com/nicole-obrien/demo-open-source-repo/actions
=> chore: add action Assign Bugs to Project

packages/mobile/capacitor/lib/pincodeManager.ts, packages/mobile/package.json
Please write a summary of your changes and why you made them. 
Closes https://github.com/iotaledger/firefly/issues/2105
- Breaking (any change that would cause existing functionality to not work as expected)
- Docs (changes to the documentation)
Add an `x` to the boxes that are relevant to …
=> Feat: Mobile Pincode manager

packages/mobile/App.svelte, packages/shared/components/popups/Index.svelte
Added the popup component to mobile
Closes https://github.com/iotaledger/firefly/issues/2185
Building for browser, Capacitor 3, Android Studio Arctic Fox 2020.3.1, Xcode 13.
Tested on real devices and iOS/Android emulators/simulators.
```bash
$ yarn
$ yarn build
$ yarn android:update
$ yarn ios:update
```
=> Feat: Mobile Popup

packages/desktop/electron/preload.js
Adds wallet logs to desktop when in development environment.
Closes #2234
Tested that logs are present on a development build.
=> feat: add wallet log to desktop for dev environment

package.json, packages/mobile/package.json, packages/mobile/yarn.lock, yarn.lock
Fixes yarn workspaces definitions for `mobile` and uses correct path for `shared` dep.
```
Simply changes to package.jsons and lock files
```
- __Desktop__
- __Mobile__
Just needs to build
=> fix: yarn workspaces definitions

packages/shared/lib/app.ts, packages/shared/routes/dashboard/wallet/Wallet.svelte
This PR aims to hardpatch #2260 in a patch elegant way, it prevents the bug from happening but the real fix should be in #2261. 
This is a backup PR in case #2261 doesnt make it on time for the next release.
**The crash happens because when you logout from a view that is not Wallet.svelte, the router remounts it and tries to reinitialize the listeners but the actors are already destroyed while `activeProfile` persists.**
```
Hotfix crash on logout on Wallet.svelte onMount
```
Patches #2260, but does not close it.
- __Desktop__
- __Mobile__
- Login
- Go to any view that is not Wallet.svelte, that can be settings or staking atm
- …
=> Hotfix: logout crash

packages/backend/bindings/capacitor/package.json, packages/mobile/package.json, yarn.lock
This PR aims to fix the mobile build (which is also necessary atm to build desktop)
```
fix: wallet-actor-system-capacitor-binding wrong path
fix: wrong capacitor version (upgrade latest to 3)
```
- __Desktop__
- __Mobile__
- from mobile run `yarn && yarn build`
- from desktop run `cd ../../ && yarn && cd packages/backend/bindings/node/ && yarn && cd ../../../desktop && yarn && yarn build && yarn start`
=> Fix: firefly unable to build

packages/shared/components/popups/StakingManager.svelte, packages/shared/routes/setup/Congratulations.svelte, packages/shared/routes/setup/backup/views/VerifyRecoveryPhrase.svelte, packages/shared/routes/setup/import/views/Success.svelte, packages/shared/routes/setup/ledger/views/GenerateNewAddress.svelte
before: 
after:
```
Fix: surrounding green color on success check icon
```
- __Desktop__
- __Mobile__
=> Fix: surrounding green color on success check icon

packages/desktop/electron/lib/menu.js, yarn.lock
__Please summarize your changes, describing __what__ they are and __why__ they were made.__
This is an easy fix to get my developer environment up to speed. This PR fixes the Windows and Linux quit shortcut. In Windows it changes the faulty Win+Q shortcut to Alt+F4, and in Linux it changes the shortcut from Q (only worked when menu context was open) to Ctrl+Q (now works from anywhere within Firefly).
```
- Add conditional to account for Windows platform and change shortcut text accordingly.
- Update shortcut for quitting in Linux.
```
Closes #2303 
- __Desktop__
- __Mobile__
Please …
=> fix: quit shortcut

packages/backend/bindings/capacitor/android/src/main/java/org/iota/walletactorsystem/WalletPlugin.java, packages/backend/bindings/capacitor/package.json, packages/mobile/package.json
- Add sync block to listen function
- convert PascalCase to SCREAMING_SNAKE_CASE as Java conventions
- general fixes
closes https://github.com/iotaledger/firefly/issues/2295
- __Desktop__
- __Mobile__
```bash
./packages/mobile $ yarn
./packages/mobile $ yarn android:update
./packages/mobile $ yarn dev
```
=> Fix: Android Capacitor wallet plugin

packages/shared/lib/common/index.ts, packages/shared/lib/core/index.ts
The recently added `core` and `common` modules each contained an empty `index.ts` file that caused the build step to fail.
```
- Add empty exports to both barrel files
```
_N/a_
- __Desktop__
- __Mobile__
_N/a_
=> fix: ensure package modules

packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock
Update wallet.rs to hash `2d536094ee6711c523b60c31908b9b6faf8f140b` to include voting counts in `ParticipationEvent`
```
Chore: point wallet.rs to hash 2d536094ee6711c523b60c31908b9b6faf8f140b
```
- __Desktop__
- __Mobile__
=> chore: update voting wallet.rs

packages/backend/bindings/capacitor/package.json
Running `yarn` in the root directory of Firefly after a fresh clone of develop caused the following error on Windows:
```
error C:\Users\jkraf\iotaledger\firefly\node_modules\firefly-actor-system-capacitor-bindings: Command failed.
Exit code: 1
Command: npm run clean && npm run build
Arguments:
Directory: C:\Users\jkraf\iotaledger\firefly\node_modules\firefly-actor-system-capacitor-bindings
Output:
> firefly-actor-system-capacitor-bindings@0.0.1 clean C:\Users\jkraf\iotaledger\firefly\node_modules\firefly-actor-system-capacitor-bindings
> rimraf ./dist
internal/modules/cjs/loader.js:905
throw err;
^
Error: Cannot find module 'C:\Users\jkraf\node_modules\rimraf\bin.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
at Function.Module._load …
```
=> chore: update capacitor bindings script

packages/shared/components/popups/Transaction.svelte, packages/shared/locales/en.json
Adds unvoting disclaimer when voting is active or staking+voting
closes: #2143 
- __Desktop__
- __Mobile__
=> feat: send unvoting disclaimer

packages/desktop/package.json, yarn.lock
We need to update Electron to at least version 12, which contains some potentially breaking changes. __As such this MUST be tested on all desktop platforms__.
```
- Update Electron version from 11.5.0 to 12.2.3
```
#2213
- __Desktop__
- __Mobile__
Tested general navigation of app and also some functionality (not all).
=> chore: update `electron` to 12.2.3

packages/shared/components/popups/GovernanceCastVote.svelte
Merge button only shows if current funds are not equal to voted funds.
```
merge button shows upon hasReceivedFundsSinceLastVote condition.
```
closes: https://github.com/iotaledger/firefly/issues/2443
- __Desktop__
- __Mobile__
=> fix: only show merge buttons if necessary

packages/shared/components/popups/Transaction.svelte
Adds ternary operator in `isAccountVoting` to fix Transaction.svelte crash
closes #2444 
- __Desktop__
- __Mobile__
=> fix: Transaction.svelte crash

packages/backend/bindings/capacitor/package.json, packages/backend/bindings/capacitor/scripts/build.js
Changed build script to call only one npm instead of providing multiple commands to call. 
```
- Updated packages/backend/bindings/capacitor/package.json build:bundle script to include rimraf
- Changed packages/backend/bindings/scripts/build.js script to only call one npm script
```
- __Desktop__
- __Mobile__
Please tick all of the following boxes that …
=> fix: capacitor bindings not building

packages/shared/components/inputs/Dropdown.svelte, packages/shared/lib/app.ts, packages/shared/lib/typings/app.ts, packages/shared/lib/typings/sendParams.ts, packages/shared/lib/typings/wallet.ts, packages/shared/routes/dashboard/wallet/views/Send.svelte
Merge https://github.com/iotaledger/firefly/pull/2470 first!
This fixes bug https://github.com/iotaledger/firefly/issues/2451.
```
- Added typings to `Dropdown.svelte` and `Send.svelte`
- Extracts `SendParams` into separate file
- Groups logic wrt converting and setting the amount into one function
- Fixes the issue with comparing amounts to see if user clicked the max amount button in fiat
```
closes: https://github.com/iotaledger/firefly/issues/2451
- __Desktop__
- __Mobile__
Please …
=> fix: click max fiat

packages/shared/routes/login/views/EnterPin.svelte, packages/shared/routes/setup/Profile.svelte
Currently Sentry is not implemented on Mobile, added temporally optional values to AppSettings store.
This PR solves Android crashes at the moment of create the password.
Closes https://github.com/iotaledger/firefly/issues/2397
- __Desktop__
- __Mobile__
=> Fix: Mobile Sentry

packages/shared/components/Button.svelte, packages/shared/components/modals/ProfileActions.svelte, packages/shared/locales/en.json
Moves backup state & action to profile modal
closes #2509 
- __Desktop__
- __Mobile__
=> feat: move backup to profile modal

packages/shared/components/modals/ProfileActions.svelte, packages/shared/locales/en.json
Moves firefly update state & action to profile modal
closes #2508 
- __Desktop__
- __Mobile__
=> feat: move update to profile modal

yarn.lock
Fixes malformed lockfile changes introduced in #2502
=> chore: fix lock file

packages/shared/components/modals/ProfileActions.svelte
This PR aims to fix some issues on the profile modal that were introduced by the last merge conflicts & polish some CSS
```
- fix: wrong profile modal logic for backup and ledger
- polish profile modal css
```
N/A
- __Desktop__
- __Mobile__
=> Feat: fix wrong merge & polish CSS

packages/shared/components/Drawer.svelte, packages/shared/components/popups/AddNode.svelte, packages/shared/components/popups/AddressHistory.svelte, packages/shared/components/popups/Backup.svelte, packages/shared/components/popups/DeleteProfile.svelte, packages/shared/components/popups/ErrorLog.svelte, packages/shared/components/popups/HideAccount.svelte, packages/shared/components/popups/Index.svelte, packages/shared/components/popups/LedgerMigrateIndex.svelte, packages/shared/components/popups/MissingBundle.svelte, packages/shared/components/popups/Password.svelte, packages/shared/components/popups/RemoveNode.svelte, packages/shared/components/popups/RiskFunds.svelte, packages/shared/components/popups/SwitchNetwork.svelte, packages/shared/components/popups/Version.svelte
This PR aims to convert the Drawer component into mobile popups, except for fullScreen popups
```
```
Closes #2258
Closes #2250
- __Desktop__
- __Mobile__
=> feat: convert mobile popups into drawers

packages/mobile/README.md
Update readme file on mobile folder with latest changes. It was based on desktop version.
Closes #2551 
- __Desktop__
- __Mobile__
=> chore: update mobile readme

packages/shared/components/AssetTile.svelte, packages/shared/components/StakingAssetTile.svelte, packages/shared/components/index.js, packages/shared/lib/assets.ts, packages/shared/lib/participation/staking.ts, packages/shared/lib/participation/stores.ts, packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte, packages/shared/routes/dashboard/wallet/views/AccountAssets.svelte
Adds rewards per account and staking warnings to asset tiles because the code needed to be adapted to single wallet refactor
closes #2161 #2162 
- __Desktop__
- __Mobile__
Needs to be tested with all staking possible states
=> feat: rewards per account and staking warnings

packages/desktop/App.svelte, packages/desktop/electron/lib/menu.js, packages/shared/lib/typings/events.ts, packages/shared/lib/typings/routes.ts
Update electron menu to single wallet
```
feat: Update electron menu to single wallet
```
Closes #2166
- __Desktop__
- __Mobile__
To test the changes you need to run `yarn build` from desktop
=> feat: update electron menu to single wallet

packages/shared/components/popups/CreateAccount.svelte, packages/shared/components/popups/Index.svelte
Fixes create wallet popup spacing and balanceEquiv display
closes #2625 
- __Desktop__
- __Mobile__
=> fix: create wallet UI

packages/backend/Cargo.lock, packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock, packages/shared/lib/participation/constants.ts
point to latest wallet-rs and add mainnet staking events
```
chore: point to latest wallet-rs and add mainnet staking events
```
- __Desktop__
- __Mobile__
=> chore: point to latest wallet-rs and add mainnet staking events

packages/shared/locales/en.json
Changed 
```
Changed locale string for hint on theme settings to improve semantics.
```
- __Desktop__
- __Mobile__
=> fix: improve wording for theme settings hint

packages/desktop/App.svelte
Add missing import statement that was accidentally removed in https://github.com/iotaledger/firefly/pull/2505#discussion_r837383105
```
Add import get statement to App.svelte in desktop package
```
- __Desktop__
- __Mobile__
Please tick all of the following boxes that are relevant to your …
=> fix: add missing get import to App.svelte

packages/shared/components/Sidebar.svelte
- fix wrong `Sidebar.svelte` rebase
- add governance tab
```
fix: wrong `Sidebar.svelte` rebase & add governance tab
```
- __Desktop__
- __Mobile__
=> fix: wrong `Sidebar.svelte` rebase & add governance tab

packages/shared/components/popups/StakingManager.svelte
This PR aims to fix staking issues that popped on ledger:
- Wrong reactivity/subscription to pendingParticipations lead to ledger infinite spinner
- Staking tx errors where not being fetched by the manager, eg: when you rejected staking on ledger nothing happened
```
fix: staking erros not displaying
fix: participation wrong reactivity lead to infinite ledger spinner
```
Closes #2678
- __Desktop__
- __Mobile__
Please tick all of the following boxes that are relevant to your changes, and …
=> fix: ledger staking

packages/backend/Cargo.lock, packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock
Update wallet.rs to fix missing addresses.
```
Fix missing addresses
```
Maybe https://github.com/iotaledger/firefly/issues/2647?
- __Desktop__
Recover accounts and check the addresses in the accounts, there shouldn't be any gaps in the internal or deposit address ranges of an account (maybe relogin required so it gets updated)
=> chore: update wallet.rs to fix missing addresses

packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
I encountered an error due to a missing optional chaining operator on `selectedAccountParticipationOverview`.
```
Added a missing optional chaining operator
```
- __Desktop__
- __Mobile__
=> fix: use optional chaining

packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte
The days in staking airdrop view didn't update reactively
```
update days to reactively change
refactored arrow functions
```
- __Desktop__
- __Mobile__
=> fix: reactive days + minor refactor

packages/backend/Cargo.lock, packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock
Update wallet.rs to fix deserialization of old messages.
```
Update wallet.rs to fix deserialization of old messages.
```
https://github.com/iotaledger/firefly/issues/2753
- __Desktop__
=> chore: update wallet.rs to fix deserialization of old messages

packages/shared/components/AccountSwitcher.svelte, packages/shared/components/Sidebar.svelte, packages/shared/components/modals/AccountActions.svelte, packages/shared/components/modals/AccountSwitcher.svelte, packages/shared/components/modals/Modal.svelte, packages/shared/components/modals/NetworkIndicator.svelte, packages/shared/components/modals/ProfileActions.svelte, packages/shared/routes/dashboard/wallet/Wallet.svelte
Refactors modal because there was having a conflict between click outside and an outside element that toggled the modal visibility
closes #2734 
- __Desktop__
- __Mobile__
=> fix: refactors modal

packages/shared/components/PingingBadge.svelte, packages/shared/components/Sidebar.svelte, packages/shared/components/SidebarTab.svelte, packages/shared/components/index.js, packages/shared/components/modals/Modal.svelte, packages/shared/components/modals/ProfileActions.svelte, packages/shared/lib/profile.ts
closes #2742 
- __Desktop__
- __Mobile__
=> feat: adds profile icon notification for backup and version update

packages/shared/components/AccountSwitcher.svelte, packages/shared/components/StakingAssetTile.svelte, packages/shared/components/inputs/Toggle.svelte, packages/shared/components/modals/AccountSwitcher.svelte
- improve staking asset tile hover colors
- improve scrollbar position in account switcher & increase max h… 
- improve account switcher font sizes
- add border to account color circle in wallet switcher
- add border to toggle in darkmode to improve visibility
```
feat: improve staking asset tile hover colors
feat: improve scrollbar position in account switcher & increase max h… 
feat: improve account switcher font sizes
feat: add border to account color circle in wallet switcher
feat: add border to toggle in darkmode to improve visibility
```
closes #2741, closes #2740, closes #2739, closes #2736, closes #2732, closes #2775
- …
=> feat: single wallet UI polish

packages/shared/components/ActivityDetail.svelte, packages/shared/components/ActivityRow.svelte, packages/shared/lib/transactionHistory.ts, packages/shared/lib/wallet.ts, packages/shared/locales/en.json
We are getting the wrong timestamp from some nodes, this ws fixed in Bee but the problem is still persisting. We should therefor handle this case on the frontend.
```
- add try catch blocks to getWalletHistory
- add try catch around converting timestamp to a date
```
Fixes #2795 
- __Desktop__
- __Mobile__
Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes …
=> fix: error handling of invalid timestamps

packages/shared/locales/en.json, packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte
Add status ribbon to staking airdrop tiles
```
feat: add status ribbon to staking airdrop tiles
```
Closes #2729
- __Desktop__
- __Mobile__
=> feat: add status ribbon to staking airdrop tiles

packages/shared/components/QR.svelte, packages/shared/routes/dashboard/wallet/views/Receive.svelte
Adds responsiveness to receive QR code to improve it visually
closes #2807 
- __Desktop__
- __Mobile__
=> fix: adds responsiveness to receive qr code

packages/desktop/electron/main.js
Fix the link to report an issue that is broken
closes #2808
- __Desktop__
- __Mobile__
=> fix: adds issue report url to allowed list

packages/desktop/electron/preload.js, packages/desktop/package.json, packages/desktop/scripts/create-build-dir.js, packages/shared/lib/shell/walletApi.ts, yarn.lock
Be able to use the new bindings inside the electron app.
```
- Exposing stardust API through the contextBridge
- Installed and imported @iota/wallet
```
- __Desktop__
- __Mobile__
=> feat: stardust

packages/shared/components/popups/BalanceFinder.svelte, packages/shared/locales/en.json
This vastly improves the balance finder experience, making the user aware that they need to click multiple times to search more addresses and account. It also shows in numbers how many accounts have been searched and accounts searched and found.
Before first search:
After first search:
```
- Update text to include previous airdrop rewards
- Fix logic in button to display the correct text
- Show how many accounts where found
- Show how many accounts where searched
- Show how many addresses where searched per address
- Show hint after initial search so the user knows they should search again
```
Please select any type below that is applicable to your …
=> enhancement: improve balance finder UX and wording

packages/shared/components/popups/StakingManager.svelte
Updated the styling of the staking manager.
Before:
After:
```
Changed header style
Adjusted margin between sections.
```
- __Desktop__
- __Mobile__
=> fix: update spacing and styling of staking manager

packages/shared/components/AccountSwitcher.svelte, packages/shared/routes/dashboard/Dashboard.svelte
Guide was opening before loading screen had finished, and was also not being dismissed if the user had used the account switcher.
```
- add onclick handler to update state when the switcher is clicked
- add additional checks before opening the guide
```
- __Desktop__
- __Mobile__
Please …
=> fix: single account guide opening before accounts loaded

packages/shared/components/popups/SingleAccountGuide.svelte, packages/shared/locales/en.json
Updated the single account guide text and added a hint:
Before:
After:
```
- updated title on single account guide
- updated body
- added hint to use the balance finder if the wallet is not in switcher
```
- __Desktop__
- __Mobile__
Please tick all of the following boxes that are relevant …
=> fix: single account guide wording

packages/desktop/electron/electronApi.js
Some how at some point the ledger object was removed from the platform api, specifically the ElectronApi. This change simply adds it back so that the raised bug no longer occurs.
Originally it was not getting passed the onClick handler in the AccountIndex page during onboarding flow. This was because there was no ledger object on the Platform object, so all the functions returned undefined. Perhaps in the future we should wrap any platform calls in a try catch block.
```
- add ledger object to ElectorApi
```
Please select any platforms where your changes have …
=> fix: ledger migration not working because of missing ledger object on platform api

packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Fixing a mistake where the function wasn't exiting after doing a null check. 
```
- Add return statement if null check is satisfied 
- Add optional chaining and nullish coalescing operator as fallback
```
_None_
- __Desktop__
- __Mobile__
Open staking dashboard while syncing in a fresh login session.
=> fix: handle null participation overview object

packages/shared/components/AccountSwitcher.svelte, packages/shared/components/modals/AccountSwitcher.svelte
- Reduce circle border to 1px
- Remove chevron transition animation
- Adjust text color & remove selected bg
```
feat: polish wallet switcher css
```
Close #2897, close #2895, close #2896
- __Desktop__
- __Mobile__
=> feat: polish wallet switcher css

package.json
There was a discrepancy between 'lint-staged' and normal eslint. The problem arose from the fact that lint-staged also linted scss and css files, while eslint did not.
```
- Removed check of scss and css files from lint-staged
```
- __Desktop__
- __Mobile__
=> chore: removed scss and css files from lint-staged

packages/shared/components/modals/Modal.svelte, packages/shared/components/modals/ProfileActions.svelte
- Update modals border radius
- Polish profile modal
```
feat: polish profile modal
```
Close #2898
- __Desktop__
- __Mobile__
=> Feat: polish profile modal

packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
I notice that an auto subscription was missing in StakingInfo component
```
- add missing auto subscription to StakingInfo component 
```
- __Desktop__
- __Mobile__
=> fix: missing auto subscription in StakingInfo

packages/backend/Cargo.lock, packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock
Update wallet.rs to get assembly event id from Firefly.
```
Update wallet.rs to get assembly event id from Firefly.
```
- __Desktop__
=> chore: update wallet.rs rev

packages/shared/lib/participation/stores.ts, packages/shared/routes/dashboard/Dashboard.svelte
See details of attached issue.
```
- update event state stores when participation event store is updated
- load participation events onMount of dashboard
```
- __Desktop__
- __Mobile__
=> fix: improve loading of event state

packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
```
Change read more link in stakingInfo to go to https://blog.iota.org/iota-staking-for-assembly-continues/
```
- __Desktop__
- __Mobile__
=> update: staking blog link with new link

packages/shared/lib/participation/constants.ts
```
chore: update assembly event id to mainnet event 2
chore: set current assembly staking period to 2
chore: set start date to April 22, 2022
```
- __Desktop__
- __Mobile__
=> chore: prepare constants for staking period 2

packages/desktop/public/index.html, packages/shared/lib/participation/constants.ts
```
- add url for staking results from previous mainnet events.
- add urls to content security policy
```
- __Desktop__
- __Mobile__
=> chore: add staking result file urls

packages/backend/Cargo.lock, packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock
Bump wallet.rs rev
```
Bump wallet.rs rev to fix account discovery for accounts without outputs on public addresses.
```
- __Desktop__
- __Mobile__
=> chore: bump wallet.rs rev to fix account discovery

packages/backend/Cargo.toml, packages/desktop/package.json
This increments the desktop version to 1.5.0 before release and also updates the version of the backend so that we can match the errors in sentry with the release version.
```
- set version to 1.5.0
- set backend version to 1.5.0
```
- __Desktop__
- __Mobile__
Please tick all of the following boxes that are relevant to your changes, and delete those …
=> chore: increment desktop version number to 1.5.0

packages/shared/lib/participation/staking.ts
```
Change reward calc multiplier from 4 to 2.
```
- __Desktop__
- __Mobile__
=> fix: fix reward calc

packages/shared/components/TitleBar.svelte
```
fix: windows top resize
```
Close #2951
- __Desktop__
- __Mobile__
=> fix: windows top resize

packages/shared/components/modals/ProfileActions.svelte
Adjust logout behaviour to match #2992
```
- Return to profile selection page on manual logout
```
Fixes #2992 
- __Desktop__
- __Mobile__
- if the user clicks logout then they are taken to profile selection screen
- if the system auto logs out, then you are taken to the login screen for that profile
- if you close the app while logged in, or while on the login screen you are taken to the login screen for that profile on next app start
- if you close the app on the profile selection you are taken to the profile selection screen on next app start
Please tick all of the following boxes that are relevant to your changes, and delete …
=> enhancement: adjust logout behaviour

packages/shared/lib/core/router/helper.ts
Resets governance router on logout
```
Resets governance router on logout
```
Fixes #2997
- __Desktop__
- __Mobile__
Change governance route, log out. Confirm it has reset on log in.
=> fix: reset governance router on logout

packages/shared/lib/profile.ts, packages/shared/lib/typings/profile.ts
Add typings for stardust network options.
```
```
Added ProfileNetwork enum to cover network types and added network as a field to the profile object with that type.
- __Desktop__
- __Mobile__
Please tick all of the following boxes that are relevant to your changes, and delete those that …
=> feat: add stardust network typings to profile object

packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte
- polish event detail tooltips (improved logic)
- some UI polish around the `GovernanceEventDetails.svelte`
```
```
Close #2996
- __Desktop__
- __Mobile__
=> feat: polish event detail tooltips

packages/shared/lib/walletApiListeners.ts, packages/shared/locales/en.json
This PR adds participation tx confirmation notification for voting
```
feat: add voting app notifications
```
Close #3014
- __Desktop__
- __Mobile__
=> feat: add voting app notifications

packages/shared/components/popups/GovernanceManager.svelte, packages/shared/components/popups/Index.svelte, packages/shared/components/popups/StakingConfirmation.svelte, packages/shared/lib/participation/account.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/governance/views/GovernanceDashboard.svelte, packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte, packages/shared/routes/dashboard/governance/views/GovernanceInfo.svelte
This PR aims to update the voting flows to be more similar to staking
There are also a minor CSS updates
```
feat: update voting flows to be more similar to staking
fix: ledger flow
feat: remove voting confirmation popup 
```
Close #2411
- __Desktop__
- __Mobile__
=> Feat: update voting flows

packages/desktop/public/index.html, packages/shared/lib/participation/constants.ts, packages/shared/lib/participation/staking.ts, packages/shared/locales/en.json
This change retries the fetching of previous participation reward files using a backup in s3, if the initial request with github fails.
```
- change content security policy for reward url and backup url
- change constants to separate file name from urls
- add back up url
- retry fetch of rewards if failure using backup url
- add error logging for failure of fetching rewards
```
- __Desktop__
- __Mobile__
Please describe the specific instructions, configurations, and/or test cases necessary to …
=> enhancement: add backup for retrieving previous airdrop rewards

packages/shared/locales/en.json, packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte
Update voting power text to read "voting weight".
Update event details times.
```
Update voting power text to read "voting weight".
Update event details times.
```
Fixes #3009
- __Desktop__
- __Mobile__
=> feat: adjust voting info

packages/shared/components/GovernanceInfoTooltip.svelte, packages/shared/locales/en.json, packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte
Revises usage of governance event details and tooltips to simplify UX.
```
- Conditionally renders tooltips in event details
- Uses full voting rate in tooltip
- Adds maximum votes to counting phase
- Changes event detail text for each of the voting phases
```
Fixes #2882
- __Desktop__
- __Mobile__
Try out each voting phase (including actively voting) and check everything is intuitive.
=> enhancement: fixes voting rate and polishes event details pane

packages/shared/components/GovernanceInfoTooltip.svelte, packages/shared/lib/time.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte
Fixes a few things for the voting ended state (and some things throughout other event details)
```
- Fixes NaN percentage if an option has no votes
- Use past tense for timeline events in the past
- Temporary fix for maximum votes to stop it increasing
- Fix end state duration text
- Formats long numbers with comma separator 
```
- __Desktop__
- __Mobile__
Please tick all of the following boxes that are relevant to your changes, and delete …
=> enhancement: polishes voting end state

packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock, packages/shared/components/GovernanceInfoTooltip.svelte, packages/shared/lib/participation/account.ts, packages/shared/routes/dashboard/Dashboard.svelte, packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte
Various fixes around voting totals and logic.
```
- Use correct reset function on dashboard destroy
- Fixes maximum vote calculation and display
- Only display maximum while someone is actively voting
- Fixes voting rate calculation and formatting
- Updates wallet-rs revision to fix return of incomplete trackedParticipations
- Ensures partial merge UI does not show while voting/unvoting
```
Fixes #3090
- __Desktop__
- __Mobile__
Test various voting actions on a holding event. Make sure partial vote merge works as intended.
=> fix: vote totals calculation and display and other bug fixes

packages/shared/components/AccountSwitcher.svelte, packages/shared/components/ActivityDetail.svelte, packages/shared/components/ColorPicker.svelte, packages/shared/components/WalletPill.svelte, packages/shared/components/charts/Bar.svelte, packages/shared/components/charts/Line.svelte, packages/shared/components/modals/AccountSwitcher.svelte, packages/shared/components/popups/CreateAccount.svelte, packages/shared/lib/chart.ts, packages/shared/lib/profile.ts, packages/shared/lib/typings/account.ts, packages/shared/lib/typings/chart.ts, packages/shared/lib/typings/color.ts, packages/shared/lib/wallet.ts, packages/shared/routes/dashboard/wallet/views/ManageAccount.svelte
Refactors the getColor function to not be recursive, to have optional chaining, and to have only the accountId parameter
possibly closes #3076 
- __Desktop__
- __Mobile__
=> fix: refactors getColor

packages/shared/lib/network.ts, packages/shared/lib/tests/network.test.ts, packages/shared/lib/typings/assets.ts, packages/shared/lib/typings/network.ts
Refactors network lib and adds shimmer networks. (this is a dependency for tasks related to setting shimmer profiles)
- __Desktop__
- __Mobile__
=> feat: stardust shimmer network

packages/mobile/capacitor/capacitorApi.ts
Implement on CapacitorApi.ts the function SaveRecoveryKit using the plugin `capacitor-secure-storage-plugin`
This PR depends on https://github.com/iotaledger/firefly/pull/2460
Closes https://github.com/iotaledger/firefly/issues/2236
- __Desktop__
- __Mobile__
=> feat: mobile save recovery kit PDF

packages/mobile/capacitor/capacitorApi.ts
Implement `removeProfileFolder` function calling `SecureFilesystemAccess` Capacitor plugin.
This PR depends on https://github.com/iotaledger/firefly/pull/2460
```
- Implement `removeProfileFolder`
- Fix `getUserDataPath`
```
Closes https://github.com/iotaledger/firefly/issues/2097
- __Desktop__
- __Mobile__
=> feat: mobile delete profile folder

packages/shared/lib/typings/profileManager.ts, packages/shared/lib/wallet.ts
Previously, we were using the older node info type.
```
- Changed the API wrapper function to use new bindings
- Changed function signatures as needed
- Updated node info type
```
Closed #3176 
- __Desktop__
- __Mobile__
=> fix: adjust bindings for node info

packages/mobile/capacitor/capacitorApi.ts
Fixes `prettier` warnings in mobile
```
Fix prettier warnings
```
N/A
N/A
=> chore: fix prettier warnings in mobile

packages/shared/routes/dashboard/wallet/views/Receive.svelte
Fix wrong QR sizing hides content in receive pane
```
fix: receive qr responsiveness
```
- __Desktop__
- __Mobile__
=> fix: receive qr responsiveness

packages/shared/locales/en.json
Sync changes made in 90dae67c4019283eb183e0405fbe17cdcfd455ac and 86cc36644b74fcb684ded449e0777afc217236c3 to `develop` so they're picked up by Crowdin
```
Sync strings for desktop to develop
```
N/A
N/A
=> chore: sync strings from Desktop 1.5.2 to develop

packages/desktop/package.json, packages/shared/lib/core/network/actions/updateClientOptions.ts, packages/shared/lib/core/network/constants/network.constant.ts, packages/shared/lib/core/network/helpers/buildClientOptions.ts, packages/shared/lib/core/network/helpers/index.ts, packages/shared/lib/core/network/interfaces/network.interface.ts, packages/shared/lib/core/network/interfaces/node.interface.ts, packages/shared/lib/core/network/interfaces/rent-structure.ts, packages/shared/lib/core/network/utils/ensureSinglePrimaryNode.ts, packages/shared/lib/core/network/utils/getDefaultClientOptions.ts, packages/shared/lib/core/network/utils/getNodeCandidates.ts, packages/shared/lib/core/network/utils/getOfficialNodes.ts, packages/shared/lib/core/profile-manager/actions/initialiseProfileManager.ts, packages/shared/lib/core/profile-manager/api/restoreBackup.ts, packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts, packages/shared/lib/core/profile/actions/active-profile.ts, packages/shared/lib/tests/__mocks__/profileManager.mock.ts, packages/shared/lib/tests/api.test.ts, packages/shared/lib/tests/network.test.ts, packages/shared/lib/typings/account.ts, packages/shared/package.json, packages/shared/routes/setup/Profile.svelte, yarn.lock
Co-authored-by: Tuditi <Tuditi@users.noreply.github.com>
```
```
- __Desktop__
- __Mobile__
=> chore: upgrade @iota/wallet to 1.0.8

packages/mobile/capacitor/capacitorApi.ts
`IPlatform` is already being imported on line 13
```
- Remove duplicate import of IPlatform
```
N/A
- __Desktop__
- __Mobile__
Builds successfully
=> fix: remove duplicate import

packages/mobile/android/app/src/main/AndroidManifest.xml, packages/mobile/ios/App/App/Info.plist
Modified the manifest for Android as well as the plist for IOS to disable the device rotation.
```
```
close #3096
- __Desktop__
- __Mobile__
=> chore: Disable horizontal rotation of the device

packages/shared/lib/core/profile-manager/actions/destroyProfileManager.ts, packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
Fixes logout() issues
```
- added destroy() to the IProfileManager interface
- called destroy() upon logout()
```
closes: https://github.com/iotaledger/firefly/issues/3258
- __Desktop__
- __Mobile__
=> fix: logout issues

packages/shared/routes/dashboard/governance/views/GovernanceEventInfo.svelte
Prevents attempted vote when user has zero balance
```
- Adds notification when user tries to vote when their wallet has 0 balance
```
Fixes #3173 
- __Desktop__
- __Mobile__
=> feat: block vote with zero balance

.eslintrc.js, packages/desktop/electron/preload.js, packages/mobile/App.svelte, packages/shared/components/inputs/Pin.svelte, packages/shared/components/popups/ActivityDetailsPopup.svelte, packages/shared/components/popups/DeleteProfile.svelte, packages/shared/lib/helpers.ts, packages/shared/lib/migration.ts, packages/shared/lib/shell/walletApi.ts, packages/shared/lib/utils.ts, packages/shared/lib/validator.ts, packages/shared/lib/wallet.ts, packages/shared/routes/login/views/EnterPin.svelte
Update the rules so that linter throws an error if `==` (or `!=`) is used instead of `===` (or `!==`). This coerces us to always use strict equality instead of relying on the obscure  Abstract Equality Comparison Algorithm.
```
- added eqeqeq rule to linter
- Fixed linter errors wrt eqeqeq rule
```
https://github.com/iotaledger/firefly/issues/3283
- __Desktop__
- __Mobile__
=> chore: add eqeqeq to linter

packages/shared/components/GovernanceInfoTooltip.svelte, packages/shared/components/popups/Transaction.svelte, packages/shared/locales/en.json
Minor changes to voting text
```
- Updates some voting strings
- Ensures user is warned about cancelling a vote if they send when below min stake rewards
```
- __Desktop__
- __Mobile__
=> fix: voting text fixes

packages/shared/locales/en.json, packages/shared/routes/dashboard/governance/views/GovernanceEventResults.svelte
This PR updated the voting result graphs to display the results in tooltips & update the CSS
_Please note that the code is quite ugly and static, I tried making the tooltip management dynamic but the dynamic anchor binding wasnt working for some reason 🙏🏼  _
```
feat: move voting results to tooltip & update CSS
```
Close #3172, close #3085
- __Desktop__
- __Mobile__
=> feat: move voting results to tooltip & update CSS

packages/shared/components/modals/AccountSwitcher.svelte, packages/shared/locales/en.json
```
feat: disable add new wallet while participating
```
Close #3291
- __Desktop__
- __Mobile__
=> feat: disable add new wallet while participating

packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
This PR Allow aims to allow the user to search literal strings for participation actions like "voting" "staking"
```
feat: add participation action literal string search
```
- __Desktop__
- __Mobile__
=> feat: add participation action literal string search

packages/shared/components/Sidebar.svelte
This PR aims to keep the user governance router state on wallet navigation to prevent the user from getting lost.
```
feat: remove governance router reset on tab selection
```
- __Desktop__
- __Mobile__
=> feat: remove governance router reset on tab selection

packages/shared/lib/core/account/api/collectOutputs.ts, packages/shared/lib/core/account/interfaces/account.interface.ts, packages/shared/lib/core/network/constants/network.constant.ts, packages/shared/lib/core/wallet/actions/trySend.ts, packages/shared/lib/tests/__mocks__/account.mock.ts, packages/shared/lib/tests/network.test.ts, packages/shared/package.json, yarn.lock
Update iota/wallet to 1.0.17
```
Update iota/wallet to 1.0.17
```
closes: https://github.com/iotaledger/firefly/issues/3356
- __Desktop__
- __Mobile__
=> feat: new @iota/wallet version

packages/shared/lib/tests/network.test.ts
Updated one of the mainnet urls as fix for failing network tests during CI.
```
- Changed a wrong mainnet url for the network tests
```
- __Desktop__
- __Mobile__
=> fix: changes wrong mainnet url

packages/shared/components/GovernanceInfoTooltip.svelte
Improve voting timeline in darkmode
```
feat: improve voting timeline in darkmode
```
- __Desktop__
- __Mobile__
=> feat: improve voting timeline in darkmode

packages/shared/lib/participation/governance.ts, packages/shared/routes/dashboard/governance/views/GovernanceEventStats.svelte
```
fix: your counted votes & your maximum votes
```
Close #3383
- __Desktop__
- __Mobile__
=> fix: your counted votes & your maximum votes

.github/workflows/handbook.yml
If we do not change this then it will overwrite the changes made on `stardust-develop`.
```
- Changes branch for triggering the handbook workflow
```
(Partially) resolves #3387 
- __Desktop__
- __Mobile__
_None_
=> chore: update branch for triggering handbook workflow

packages/shared/components/inputs/AssetDropdown.svelte
Adds asset icon color in AssetDropdown.svelte
closes #3279
- __Desktop__
- __Mobile__
=> feat: update send form's asset button style

packages/shared/package.json, yarn.lock
Updated wallet-stardust-alpha package to the latest
```
- update wallet-stardust-alpha to 1.0.20
```
closes: https://github.com/iotaledger/firefly/issues/3365
- __Desktop__
- __Mobile__
=> feat: update wallet 1.20

packages/shared/components/inputs/Password.svelte
closes #3077 
- __Desktop__
- __Mobile__
=> fix: password strength text color

packages/shared/components/NetworkIndicator.svelte, packages/shared/lib/core/network/actions/getAndUpdateNodeInfo.ts, packages/shared/lib/core/network/interfaces/node-info-response.interface.ts, packages/shared/lib/tests/__mocks__/account.mock.ts, packages/shared/package.json, yarn.lock
Updated wallet.rs backend to the latest version
```
- update dependency wallet-stardust-alpha to 1.0.21
```
- __Desktop__
- __Mobile__
=> chore: updated wallet.rs to 1.0.21

packages/shared/lib/core/profile/actions/add-node.ts, packages/shared/lib/core/wallet/classes/activity.class.ts, packages/shared/lib/core/wallet/utils/isAsyncActivity.ts, packages/shared/lib/tests/__mocks__/profileManager.mock.ts, packages/shared/lib/validator.ts
```
```
- __Desktop__
- __Mobile__
=> fix: build issues to do with types

packages/shared/lib/core/profile-manager/api/events/newOutput.ts
It breaks the build otherwise. 
```
```
- __Desktop__
- __Mobile__
=> fix: use correct output type in event handler

docs/guides/environment-setup/ledger.md
Updated instructions for letting Firefly run with the Speculos simulator
=> updated instructions for running firefly with the Speculos simulator

packages/shared/components/inputs/RecipientInput.svelte, packages/shared/components/popups/SendFormPopup.svelte
Recipient Input should come from account.name instead of an API call to `getAlias()`
```
- account.name instead of getAlias()
- added typings
```
closes: https://github.com/iotaledger/firefly/issues/3420
- __Desktop__
- __Mobile__
=> feat: polish recipient input

packages/shared/lib/core/account/actions/buildAccountState.ts, packages/shared/lib/tests/__mocks__/account.mock.ts, packages/shared/lib/tests/__mocks__/accountBalance.mock.ts, packages/shared/package.json, yarn.lock
Update wallet stardust alpha to 1.0.23
```
- updated wallet-stardust-alpha to 1.0.23
```
closes: https://github.com/iotaledger/firefly/issues/3415
- __Desktop__
- __Mobile__
=> chore: update wallet-stardust to 1.0.23

packages/shared/lib/core/account/interfaces/account.interface.ts, packages/shared/lib/tests/__mocks__/account.mock.ts, packages/shared/lib/tests/__mocks__/profileManager.mock.ts, packages/shared/package.json, yarn.lock
Updated wallet.rs so that `prepareOutput()` can be used to calculate the storage deposit.
```
- added prepareOutput()
- update wallet.rs to 1.0.24
- fixed tests
```
https://github.com/iotaledger/firefly/issues/3488
- __Desktop__
- __Mobile__
=> chore: update wallet to 1.0.24

packages/shared/components/SettingsMenu.svelte, packages/shared/featureFlags.config.js, packages/shared/lib/core/account/actions/buildAccountState.ts, packages/shared/lib/core/router/enums/routes.ts, packages/shared/routes/dashboard/settings/views/SettingsHome.svelte, packages/shared/routes/dashboard/settings/views/SettingsViewer.svelte, packages/shared/routes/dashboard/settings/views/advanced/Advanced.svelte, packages/shared/routes/dashboard/settings/views/general/General.svelte, packages/shared/routes/dashboard/settings/views/help/Help.svelte, packages/shared/routes/dashboard/settings/views/security/Security.svelte
This pr adds feature flags to all the settings so that we can disable the settings that don't currently work or not implemented.
```
- add feature flags for all settings
- conditionally display settings in menu and on settings pages based on feature flags
- set initial setting feature flag values
```
- __Desktop__
- __Mobile__
=> enhancement: add more feature flags to disable unimplemented features

docs/guides/coding-conventions/comments.md, docs/guides/environment-setup/tools.md, docs/standard-operating-procedures/development/documentation.md, package.json, yarn.lock
To generate clean specifications, there needs to be documentation on how to write comments so that our specs read cleanly and consistently.
```
- Adds section to handbook comments on TSDoc comments
- Adds retype as dev dependency for running in dev environment
```
Closes #3265 
- __Desktop__
- __Mobile__
1. Pull in the latest on this branch
2. Run `yarn` in the root directory to install retype dependency
3. Run `yarn docs:start` in the root directory to start up local instance of handbook
=> chore: comment documentation

packages/shared/routes/setup/Profile.svelte
Add error message back to profile name onboarding page
```
```
- __Desktop__
- __Mobile__
=> fix: display error messages on profile name

.github/workflows/handbook.yml, packages/desktop/electron/electronApi.js, packages/mobile/capacitor/capacitorApi.ts, packages/mobile/ios/App/Podfile, packages/mobile/ios/App/Podfile.lock, packages/mobile/package.json, packages/shared/components/inputs/Amount.svelte, packages/shared/lib/tests/mocks/platform.ts, packages/shared/lib/typings/actionSheet.ts, packages/shared/lib/typings/platform.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/wallet/views/Send.svelte, yarn.lock
Mobile pre stardust update for the send transaction flow.
```
- Separated the send components markup between mobile and desktop
- Added capacitor acton-sheet plugin as dependency
- Added a function as hook to the amount component to use an action-sheet instead of a dropdown for unit selection
- Added a function to the send component to select the account wallets with an action-sheet
- Updated the markup of the send components mobile section to the pre stardust layout
```
Closes #3199
Closes #3198
Closes #3200 
- __Desktop__
- __Mobile__
Please describe the specific instructions, configurations, and/or test cases necessary to …
=> enhancement: update send transactions flow for mobile

packages/shared/components/inputs/ImportTextfield.svelte, packages/shared/routes/setup/Congratulations.svelte, packages/shared/routes/setup/import/views/TextImport.svelte
Fixes the bug related to locale not being defined on ImportTextField
```
- Replaced locale with localize in `ImportTextField`
- Added some types
- Removed a non-existing prop
```
- __Desktop__
- __Mobile__
=> fix: fix import onboarding

packages/shared/components/SettingsMenu.svelte, packages/shared/components/Sidebar.svelte, packages/shared/components/organisms/AccountActivity.svelte, packages/shared/components/panes/wallet/AccountActivityPane.svelte, packages/shared/components/panes/wallet/AccountSummaryAndAssetsPane.svelte, packages/shared/components/panes/wallet/BarChartPane.svelte, packages/shared/components/panes/wallet/LineChartPane.svelte, packages/shared/features/features.js, packages/shared/features/onboardingFeatures.js, packages/shared/routes/dashboard/settings/views/SettingsHome.svelte, packages/shared/routes/dashboard/settings/views/SettingsViewer.svelte, packages/shared/routes/dashboard/settings/views/advanced/Advanced.svelte, packages/shared/routes/dashboard/settings/views/general/General.svelte, packages/shared/routes/dashboard/settings/views/help/Help.svelte, packages/shared/routes/dashboard/settings/views/security/Security.svelte, packages/shared/routes/setup/Create.svelte, packages/shared/routes/setup/OnboardingNetwork.svelte, packages/shared/routes/setup/OnboardingProtocol.svelte, packages/shared/routes/setup/Setup.svelte, packages/shared/routes/setup/Welcome.svelte, packages/shared/routes/setup/import/views/Import.svelte
Added more feature flags for all onboarding routes
```
- moved feature flags to folder
- separated onboarding flags
- added flags for all onboarding routes
- set flags for alpha
```
- __Desktop__
- __Mobile__
=> refactor: improve onboarding feature flags

.github/pull_request_template.md
PRs can look a little bit neater if the template quotes the prompt for each section.
```
- Modify the PR template to quote prompts for some sections
```
_None_
- __Desktop__
- __Mobile__
Look at this PR description.
> Please tick all of the following boxes that are relevant to …
=> chore: cleanup PR template

packages/shared/components/organisms/AccountActivity.svelte
Enhance the scroll bar of the activity list so that the contents does not get squished horizontally when the scroll bar is visible
```
- adjust padding and margins to move scroll bar into existing padding space
```
- __Desktop__
- __Mobile__
=> enhancement: optimise scroll bar position on activity list

packages/shared/components/popups/WalletFinderPopup.svelte, packages/shared/locales/en.json
```
```
- __Desktop__
- __Mobile__
=> fix: strings used on wallet finder button

packages/shared/components/inputs/ExpirationDateTimePicker.svelte, packages/shared/components/modals/ExpirationTimePickerMenu.svelte, packages/shared/components/molecules/ExpirationTimePicker.svelte, packages/shared/components/popups/SendConfirmationPopup.svelte, packages/shared/lib/core/utils/index.ts, packages/shared/lib/core/utils/time.ts, packages/shared/locales/en.json
Without some extra logic, it would be possible to send transaction with invalid expiration times.
```
- Add expiration date/time validation when choosing and sending
- Polish UX for handling different test cases (see below)
```
Closes #3421 
- __Desktop__
- __Mobile__
Test …
=> fix: expiration date/time validation

packages/shared/components/HR.svelte, packages/shared/components/atoms/tiles/ClickableTile.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: tile background and hover colours

packages/shared/components/atoms/pills/ActivityAsyncStatusPill.svelte, packages/shared/components/atoms/pills/ActivityStatusPill.svelte, packages/shared/components/atoms/pills/Pill.svelte, packages/shared/components/atoms/tiles/ActivityTile.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: polish activity tile 2

packages/shared/components/modals/ProfileActions.svelte
Reflect change of toggle on stardust-api branch
...
```
- toggle change direction reversed
```
- __Desktop__
- __Mobile__
...
=> enhancement: switch toggle

packages/desktop/package.json, packages/shared/features/features.ts, packages/shared/lib/core/wallet/actions/claimActivity.ts, packages/shared/lib/core/wallet/utils/getSenderAddressFromUnlockCondition.ts, packages/shared/lib/core/wallet/utils/outputs/calculateStoragetDepositFromOutput.ts, packages/shared/lib/core/wallet/utils/outputs/getExpirationDateFromOutput.ts, packages/shared/lib/core/wallet/utils/outputs/getMetadataFromOutput.ts, packages/shared/lib/core/wallet/utils/outputs/getSenderFromOutput.ts, packages/shared/lib/core/wallet/utils/outputs/getStorageDepositFromOutput.ts, packages/shared/lib/core/wallet/utils/outputs/getTagFromOutput.ts, packages/shared/lib/core/wallet/utils/outputs/isOutputAsync.ts
A small number of fixes applied, and distributed as 2.0.0-alpha-0.0.3.
```
- Enable manual sync feature flag
- Add conditional checks and chaining to outputs in various places
- Always use the outputid when claiming an activity and not the activity id as that is not always the outputid
```
...
- __Desktop__
- __Mobile__
> Please describe the specific instructions, configurations, and/or test cases necessary to __test and …
=> fix: small number of fixes applied for v2 alpha 0.0.3

packages/shared/components/molecules/menu-items/AccountSwitcherMenuItem.svelte, packages/shared/locales/en.json
Don't block changing account if transaction is still sending
...
```
- remove `isTransferring` check
```
Closes #3604 
...
- __Desktop__
- __Mobile__
...
=> Allow changing wallets on pending transaction

packages/shared/components/ActivityDetail.svelte, packages/shared/locales/en.json
Updated the activity details UI to the new mobile beta layout 
```
- Separated desktop and mobile markup (Mobile ActivityDetail)
- Deleted the message id (Mobile ActivityDetail)
- Created a button to view the transaction with the explorer (Mobile ActivityDetail)
- Updated locals
```
Closes #3204
Closes #3205
- __Desktop__
- __Mobile__
=> enhancement: mobile beta UI update for activity details

packages/shared/components/molecules/ExpirationTimePicker.svelte, packages/shared/components/popups/SendConfirmationPopup.svelte
...
```
```
Closes #3591 
- __Desktop__
- __Mobile__
...
=> enhancement: auto add an expiration date if a storage deposit is needed for a transaction 2

packages/shared/routes/setup/import/views/Success.svelte
Fixes the import success check icon position and size according to the Figma
closes #3583
- __Desktop__
- __Mobile__
=> fix: import success layout

packages/shared/components/Animation.svelte, packages/shared/components/OnboardingLayout.svelte, packages/shared/components/RecoveryPhrase.svelte, packages/shared/components/inputs/Checkbox.svelte, packages/shared/lib/core/router/app-router.ts, packages/shared/lib/core/router/subrouters/backup-router.ts, packages/shared/locales/en.json, packages/shared/routes/setup/Balance.svelte, packages/shared/routes/setup/Congratulations.svelte, packages/shared/routes/setup/Create.svelte, packages/shared/routes/setup/Password.svelte, packages/shared/routes/setup/Profile.svelte, packages/shared/routes/setup/Secure.svelte, packages/shared/routes/setup/Setup.svelte, packages/shared/routes/setup/Welcome.svelte, packages/shared/routes/setup/import/views/BackupPassword.svelte, packages/shared/routes/setup/import/views/FileImport.svelte, packages/shared/routes/setup/import/views/Import.svelte, packages/shared/routes/setup/import/views/Success.svelte, packages/shared/routes/setup/import/views/TextImport.svelte, packages/shared/routes/setup/legal/Legal.svelte, packages/shared/routes/setup/migrate/views/Migrate.svelte, packages/shared/routes/setup/migrate/views/SecureSpentAddresses.svelte, packages/shared/routes/setup/migrate/views/SecurityCheckCompleted.svelte, packages/shared/routes/setup/protect/views/Pin.svelte, packages/shared/routes/setup/protect/views/RepeatPin.svelte
Update onboarding for mobile.
```
- Add auto-seclet language
- Set default system theme for mobile
- We should allow select recovery phrase?
```
```
Fixed all onboarding features, import, export, etc
```
Closes https://github.com/iotaledger/firefly/issues/3216
Closes https://github.com/iotaledger/firefly/issues/3217
Closes https://github.com/iotaledger/firefly/issues/3218
...
- __Desktop__
- __Mobile__
...
=> chore: update onboarding mobile (new PR)

.github/workflows/handbook.yml, packages/desktop/electron/electronApi.js, packages/mobile/capacitor/capacitorApi.ts, packages/mobile/ios/App/Podfile, packages/mobile/ios/App/Podfile.lock, packages/mobile/package.json, packages/shared/components/inputs/Amount.svelte, packages/shared/lib/tests/mocks/platform.ts, packages/shared/lib/typings/actionSheet.ts, packages/shared/lib/typings/platform.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/wallet/views/Send.svelte, yarn.lock
Fixes the overwritten changes of the send transaction flow.
tbd
tbd
- __Desktop__
- __Mobile__
...
=> fix: send transaction flow for mobile beta

packages/desktop/package.json
Bump version  after alpha release
```
- Bump desktop version to 2.0.0-alpha-0.1.0
```
...
- __Desktop__
- __Mobile__
...
=> chore: bump desktop version to 2.0.0-alpha-0.1.0

packages/shared/lib/core/wallet/classes/activity.class.ts
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: remove milestone index from expiration

.github/workflows/build-desktop.yml, packages/shared/lib/core/wallet/classes/activity.class.ts
The build script only worked when tagged a commit with only a single or multi digit number after the stage name. However we want to also get the stage if we use a tag such as 2.0.0-alpha-0.1.0
```
- Change regex for getting the stage from a tag
```
...
- __Desktop__
- __Mobile__ …
=> fix: build script for various versions

docs/guides/coding-conventions/naming.md, package.json, packages/shared/components/popups/NodeInfoPopup.svelte, packages/shared/components/popups/StakingManager.svelte, packages/shared/lib/core/network/enums/index.ts, packages/shared/lib/core/network/enums/node-plugin.enum.ts, packages/shared/lib/core/network/helpers/getNetworkStatusFromNodeInfo.ts, packages/shared/lib/core/network/interfaces/network-status.interface.ts, packages/shared/lib/core/network/stores/network-status.store.ts, packages/shared/lib/core/network/stores/node-info.store.ts, packages/shared/lib/core/network/utils/doesNodeHavePlugin.ts, packages/shared/lib/core/wallet/classes/activity.class.ts, packages/shared/lib/core/wallet/utils/getOutputOptions.ts, packages/shared/lib/participation/stores.ts, packages/shared/lib/shell/walletApi.ts, packages/shared/lib/tests/__mocks__/profileManager.mock.ts, packages/shared/locales/en.json, packages/shared/package.json, packages/shared/routes/dashboard/staking/views/StakingSummary.svelte, yarn.lock
Update the latest `@iota/wallet` and `@iota/types` dependencies.
```
- @iota/types updated to 1.0.0-beta.8
- @iota/wallet update to 2.0.1
- removed plugin property from INodeInfo
- replaced expiration.unixTime w/ expirationUnixTime
- removed/commented out code related to plugin[] on INodeInfo
```
closes: #3672
...
- __Desktop__
- __Mobile__
...
=> chore: update wallet rs

packages/shared/lib/core/profile-manager/api/events/newTransactionInclusionEvent.ts, packages/shared/lib/core/profile-manager/api/types/transactionInclusionEvent.ts
The response type for transactionInclusionEvent was updated and was not updated in the PR in which we updated the wallet.rs bindings.
```
- change props of type from snake case to camel case
```
...
- __Desktop__
- __Mobile__
... …
=> fix: transaction inclusion event type

packages/shared/lib/core/account/actions/createNewAccount.ts, packages/shared/lib/core/wallet/stores/all-account-activities.store.ts
On the creation of a new wallet, we forgot to add it to the account activities. 
```
- Add account activity list on account creation
```
Closes #3600 
...
- __Desktop__
- __Mobile__
...
=> fix: listen to events for new accounts

packages/shared/components/Animation.svelte, packages/shared/routes/dashboard/wallet/views/Send.svelte, packages/shared/routes/setup/Appearance.svelte, packages/shared/routes/setup/Balance.svelte, packages/shared/routes/setup/Congratulations.svelte, packages/shared/routes/setup/CrashReporting.svelte, packages/shared/routes/setup/Create.svelte, packages/shared/routes/setup/Password.svelte, packages/shared/routes/setup/Profile.svelte, packages/shared/routes/setup/Secure.svelte, packages/shared/routes/setup/Setup.svelte, packages/shared/routes/setup/Welcome.svelte, packages/shared/routes/setup/backup/views/Backup.svelte, packages/shared/routes/setup/backup/views/BackupToFile.svelte, packages/shared/routes/setup/import/views/BackupPassword.svelte, packages/shared/routes/setup/import/views/FileImport.svelte, packages/shared/routes/setup/import/views/Import.svelte, packages/shared/routes/setup/import/views/Success.svelte, packages/shared/routes/setup/import/views/TextImport.svelte, packages/shared/routes/setup/protect/views/Pin.svelte, packages/shared/routes/setup/protect/views/RepeatPin.svelte, packages/shared/tailwind.config.js
A `transform` inline style was added permanently to the `Animation` component, and this made any custom transform added to `classes` using Tailwind to not work. 
To fix this, I removed the `scaled` props to the `Animation` component and replace it by a custom inline style that you can append to the component.
The idea behind this is that if you want to apply a transform that is not part of tailwind you can do so by adding a custom inline CSS style. Otherwise, you can simply add the already existing transform utility classes.
This was affecting the desktop staking view
```
fix: permanent inline CSS transform property in Animation.svelte breaks any other custom transform
```
> Please list any related …
=> fix: permanent inline CSS `transform` property in `Animation.svelte` breaks any other custom `transform`

packages/mobile/android/app/build.gradle, packages/mobile/ios/App/App.xcodeproj/project.pbxproj, packages/mobile/ios/App/App/Info.plist
Bump mobile project versions to latest release
```
- Updated iOS
- Updated Android
```
- __Desktop__
- __Mobile__
=> chore: bump mobile alpha version

packages/shared/components/AccountNavigation.svelte, packages/shared/components/ActivityDetail.svelte, packages/shared/components/MainMenu.svelte, packages/shared/components/inputs/Checkbox.svelte, packages/shared/components/popups/Index.svelte, packages/shared/routes/dashboard/settings/Settings.svelte, packages/shared/routes/dashboard/wallet/views/AccountAssets.svelte, packages/shared/routes/dashboard/wallet/views/AccountBalance.svelte, packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte, packages/shared/routes/setup/Welcome.svelte
...
```
- style: unify mobile horizontal paddings to `20px`
```
Close #3734
- __Desktop__
- __Mobile__
...
=> style: unify mobile horizontal paddings to `20px`

packages/desktop/electron/preload.js, packages/desktop/package.json
Fix logger, so that it automatically logs if in development mode.
...
```
- fix logger options
```
closes: #3673 
- __Desktop__
- __Mobile__
...
=> fix: initialize logger

.github/workflows/ci.snyk.yml
Using Snyk for every PR wasn't quite as useful as we'd hoped since it was failing every time.
```
- Remove action for pull requests
- Add "stardust-develop" branch to workflow
```
Closes #3744 
- __Desktop__
- __Mobile__
See status checks below.
> Please tick all of the …
=> chore: Snyk CI changes

packages/desktop/tsconfig.json, packages/mobile/tsconfig.json, packages/shared/tsconfig.json
Now that we're using features in our code, we should be importing it more cleanly with a path alias, e.g. `@features`
```
- Add path alias to TS configs for shared, desktop, and mobile
```
_None_
- __Desktop__
- __Mobile__
Try using `@features` 
> Please tick all of the …
=> chore: add path alias for features

packages/shared/lib/contexts/onboarding/actions/initProfileManagerFromNewProfile.ts, packages/shared/lib/contexts/onboarding/actions/setNewProfileClientOptions.ts, packages/shared/lib/core/account/actions/createNewAccount.ts, packages/shared/lib/core/profile-manager/actions/initialiseProfileManager.ts, packages/shared/package.json, packages/shared/routes/login/views/EnterPinView.svelte, yarn.lock
Updated the alpha package of wallet.rs. This contains the changes for the account manager (Breaking Change!) as well as declaration files that fix the test.
...
```
- Updated @iota/wallet
- Added coinType from createAccount to initialiseProfileManager
```
close: #3768 
...
- __Desktop__
- __Mobile__
...
=> fix: update wallet.rs

packages/mobile/android/app/build.gradle
This PR aims to make the application load faster because the libraries are directly loaded from the APK at runtime.
More info at #2572 
Closes #2572 
- __Desktop__
- __Mobile__
...
=> chore: store uncompressed libs on apk

.github/workflows/ci.snyk.yml
...
```
```
...
- __Desktop__
- __Mobile__
...
=> chore: copy ci.snyk.yml onto stardust-develop

packages/shared/components/ActivityDetail.svelte, packages/shared/locales/de.json, packages/shared/locales/en.json
This PR adds a title to the transaction details drawer.
...
```
- Added title to activity detail component
```
Closes #3789
- __Desktop__
- __Mobile__
...
=> chore: add title to transaction details

packages/shared/routes/dashboard/settings/views/SettingsHome.svelte
This PR removes the iota links entry from settings list
```
- Removed iota links from settings list.
```
Closes #3797
- __Desktop__
- __Mobile__
...
=> chore: remove iota links from settings

packages/shared/components/Drawer.svelte
This PR pair the left and bottom drawer animations, plus some animation stores fixes and velocity detection adjust.
- __Desktop__
- __Mobile__
...
=> fix: drawer close animation

packages/shared/components/Illustration.svelte, packages/shared/routes/dashboard/wallet/views/Send.svelte
https://github.com/iotaledger/firefly/issues/3770
```
```
Closes #3770 
- __Desktop__
- __Mobile__
...
=> fix: send screen scroll

packages/mobile/public/index.html
https://github.com/iotaledger/firefly/issues/2321
Closes #2321 
...
- __Desktop__
- __Mobile__
...
=> chore: pair CSP as desktop for beta

packages/mobile/App.svelte, packages/mobile/public/index.html, packages/shared/components/QRScanner.svelte, packages/shared/locales/en.json
This PR aligns the qr code scanners design to the figma layout.
```
- Added locals function to QR scanner
- Added scanner text
- Changed the scanner style
```
Closes #3733 
- __Desktop__
- __Mobile__
...
=> chore: adjust qr code scanner style to figma design

packages/shared/components/popups/DeleteProfile.svelte
Adds spinner in profile deletion
closes #3795
- __Desktop__
- __Mobile__
=> fix: add spinner profile deletion

packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts, packages/shared/package.json
...
```
```
...
- __Desktop__
- __Mobile__
...
=> update: update wallet.rs version alpha 5

packages/shared/locales/en.json, packages/shared/routes/setup/import/views/FileImport.svelte
This PR adapt the import as Figma design
```
- Advance once file is selected.
- Add title as figma
- Adapt button with title as figma
- Update locales 
```
Closes #3793 
- __Desktop__
- __Mobile__
...
=> chore: import Stronghold screen as figma

packages/desktop/package.json
Preparing for a new alpha release.
```
- Change the version in desktop package.json file
```
_None_
- __Desktop__
- __Mobile__
N/a
=> chore: bump alpha version to `0.1.3`

packages/shared/components/organisms/NodeConfigurationForm.svelte, packages/shared/routes/onboarding/OnboardingCustomNetworkView.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: node config inputs

docs/guides/coding-conventions/components.md, docs/guides/coding-conventions/modules.md, docs/retype.yml, docs/specifications/account-activity.md, docs/specifications/modules.md
The handbook is a little out of date, specifically wrt coding conventions.
```
- Update coding conventions for new module sub-directories
- Add specification page for library modules
```
Closes #3917 
- __Desktop__
- __Mobile__
Pull latest from this branch and run `yarn …
=> docs: update spec and coding conventions

packages/shared/components/Drawer.svelte
This PR adds capture and passive options to allow better tap events UX.
More info: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: add capture & passive props to events

packages/mobile/App.svelte, packages/mobile/capacitor/capacitorApi.ts, packages/mobile/package.json, packages/shared/components/popups/ConfirmCloseApp.svelte, packages/shared/components/popups/Index.svelte, packages/shared/locales/en.json, yarn.lock
This PR implement android back button action, preventing the app from close asking with a drawer to exit, or formir going back again.
```
- Look commits ;)
```
Closes #2638 
- __Desktop__
- __Mobile__
...
=> feat: implement android back action

packages/shared/components/QRScanner.svelte
This PR rounds the qr scanners corners
```
- Added tailwind class to round the corners of the scanner
```
...
- __Desktop__
- __Mobile__
...
=> fix: qr scanner corners

packages/backend/bindings/capacitor/ios/Plugin/Plugin.swift
...
Closes [#3855](https://github.com/iotaledger/firefly/issues/3855)
- __Desktop__
- __Mobile__
...
=> fix: capacitor iOS bindings listen & destoy functions

packages/shared/components/ActivityDetail.svelte
Signed-off-by: Amadeo Marchioni <amadeo.marchioni@iota.org>
...
```
```
...
- __Desktop__
- __Mobile__
...
=> chore: add safe-area env to botom button

packages/shared/routes/dashboard/wallet/Wallet.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> chore: close drawer upon send

packages/shared/components/Drawer.svelte, packages/shared/routes/dashboard/wallet/Wallet.svelte, packages/shared/routes/dashboard/wallet/views/Receive.svelte, packages/shared/routes/dashboard/wallet/views/Send.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> chore: pair send & receive drawer design

docs/guides/coding-conventions/errors.md
The error parameters are out of date.
```
- Update the error parameters and annotation comments
```
_None_
- __Desktop__
- __Mobile__
_N/a_
=> docs: update error coding conventions

packages/shared/components/popups/CreateAccount.svelte, packages/shared/components/popups/Password.svelte, packages/shared/components/popups/Transaction.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> chore: center drawer popup titles

packages/shared/components/drawerContent/AccountSwitcher.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: account switcher various

README.md, packages/desktop/README.md, packages/mobile/README.md
The READMEs were slightly outdated.
```
- Changes root README file
- Add platform environment setup guides to mobile and desktop READMEs
```
Closes #3960 
- __Desktop__
- __Mobile__
_N/a_
=> docs: update `README`s

packages/shared/lib/core/network/tests/network.test.ts, packages/shared/lib/tests/__mocks__/account.mock.ts, packages/shared/package.json, yarn.lock
Update wallet.rs version to alpha.10
...
```
- Update wallet.rs version
```
Closes #4004 
...
- __Desktop__
- __Mobile__
...
=> update: walletrs alpha 10

packages/shared/components/inputs/AssetDropdown.svelte
Fix from asset send:
-  squished icon
- displayed name/id truncation
```
fix: send asset dropdown squished icon and truncate
```
Close #4033
- __Desktop__
- __Mobile__
...
=> fix: send asset dropdown squished icon and truncate

packages/shared/components/popups/MintNativeTokenFormPopup.svelte
There was an error in the validation, because the input fields return a string the expected number was not being check properly in the operations. I.e. greater than sign was comparing alphabetically.
```
- Cast strings to number in validation of minting form
```
...
- __Desktop__
- __Mobile__
> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ that your changes …
=> fix: validation of minting

packages/shared/components/popups/TokenInformationPopup.svelte
fix: title of `TokenInfoPopup` for long asset names
```
fix: title of TokenInfoPopup for long asset names
```
Close #4046
- __Desktop__
- __Mobile__
...
=> fix: title of `TokenInfoPopup` for long asset names

packages/shared/components/atoms/tiles/ActivityTile.svelte, packages/shared/components/atoms/tiles/AssetTile.svelte, packages/shared/components/molecules/AssetIcon.svelte
This is to show the native token on the asset tiles
```
- Use AssetIcon on the ActivityTile
- Add option to only show verification  badge and not other badges to the AssetIcon
- Truncate minted asset name if its too long
```
...
- __Desktop__
- __Mobile__
...
> Please tick all …
=> enhancement: activity tile for native tokens

packages/shared/components/atoms/tiles/ActivityTile.svelte, packages/shared/components/inputs/AssetDropdown.svelte, packages/shared/components/molecules/AssetIcon.svelte, packages/shared/components/organisms/AccountActivity.svelte, packages/shared/components/popups/ActivityDetailsPopup.svelte, packages/shared/components/popups/TokenInformationPopup.svelte, packages/shared/lib/core/profile-manager/api/events/newOutput.ts, packages/shared/lib/core/wallet/actions/hideActivitiesForHiddenAssets.ts, packages/shared/lib/core/wallet/actions/loadAccountActivities.ts, packages/shared/lib/core/wallet/actions/loadAccountActivitiesFromOutputs.ts, packages/shared/lib/core/wallet/actions/loadAccountActivitiesFromTransactions.ts, packages/shared/lib/core/wallet/actions/mintNativeToken.ts, packages/shared/lib/core/wallet/actions/sendOutput.ts, packages/shared/lib/core/wallet/classes/activity.class.ts, packages/shared/lib/core/wallet/interfaces/activity.interface.ts, packages/shared/locales/en.json
This pr adds some fixers to the activities so that if we receive a token that needs claiming that we have never seen before we will pull in the metadata. It also asks the user to verify the metadata if it is a new token when they click on an activity.
```
- Only store asset id in activity so the rest can be reactive
- Add token information popup before activity popup if token is new
- Update activity builders to also try and get the asset metadata if its never been added
```
...
> Please …
=> enhancement: claim / view flow of unknown tokens

packages/shared/components/molecules/TransactionDetails.svelte
Add asset icon to transaction details
```
- Add asset icon to transaction details
```
Closes #3946 
- __Desktop__
- __Mobile__
...
=> update: native tokens in transaction popup

packages/backend/bindings/node/index.ts, packages/mobile/capacitor/walletPluginApi.ts, packages/shared/lib/typings/account.ts, packages/shared/lib/typings/walletApi.ts, packages/shared/lib/wallet.ts, packages/shared/routes/dashboard/wallet/Wallet.svelte, packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
Fixes gap limit in all scenarios and ensures Ledger profiles restore all wallets after logging out and restoring a profile
...
```
- Fix gap limit for background syncing
- Fix gap limit for account syncing
- Fix gap limit for manual sync
- Reset account syncing queue on logout
- Styling fixes
```
- __Desktop__
- __Mobile__
Test various wallet creation, restore, login and sync scenarios
=> fix: gap limits and syncing logic

packages/mobile/App.svelte, packages/mobile/package.json, packages/shared/routes/dashboard/Dashboard.svelte, yarn.lock
...
```
```
Closes #3348 
- __Desktop__
- __Mobile__
...
=> fix: top status bar mobile issues

packages/shared/lib/participation/staking.ts, packages/shared/lib/wallet.ts, packages/shared/lib/walletApiListeners.ts, packages/shared/routes/dashboard/Dashboard.svelte, packages/shared/routes/dashboard/wallet/Wallet.svelte
Fixes duplication of accounts on profile restoration and fixes asset display on restore
...
```
- Updates account update logic on balance change
- Force rerender of asset tile on staking cache completion
- Only cache assets on first session sync
```
- __Desktop__
- __Mobile__
=> fix: syncing issues

packages/shared/lib/core/wallet/actions/linkActivityAndClaimingTransaction.ts, packages/shared/lib/core/wallet/classes/activity.class.ts, packages/shared/lib/core/wallet/interfaces/activity.interface.ts
Save transactions input into activity 
```
- save transactions input into activity
```
Closes #4096 
Closes #4098 
- __Desktop__
- __Mobile__
...
=> fix: claimed activities still claimable

packages/shared/components/atoms/tiles/AssetTile.svelte, packages/shared/components/inputs/AssetAmountInput.svelte, packages/shared/components/inputs/AssetDropdown.svelte
...
```
- Increase max height
- Add squished variant to assettile
- Use squished variant in asset dropdown
- Dont reset amount when asset changes
```
...
- __Desktop__
- __Mobile__
...
=> enhancement: improve asset dropdown

packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
Activity groups appear in random order. This PR fixes it by introducing a default ordering to the activity list 
```
- add sorting to activity list
```
Closes #4130 
- __Desktop__
- __Mobile__
...
=> fix: ordering of activity list grouping

packages/shared/lib/core/wallet/interfaces/filter.interface.ts, packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts, packages/shared/lib/core/wallet/utils/isFilteredActivity.ts, packages/shared/locales/en.json
Add filter options for status and type for activities.
```
- add type filter to activities
- add status filter to activities
```
Closes #4151 
- __Desktop__
- __Mobile__
...
=> enhancement: status and type filter

packages/shared/components/filters/FilterItem.svelte, packages/shared/lib/auxiliary/icon/constants/icon-svg.ts, packages/shared/lib/auxiliary/icon/enums/icon.enum.ts, packages/shared/lib/auxiliary/icon/svgs/arrow-right.svg.ts, packages/shared/lib/auxiliary/icon/svgs/index.ts, packages/shared/lib/core/wallet/interfaces/filter.interface.ts, packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts, packages/shared/lib/core/wallet/stores/selected-account-assets.store.ts, packages/shared/lib/core/wallet/utils/isFilteredActivity.ts, packages/shared/locales/en.json
A new filter is added, such that the user can filter their activities with different conditions regarding its amount.
```
- Add amount filter component
- filter activities by amount
```
Closes #4153 
- __Desktop__
- __Mobile__
...
=> enhancement: amount filter

packages/shared/routes/dashboard/settings/views/advanced/NetworkConfiguration.svelte, packages/shared/routes/login/views/EnterPinView.svelte
There was an issue where a piece of code was causing the nodes of the client options to be removed. This fix aims to prevent that and recover profiles from that issue where it happened.
```
- Remove code that was causing nodes to disapear
- Recover profile using default nodes
```
...
- __Desktop__
- __Mobile__
> Please describe the specific instructions, configurations, and/or test cases necessary to __test and verify__ …
=> fix: login issue client missing node

packages/shared/components/molecules/AssetList.svelte, packages/shared/components/organisms/AccountActivity.svelte
If  a virtual list wasnt scrollable, the padding didnt match the design
```
- move scrollbar to outer div
```
Closes #4161 
- __Desktop__
- __Mobile__
...
=> ui: fix padding on asset list

packages/desktop/package.json
...
```
- Increment version numbers
```
...
- __Desktop__
- __Mobile__
...
=> chore: merge desktop 2.0.0 alpha/beta 3 into `stardust-develop`

packages/shared/components/atoms/tiles/ActivityTile.svelte, packages/shared/components/filters/FilterItem.svelte, packages/shared/components/popups/ActivityDetailsPopup.svelte, packages/shared/lib/core/wallet/actions/index.ts, packages/shared/lib/core/wallet/actions/rejectActivity.ts, packages/shared/lib/core/wallet/classes/activity.class.ts, packages/shared/lib/core/wallet/interfaces/activity.interface.ts, packages/shared/lib/core/wallet/interfaces/filter.interface.ts, packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts, packages/shared/lib/core/wallet/stores/selected-account-assets.store.ts, packages/shared/lib/core/wallet/utils/isFilteredActivity.ts, packages/shared/lib/core/wallet/utils/isFilteredAsset.ts, packages/shared/locales/en.json
Add filter to show the rejected activities
```
- Add filter to show the rejected activities
- Update boolean filter to show a Yes/No dropdown
```
Closes #4172 
- __Desktop__
- __Mobile__
...
=> enhancement: add show rejected filter

packages/shared/components/filters/FilterItem.svelte, packages/shared/components/inputs/AssetDropdown.svelte, packages/shared/components/inputs/Dropdown.svelte, packages/shared/components/molecules/AssetList.svelte, packages/shared/components/organisms/AccountActivity.svelte, packages/shared/components/popups/TokenInformationPopup.svelte, packages/shared/lib/core/wallet/actions/getAccountAssetsForSelectedAccount.ts, packages/shared/lib/core/wallet/interfaces/filter.interface.ts, packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts, packages/shared/lib/core/wallet/stores/selected-account-assets.store.ts, packages/shared/lib/core/wallet/utils/isFilteredActivity.ts, packages/shared/locales/en.json
Add a filter option to the activities for filtering them regarding their token
```
- add asset filter
```
Closes #4154 
- __Desktop__
- __Mobile__
...
=> enhancement: add asset filter

packages/shared/components/AccountNavigation.svelte, packages/shared/components/MainMenu.svelte, packages/shared/components/popups/Index.svelte, packages/shared/lib/core/router/router.ts, packages/shared/lib/profile.ts, packages/shared/routes/dashboard/wallet/Wallet.svelte, packages/shared/routes/login/views/SelectProfile.svelte, packages/shared/routes/setup/Welcome.svelte
This PR aims to add missing conditional chaining and fix an undefined object deconstruction which lead to crashes in desktop. 
In order to test sometimes I need to run desktop to compare both platforms and before desktop wasnt able to run.
```
- fix: add missing conditional chaining 
```
...
- __Desktop__
- __Mobile__
> Please describe the specific instructions, configurations, and/or test cases necessary to __test and …
=> fix: add missing conditional chaining 

packages/shared/package.json, yarn.lock
Update wallet-rs to v2.0.2-alpha.16
N/A
https://github.com/iotaledger/firefly/issues/4259
- __Desktop__
- __Mobile__
=> chore: update wallet-rs to v2.0.2-alpha.16

packages/mobile/capacitor.config.ts
...
```
```
...
- __Desktop__
- __Mobile__
...
=> chore: change capacitor logging behavior

packages/shared/components/popups/AddNode.svelte, packages/shared/components/popups/Index.svelte, packages/shared/components/popups/NodeConfigOptions.svelte, packages/shared/routes/dashboard/settings/views/advanced/NetworkConfiguration.svelte
This PR aims to fix 2 things:
- trying to manually enter a wrong node url refreshed the app, fixes #4268
- node options where not available, this PR adds them (please note that there is some code duplication added because drawers inside drawers are not working as expected for me in mobile so i had to create a new popup)
```
feat: add mobile nodes configuration options
```
...
- __Desktop__
- __Mobile__
> Please describe the …
=> feat: add mobile nodes configuration options

packages/shared/package.json
Updates wallet.rs version to alpha.19. This PR should improve the size of the nodemodules and the build speed drastically
```
- update wallet.rs
```
...
- __Desktop__
- __Mobile__
...
=> update: wallet rs 19

packages/shared/lib/core/profile-manager/api/recoverAccounts.ts, packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts, packages/shared/lib/tests/__mocks__/profile-manager.mock.ts, yarn.lock
… bindings
This PR fixes a mismatched API method signature.
```
- Add syncOptions parameter to recoverAccounts API method
- Change wrapped method
- Update main lock file
```
Closes #4310 
- __Desktop__
- __Mobile__
Test recovering accounts and finding balance.
> Please tick all …
=> chore: update API typings

packages/shared/components/OnboardingLayout.svelte, packages/shared/routes/setup/legal/Legal.svelte
This PR fixes all styling issues of the privacy policy and terms of service view
```
- Changes text padding
- Removes title overlapping through scrolling
```
Closes #4312
- __Desktop__
- __Mobile__
...
=> fix: privacy policy and terms of service view

packages/shared/routes/dashboard/wallet/views/Receive.svelte
...
```
```
Closes #4355
- __Desktop__
- __Mobile__
...
=> fix: tap to copy address not working

packages/shared/routes/dashboard/wallet/views/AccountAssets.svelte
closes #4360
- __Desktop__
- __Mobile__
=> feat: adds sync spinner on the AccountAssets

packages/shared/routes/setup/backup/views/Backup.svelte, packages/shared/routes/setup/protect/views/Pin.svelte, packages/shared/routes/setup/protect/views/RepeatPin.svelte
closes #4371
- __Desktop__
- __Mobile__
=> fix: disable keyboard autofocus on setup

packages/shared/routes/dashboard/Dashboard.svelte, packages/shared/routes/dashboard/settings/views/SettingsViewer.svelte
...
```
```
Close #4391
- __Desktop__
- __Mobile__
...
=> fix: mobile language change reactivity

packages/shared/components/popups/SwitchNetwork.svelte
...
```
```
Closes #4405 
- __Desktop__
- __Mobile__
...
=> fix: switch network drawer adapt to input

packages/shared/components/popups/Transaction.svelte, packages/shared/routes/dashboard/wallet/views/Send.svelte
closes #4389
- __Desktop__
- __Mobile__
=> fix: add correct spacing between cta buttons in send drawer

packages/desktop/App.svelte, packages/shared/components/TransactionTabs.svelte, packages/shared/components/inputs/AssetDropdown.svelte, packages/shared/components/inputs/Dropdown.svelte, packages/shared/components/inputs/Dropdown2.svelte, packages/shared/components/inputs/ImportTextfield.svelte, packages/shared/components/molecules/AssetList.svelte, packages/shared/components/molecules/ShimmerClaimingAccountList.svelte, packages/shared/components/organisms/AccountActivity.svelte, packages/shared/routes/login/views/SelectProfileView.svelte, packages/shared/routes/onboarding/views/app-setup/views/LegalView.svelte
This PR simplifys the styles of the scroll bar and removes older styles that are not needed.
```
- Simplify scroll styles
- Add overlay scroll class
- Removed border from scroll
- Remove use of old classes
- Only show scroll on hover
```
...
- __Desktop__
- __Mobile__
...
> …
=> refactor: simplify scroll styles and remove old styles

packages/shared/package.json, yarn.lock
...
```
```
...
- __Desktop__
- __Mobile__
...
=> chore: update @iota/wallet to 2.0.2-alpha.23

packages/shared/components/popups/AirdropNetworkInfo.svelte, packages/shared/components/popups/AirdropNetworkWarning.svelte
...
```
```
Closes #4470 
- __Desktop__
- __Mobile__
...
=> chore: adjust top paddings

packages/shared/routes/dashboard/settings/views/SettingsHome.svelte
This PR sets the right issue report url
...
```
```
Closes #4469 
- __Desktop__
- __Mobile__
...
=> fix: wrong url for issue report

packages/shared/components/atoms/iconButtons/index.js
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: remove leftover import

packages/desktop/electron-builder-config.js, packages/desktop/package.json, packages/desktop/scripts/fix-productName.js, packages/desktop/webpack.config.js
For launch of shimmer the app will be called Firefly Shimmer to make it easier to find.
```
- Change app name to "Firefly Shimmer" in all relevant instances
```
Closes #4549 
- __Desktop__
- __Mobile__
...
> Please tick all of the following boxes that are relevant to your …
=> chore: change app name to "Firefly Shimmer"

packages/shared/lib/core/account/utils/getIconColorFromString.ts
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: remove gray from potential icon colours

packages/shared/components/filters/Filter.svelte, packages/shared/components/filters/FilterItem.svelte
Implement accordeon behavior for filters
```
- Implement accordeon behavior for filters
```
Closes #4569 
- __Desktop__
- __Mobile__
...
=> ui: filter accordeon

packages/shared/lib/contexts/onboarding/actions/findShimmerRewards.ts, packages/shared/lib/contexts/onboarding/helpers/getSortedRenamedBoundAccounts.ts, packages/shared/lib/core/profile-manager/api/recoverAccounts.ts, packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts, packages/shared/lib/core/profile/actions/active-profile/login.ts, packages/shared/lib/tests/__mocks__/profile-manager.mock.ts, packages/shared/routes/onboarding/views/shimmer-claiming/views/ClaimRewardsView.svelte
Bug was originally due to breaking change from `wallet-rs`.
```
- Change recoverAccounts function signature to match that of wallet-rs
- Add some void keywords for promises
```
Closes #4632 
- __Desktop__
- __Mobile__
... …
=> chore: fix `NaN` issue with Shimmer claiming flow

packages/shared/locales/en.json, packages/shared/routes/onboarding/views/profile-recovery/views/BackupPasswordView.svelte, packages/shared/routes/onboarding/views/storage-protection-setup/views/SetupPinProtectionView.svelte
UX was suffering in some onboarding views.
```
- Add spinners to improve UX of some onboarding views
```
Closes #4416 
- __Desktop__
- __Mobile__
...
=> enhancemnet: add spinners to specific onboarding views

packages/shared/components/Drawer.svelte, packages/shared/components/popups/BalanceFinder.svelte, packages/shared/routes/dashboard/settings/views/advanced/BalanceFinder.svelte
...
```
```
Closes #4471
- __Desktop__
- __Mobile__
...
=> fix: allow popup swipe for balance finder

packages/shared/lib/core/profile/constants/initial-address-gap-limit.constant.ts
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: recover account gap limit

packages/shared/routes/onboarding/views/network-setup/views/ChooseProtocolView.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: reset active profile in onboarding

packages/shared/lib/contexts/settings/constants/documentation-url.constant.ts, packages/shared/lib/contexts/settings/constants/faq-url.constant.ts
update doc and faq links
```
- update doc link
- update faq link
```
Closes #4665 
- __Desktop__
- __Mobile__
...
=> chore: update doc and faq links

packages/shared/components/inputs/AssetAmountInput.svelte
dont reset unit after go from send confirmation back to send form
```
- dont reset unit after go from send confirmation back to send form
```
Closes #4684 
- __Desktop__
- __Mobile__
...
=> fix: unit resets after back

packages/shared/components/atoms/MenuItem.svelte, packages/shared/components/modals/ExpirationTimePickerMenu.svelte
Enhances the expiration date picker menu by changing its date format display from long to medium and by adding margin to the checkmark icon when an item is selected
closes #4644
- __Desktop__
- __Mobile__
=> enhancement: expiration date picker menu

.github/workflows/build-desktop.yml
Removes S3 and Cloudfront steps because the website download link will request GitHub file
Changes prerelease variable in the 'Create Release' step to always true
```
- removes S3 and Cloudfront steps
- changes prerelease variable in the 'Create Release' step to always true
```
closes #3394
=> fix: stardust build workflow

packages/shared/components/popups/MintNativeTokenFormPopup.svelte, packages/shared/locales/en.json
closes #4707 
- __Desktop__
- __Mobile__
=> fix: mint native token form tooltip text

packages/shared/components/popups/ActivityDetailsPopup.svelte
closes #4703
- __Desktop__
- __Mobile__
=> fix: hide expiration time on claimed activity popup

packages/shared/components/popups/FaucetRequestPopup.svelte, packages/shared/components/popups/LegalUpdate.svelte, packages/shared/components/popups/MintNativeTokenFormPopup.svelte, packages/shared/components/popups/SendConfirmationPopup.svelte, packages/shared/components/popups/SendFormPopup.svelte, packages/shared/components/popups/TestDeepLinkFormPopup.svelte, packages/shared/components/popups/TokenInformationPopup.svelte, packages/shared/routes/onboarding/views/CongratulationsView.svelte, packages/shared/routes/onboarding/views/profile-backup/views/BackupMnemonicView.svelte, packages/shared/routes/onboarding/views/profile-backup/views/VerifyMnemonicView.svelte, packages/shared/routes/onboarding/views/shimmer-claiming/views/SuccessView.svelte
Removes autofocus in all buttons as it is not a good feature for accessibility
closes #4704 
- __Desktop__
- __Mobile__
=> fix: remove autofocus all buttons

packages/shared/components/popups/ActivityDetailsPopup.svelte
closes #4702 
- __Desktop__
- __Mobile__
=> fix: changes from native button to Button component in ActivityDetailsPopup

packages/mobile/capacitor/plugins/secure-filesystem-access/android/src/main/java/org/iota/plugins/securefilesystemaccess/SecureFilesystemAccessPlugin.java
...
```
```
Close #4533
- __Desktop__
- __Mobile__
...
=> fix: multi import stronghold android

packages/shared/components/popups/LedgerAppGuidePopup.svelte, packages/shared/locales/en.json, packages/shared/routes/onboarding/views/ledger-setup/views/LedgerInstallationGuideView.svelte
Updates Ledger strings for Shimmer claiming
...
```
- Updates strings
```
- __Desktop__
- __Mobile__
...
=> feat: ledger claim strings

packages/shared/components/popups/Transaction.svelte, packages/shared/lib/app.ts, packages/shared/lib/common/deep-links/types/deep-link-request.type.ts, packages/shared/lib/common/deep-links/types/wallet-context.type.ts, packages/shared/lib/common/deep-links/wallet-context-handler.ts, packages/shared/lib/typings/sendParams.ts, packages/shared/lib/utils.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/wallet/Wallet.svelte, packages/shared/routes/dashboard/wallet/views/Send.svelte
Updated the confirmation popup and passed the deep link to be sent. Firefly v1 is now compatible with multichain deeplinks. I'll create separate PR to fix the design issues.
...
```
- Updated confirmation popup
- Passed indexation payload correctly
- Added string to utf-8 conversion
```
closes: #4545 
...
- __Desktop__
- __Mobile__
...
=> feat: adjust confirmation page

packages/desktop/package.json
Same as #4197
```
```
Close #4793
- __Desktop__
- __Mobile__
...
=> chore: add `--no-sandbox` to electron start script

packages/shared/components/modals/AccountActionsMenu.svelte, packages/shared/components/molecules/menu-items/AccountSwitcherMenuItem.svelte, packages/shared/components/organisms/AccountSummary.svelte, packages/shared/components/popups/AliasConfirmationPopup.svelte, packages/shared/components/popups/MintNativeTokenFormPopup.svelte, packages/shared/components/popups/SendConfirmationPopup.svelte, packages/shared/components/popups/TestDeepLinkFormPopup.svelte, packages/shared/lib/core/account/actions/buildAccountState.ts, packages/shared/lib/core/account/interfaces/account-state.interface.ts, packages/shared/lib/core/profile/actions/active-accounts/findActiveAccountWithAddress.ts, packages/shared/lib/core/profile/actions/active-accounts/index.ts, packages/shared/lib/core/profile/actions/resetDashboardState.ts, packages/shared/lib/core/wallet/actions/mintNativeToken.ts, packages/shared/lib/core/wallet/actions/sendOutput.ts, packages/shared/lib/core/wallet/utils/getSubjectFromAddress.ts, packages/shared/lib/wallet.ts
Remove lib/wallet file and move contents
```
```
...
- __Desktop__
- __Mobile__
...
=> refactor: clean up lib/wallet

packages/shared/lib/address.ts, packages/shared/lib/common/deep-links/wallet-context-handler.ts, packages/shared/lib/tests/address.test.ts
Validate input fields for bridge transaction
```
- Add validation for chain ID
- Add validation for receiver address
```
closes: #4792 
...
- __Desktop__
- __Mobile__
...
=> feat: validate input fields

packages/mobile/components/OnboardingLayout.svelte, packages/mobile/components/buttons/ProfileButton.svelte, packages/mobile/routes/login/views/EnterPinView.svelte, packages/mobile/routes/login/views/SelectProfileView.svelte, packages/mobile/routes/onboarding/views/CongratulationsView.svelte, packages/mobile/routes/onboarding/views/app-setup/views/WelcomeView.svelte, packages/mobile/routes/onboarding/views/profile-backup/views/VerifyMnemonicView.svelte, packages/mobile/routes/onboarding/views/profile-backup/views/ViewMnemonicView.svelte, packages/mobile/routes/onboarding/views/profile-setup/views/EnterNameView.svelte, packages/mobile/routes/onboarding/views/storage-protection-setup/views/SetupPinProtectionView.svelte, packages/mobile/routes/onboarding/views/stronghold-setup/views/SetupStrongholdPasswordView.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> refactor: cleanup TextTypes

packages/mobile/routes/login/LoginRouter.svelte, packages/mobile/routes/onboarding/OnboardingRouter.svelte, packages/mobile/routes/onboarding/views/app-setup/AppSetupRouter.svelte, packages/mobile/routes/onboarding/views/network-setup/NetworkSetupRouter.svelte, packages/mobile/routes/onboarding/views/profile-backup/ProfileBackupRouter.svelte, packages/mobile/routes/onboarding/views/profile-setup/ProfileSetupRouter.svelte, packages/mobile/routes/onboarding/views/storage-protection-setup/StorageProtectionSetupRouter.svelte, packages/mobile/routes/onboarding/views/stronghold-setup/StrongholdSetupRouter.svelte
...
```
```
Close #4801
- __Desktop__
- __Mobile__
...
=> refactor: remove mobile routes transitions

docs/retype.yml, packages/desktop/package.json, packages/shared/features/onboarding.features.ts
...
```
```
...
- __Desktop__
- __Mobile__
...
=> chore: merge `release/desktop-2.0.1-beta-1` into `stardust-develop`

packages/mobile/App.svelte, packages/mobile/lib/core/router/dashboard-router.ts, packages/mobile/lib/core/router/enums/dashboard-route.enum.ts, packages/mobile/lib/core/router/enums/index.ts, packages/mobile/routes/dashboard/DashboardRouter.svelte, packages/mobile/routes/dashboard/index.js, packages/mobile/routes/index.js
Copy of https://github.com/iotaledger/firefly/pull/4917
```
```
...
- __Desktop__
- __Mobile__
...
=> feat: setup dashboard router for mobile stardust

packages/mobile/components/ActivityList.svelte, packages/mobile/components/ActivityTile.svelte, packages/mobile/components/index.js, packages/mobile/features/features.ts, packages/mobile/routes/dashboard/wallet/tabs/ActivityTab.svelte
This PR adds the activity list tab to mobile and enables the feature
Filtering is not yet added nor clicks are yet added, this is presentational only for now
```
feat: add mobile activity list
```
Close #4941
- __Desktop__
- __Mobile__
In order to test, you have to:
- in …
=> feat: add mobile activity list

packages/shared/components/ActivityRow.svelte, packages/shared/lib/wallet.ts
Backport for bug fixed in https://github.com/iotaledger/firefly/pull/5076
...
```
- Correct sender/recipient shown for transaction detail
```
closes: https://github.com/iotaledger/firefly/issues/4521
- __Desktop__
- __Mobile__
...
=> fix: correct recipient address

packages/mobile/components/ColorPicker.svelte, packages/mobile/views/dashboard/drawers/account-switcher/views/CreateAccount.svelte
This PR fixes wrong import paths for utils functions
```
- fixes wrong import paths for utils functions
```
...
- __Desktop__
- __Mobile__
...
=> fix: stardust mobile utils imports

packages/shared/lib/participation/constants.ts, packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> chore: update for next Assembly staking period

packages/shared/locales/en.json
...
```
```
...
- __Desktop__
- __Mobile__
...
=> chore: cleanup locale debris

packages/shared/lib/common/deep-links/wallet-context-handler.ts, packages/shared/locales/en.json
Reverted address validation to parse send operation
...
```
- Added explicit check for no address validation
```
...
- __Desktop__
- __Mobile__
...
=> chore: move address validation to send address

packages/desktop/package.json, packages/shared/lib/participation/constants.ts
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: update event

packages/shared/lib/auxiliary/popup/stores/popup-state.store.ts
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: fix update popup props function

packages/shared/components/inputs/RecipientInput.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: filter selected wallet from recipient input

packages/desktop/App.svelte, packages/desktop/lib/routers/actions/goToAppContext.ts, packages/desktop/lib/routers/actions/index.ts, packages/desktop/lib/routers/helpers/getAppRouteForContext.ts, packages/desktop/lib/routers/helpers/index.ts, packages/desktop/lib/routers/utils/getAppRouter.ts, packages/desktop/lib/routers/utils/index.ts, packages/desktop/views/login/views/SelectProfileView.svelte, packages/shared/lib/contexts/onboarding/actions/initialiseOnboardingFlow.ts, packages/shared/lib/contexts/settings/actions/deleteProfile.ts, packages/shared/lib/core/router/enums/router-manager-extension-name.enum.ts, packages/shared/lib/core/router/interfaces/router-manager.interface.ts
The contexts modules contain routing logic, and they shouldn't.
```
```
Closes #5142
- __Desktop__
- __Mobile__
Test general app functionality.
=> refactor: remove routing logic for `context` modules

packages/desktop/electron/main.js
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: remove persistence of app window position

packages/shared/components/Text.svelte, packages/shared/components/inputs/ClosableInput.svelte, packages/shared/components/inputs/Input.svelte, packages/shared/components/inputs/InputContainer.svelte, packages/shared/components/inputs/NumberInput.svelte, packages/shared/components/inputs/TextInput.svelte, packages/shared/components/molecules/SelectorInput.svelte
...
```
- Added slots to input for different locations of components
- Added value to right input slot if key exists in selected option
```
...
- __Desktop__
- __Mobile__
...
=> enhancement: show key and value in selector

packages/shared/components/inputs/NftInput.svelte, packages/shared/components/molecules/NftMediaContainer.svelte, packages/shared/components/molecules/SelectorInput.svelte
Add icon to nft selector
```
- add icon to nft selector
```
Closes #5191 
- __Desktop__
- __Mobile__
...
=> enhancement: add icon to nft selector

packages/shared/components/popups/ActivityDetailsPopup.svelte
...
```
- pass subject as a prop to activity details
```
Closes #5185 
- __Desktop__
- __Mobile__
...
=> fix: subject not shown on activity details

packages/shared/components/popups/MintNftConfirmationPopup.svelte, packages/shared/components/popups/MintNftFormPopup.svelte, packages/shared/lib/core/nfts/constants/current-irc27-version.constant.ts, packages/shared/lib/core/nfts/constants/index.ts, packages/shared/lib/core/utils/validation.ts, packages/shared/lib/core/wallet/actions/mintNft.ts
General fixes for minting nft related issues
```
- Add deposit address as immutable issuer
- Show actual mint details on the confirmation page
- Add version to the IRC27 metadata
- Validate URI as uri not web url
- Add nft to store after minting
```
...
- __Desktop__
- __Mobile__
...
=> fix: fixes for minting NFT related issues

packages/mobile/App.svelte, packages/mobile/components/QRScanner.svelte, packages/mobile/lib/routers/actions/goToAppContext.ts, packages/mobile/lib/routers/actions/index.ts, packages/mobile/lib/routers/actions/initialiseRouters.ts, packages/mobile/lib/routers/actions/resetRouterForAppContext.ts, packages/mobile/lib/routers/actions/resetRouters.ts, packages/mobile/lib/routers/helpers/getAppRouteForContext.ts, packages/mobile/lib/routers/helpers/index.ts, packages/mobile/lib/routers/index.ts, packages/mobile/lib/routers/utils/getAppRouter.ts, packages/mobile/lib/routers/utils/getRouterForAppContext.ts, packages/mobile/lib/routers/utils/getSubroutersForAppContext.ts, packages/mobile/lib/routers/utils/index.ts, packages/mobile/views/dashboard/DashboardView.svelte
After the latest shared and desktop refactors around the routers, mobile has stopped working. See refactors in #5200 & #5146
This PR aims to adapt the mobile package to work with the new arquitecture 
```
- refactor: adapt mobile routers 
```
...
You can use branch `dev-mode/mobile-stardust` for testing purposes.
From the root of the repo in this PR's branch `refactor/mobile-routers-after-refactor` you can do:
```
git diff origin/dev-mode/mobile-stardust > branch.diff
git apply --reverse …
```
=> refactor: adapt mobile routers 

packages/shared/lib/core/wallet/utils/generateActivity/generateAliasActivity.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateFoundryActivity.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateNftActivity.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateTransactionActivity.ts, packages/shared/lib/core/wallet/utils/generateActivity/helper/getAsyncDataFromOutput.ts
Keep rejected activities hidden after logout -> login
```
- Keep rejected activities hidden after logout -> login
```
Closes #5279 
- __Desktop__
- __Mobile__
...
=> fix: fix shown rejected activities

packages/mobile/views/dashboard/drawers/activity/views/ActivityDetails.svelte
This PR adds the activity details for foundries, aliases and NFTs.
I also added the NTF details even though the component still needs optimization for mobile usage.
```
- Adds activity details for foundries, aliases and NFTs
```
Closes #5249 
Closes #5248
- __Desktop__
- __Mobile__
...
=> feat-mobile: add activity details for foundries, aliases and NFTs

packages/desktop/components/AccountActivity.svelte, packages/desktop/views/dashboard/collectibles/Collectibles.svelte, packages/desktop/views/dashboard/collectibles/views/GalleryView.svelte, packages/shared/components/inputs/TogglableButton.svelte, packages/shared/components/molecules/NftGalleryItem.svelte, packages/shared/components/molecules/NftMediaContainer.svelte, packages/shared/locales/en.json
This PR updates the current implementation of the GalleryView to the figma designs.
```
- add NFT amount to title
- fix font size and weights of title + nft names
- fix border + bg color of nft items
- fix some margins
```
Closes #3442 
- __Desktop__
- __Mobile__
...
=> enhancement: improve gallery view UI

packages/shared/tailwind.config.js
...
```
```
Close https://github.com/iotaledger/firefly/issues/5324
- __Desktop__
- __Mobile__
...
=> fix: tailwind purge

packages/desktop/views/dashboard/Sidebar.svelte
Added governance feature flag
...
```
- Add governance feature flag
```
close: #5263 
...
- __Desktop__
- __Mobile__
...
=> feat: add governance feature flag

packages/shared/components/atoms/tiles/tileContents/NftActivityTileContent.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> enhancement: nft name on activity tile 

packages/shared/components/molecules/NftActivityDetails.svelte, packages/shared/components/molecules/NftMediaContainer.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> enhancement: nft activity summary

.github/workflows/build-desktop.yml
Fix build for macOS
...
```
- Set MACOSX_DEPLOYMENT_TARGET to 10.14
```
- __Desktop__
- __Mobile__
...
=> fix: build on mac os 14

packages/mobile/views/dashboard/drawers/token/TokenDrawer.svelte, packages/mobile/views/dashboard/drawers/token/views/TokenInformation.svelte, packages/shared/components/popups/MintNativeTokenConfirmationPopup.svelte, packages/shared/components/popups/TokenInformationPopup.svelte
Use the correct enum value
```
- Use the correct enum value
```
Closes #5380 
- __Desktop__
- __Mobile__
...
=> fix: fix asset actions not displayed

packages/shared/components/atoms/boxes/KeyValueBox.svelte, packages/shared/components/inputs/SliderInput.svelte, packages/shared/components/popups/BurnNativeTokensConfirmationPopup.svelte, packages/shared/components/popups/BurnNativeTokensPopup.svelte, packages/shared/components/popups/Index.svelte
This PR introduces a Confirmation popup for burning native tokens
```
- add BurnNativeTokenConfirmationPopup
```
Closes #5350 
- __Desktop__
- __Mobile__
...
=> enhancement: burn confirmation popup

packages/shared/lib/core/governance/interfaces/participation.interface.ts
Changes index signature parameters types in IParticipations to string to fix the building fail
- __Desktop__
- __Mobile__
=> fix: change index signature parameter types in IParticipations

packages/shared/lib/core/app/utils/openUrlInBrowser.ts
...
```
```
...
- __Desktop__
- __Mobile__
...
=> fix: audit fixes for url whitelist

packages/shared/components/atoms/tiles/ActivityTile.svelte
...
```
```
...
- __Desktop__
- __Mobile__
...
=> ui: animate pending activity tile

packages/shared/lib/core/layer-2/constants/network-address.constant.ts
Updated the l2 network address to the latest address
...
```
- Changed l2 address
```
...
- __Desktop__
- __Mobile__
...
=> fix: update network address

packages/shared/components/popups/MintNftFormPopup.svelte, packages/shared/locales/en.json
add uri info on nft mint form
```
- add uri info on nft mint form
```
Closes #5459 
- __Desktop__
- __Mobile__
...
=> enhancement: add uri info on nft mint form

packages/mobile/App.svelte
...
```
fix-mobile: refresh views on locale change
```
Close https://github.com/iotaledger/firefly/issues/5106
- __Desktop__
- __Mobile__
...
=> fix-mobile: refresh views on locale change

packages/mobile/components/inputs/RecipientInput.svelte, packages/mobile/views/dashboard/drawers/send/views/RecipientView.svelte
Add recipient quick list 
```
```
Close #5015
- __Desktop__
- __Mobile__
...
=> feat-mobile: add recipient quick list

.github/pull_request_template.md, .github/workflows/ci.snyk.yml, .github/workflows/crowdin.yml, .github/workflows/handbook.yml, README.md
Some files need updating now that our main branches have been renamed.
```
- Rename YML files accordingly 
- Update README accordingly
- Update pull request template
```
- __Desktop__
- __Mobile__
N/a
=> chore: update files after branch rename

docs/guides/git/branches.md, docs/guides/git/pull-requests.md
Update some outdated information.
```
Added information around protected branches.
```
- __Desktop__
- __Mobile__
=> chore: update documentation

packages/desktop/components/SidebarTab.svelte, packages/shared/components/PingingBadge.svelte, packages/shared/components/ProposalAnswer.svelte
Adds the pinging badge to the proposal answer that is being actively voted
```
- Adds prop classes to PingingBadge.svelte
- Remove specific positioning classes in PingingBadge.svelte
- Adds specific positioning classes to PingingBadge in SidebarTab.svelte
- Adds PingingBadge in ProposalAnswer.svelte
```
closes #5562 
- __Desktop__
- __Mobile__
=> feat: pinging badge active vote

packages/desktop/views/dashboard/governance/views/DetailsView.svelte
Format the voting power and the total votes counted
```
- Format voting power
```
- __Desktop__
- __Mobile__
...
=> feat: format voting power and total votes

packages/desktop/package.json
Merge back, since alpha-3 has been released.
...
```
- Update version
```
- __Desktop__
- __Mobile__
...
=> release: version 2.1.0-alpha-3

packages/shared/components/molecules/activity-info/ConsolidationActivityInformation.svelte, packages/shared/components/molecules/activity-info/FoundryActivityInformation.svelte, packages/shared/components/molecules/activity-info/GenericActivityInformation.svelte, packages/shared/components/molecules/activity-info/GovernanceActivityInformation.svelte, packages/shared/components/molecules/activity-info/NftActivityInformation.svelte, packages/shared/components/molecules/activity-info/TokenActivityInformation.svelte, packages/shared/components/organisms/ProposalInformation.svelte, packages/shared/lib/core/utils/interfaces/index.ts, packages/shared/lib/core/utils/interfaces/key-value-box-list.interface.ts
...
```
```
Closes #5644 
- __Desktop__
- __Mobile__
...
=> enhancement: make event id copyable

packages/shared/components/popups/AddProposalPopup.svelte
...
```
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …
=> fix: proposal registration

packages/mobile/views/dashboard/drawers/profile/views/settings/views/ChangePasswordView.svelte
...
```
- feat-mobile: add export stronghold checkbox to change password
```
Close https://github.com/iotaledger/firefly/issues/5117
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feat-mobile: add export stronghold checkbox to change password

packages/mobile/components/buttons/AccountActionsButton.svelte, packages/mobile/features/features.ts, packages/mobile/lib/contexts/dashboard/enums/account-action.enum.ts, packages/mobile/lib/contexts/dashboard/enums/index.ts, packages/mobile/lib/routers/actions/initialiseRouters.ts, packages/mobile/lib/routers/actions/resetRouters.ts, packages/mobile/lib/routers/enums/dashboard-route.enum.ts, packages/mobile/lib/routers/enums/dashboard/account-actions-route.enum.ts, packages/mobile/lib/routers/enums/dashboard/index.ts, packages/mobile/lib/routers/interfaces/account-actions-router-event.interface.ts, packages/mobile/lib/routers/interfaces/index.ts, packages/mobile/lib/routers/routers/dashboard/account-actions-router.ts, packages/mobile/lib/routers/routers/dashboard/index.ts, packages/mobile/lib/routers/utils/getSubroutersForAppContext.ts, packages/mobile/views/dashboard/DashboardRouter.svelte, packages/mobile/views/dashboard/drawers/account-actions/AccountActionsDrawer.svelte, packages/mobile/views/dashboard/drawers/account-actions/AccountActionsRouter.svelte, packages/mobile/views/dashboard/drawers/account-actions/index.js, packages/mobile/views/dashboard/drawers/account-actions/views/AccountActionsView.svelte, packages/mobile/views/dashboard/drawers/account-actions/views/index.js, packages/mobile/views/dashboard/drawers/account-switcher/views/AccountSwitcher.svelte, packages/mobile/views/dashboard/drawers/index.js
...
```
- feat-mobile: prepare account actions drawer and routing
```
Close https://github.com/iotaledger/firefly/issues/4965
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feat-mobile: prepare account actions drawer and routing

packages/shared/lib/core/wallet/actions/activities/preprocessOutputsForAccount.ts
...
```
```
Closes #5706 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: fix inputs preprocessing

packages/shared/components/ProposalQuestion.svelte, packages/shared/lib/contexts/governance/utils/getPercentagesFromAnswerStatuses.ts
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
=> fix: undefined param get percentages

packages/shared/package.json, yarn.lock
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …
=> fix: revert breaking change in i18n

packages/shared/components/inputs/SliderInput.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …
=> fix: fix slider input for 0 decimals

packages/shared/components/atoms/BalanceSummarySection.svelte, packages/shared/components/filters/items/AssetFilterItem.svelte, packages/shared/components/inputs/AssetAmountInput.svelte, packages/shared/components/popups/BurnNativeTokensConfirmationPopup.svelte, packages/shared/components/popups/BurnNativeTokensPopup.svelte, packages/shared/lib/core/ledger/helpers/deconstructLedgerVerificationProps.ts, packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts, packages/shared/lib/core/wallet/utils/sortAssets.ts
Add optional chaining operator to assets
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: add optional chaining operator on assets

packages/shared/locales/en.json, packages/shared/package.json, yarn.lock
Idk why but the IntlMessage formatting now requires a default case, or else it will crash the app.
```
- add `Other` clause to IntlMessage translations
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have commented my code, particularly in hard-to-understand …
=> fix: fix setup view error

packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts, packages/shared/locales/en.json
...
```
- add governance filter
- add consolidation filter
```
Closes #5755 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have added or modified …
=> enhancement: add governance and consolidation as filter options

packages/shared/lib/core/profile/actions/active-profile/logout.ts
Refactors the logout function to get rid of the TODO's. Also corrects the order of first stopping the background sync and only then clearing the event listeners.
...
```
- First stopping background sync, then unsubscribing from wallet events!
- Separate state cleanup in separate function
- Get rid of returning the Promise
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have followed …
=> refactor: logout function

packages/shared/lib/core/app/constants/external-allowed-links.constant.ts
...
```
```
Closes #5373 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> enhancement: add govern.iota.org to allowed urls

packages/shared/components/popups/AddProposalPopup.svelte, packages/shared/lib/contexts/governance/actions/registerParticipationEvent.ts, packages/shared/locales/en.json
...
```
```
Closes #5766
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> enhancement: add proposal to all accounts

packages/shared/lib/core/wallet/enums/governance-action.enum.ts, packages/shared/lib/core/wallet/utils/generateActivity/helper/getGovernanceInfo.ts, packages/shared/lib/core/wallet/utils/getActivityTileTitle.ts, packages/shared/locales/en.json
...
```
```
Closes #5754 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> enhancement: add revote activity

packages/shared/components/popups/BurnNativeTokensConfirmationPopup.svelte
...
```
```
Closes #5778 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: disable burn button while loading

packages/desktop/package.json, packages/shared/lib/participation/constants.ts
...
```
- Added results file for ASMB staking period 4
- Update participation constants as necessary
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
Tested general app functionality and the staking dashboard.
-   [ ] I have commented my …
=> chore: prepare desktop for next Assembly staking period

packages/mobile/android/app/build.gradle, packages/mobile/ios/App/App.xcodeproj/project.pbxproj, packages/shared/lib/participation/constants.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …
=> chore: prepare mobile for asmb staking period 5

packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock, packages/backend/bindings/node/package.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …
=> fix: pass dist-url flag & update wallet-rs revision hash

packages/desktop/features/governance.features.ts, packages/shared/components/modals/ProposalDetailsMenu.svelte
We need the ability to turn this feature on/off.
```
- Add removeProposals feature flag
- Disable remove proposals menu item if feature flag is enabled
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
Enable / disable the `removeProposals` feature flag.
-   [x] I have performed a self-review of my …
=> chore: add feature flag for removing Governance proposals

packages/shared/lib/participation/constants.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: new event id

packages/shared/lib/participation/constants.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: new staking event

packages/mobile/capacitor/plugins/secure-filesystem-access/android/src/main/java/org/iota/plugins/securefilesystemaccess/SecureFilesystemAccessPlugin.java
This PR fixes export Stronghold for Android 13
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: export stronghold android 13

packages/mobile/android/app/build.gradle, packages/mobile/ios/App/App.xcodeproj/project.pbxproj
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: bump mobile versions

packages/shared/lib/contexts/governance/stores/participation-overviews.store.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: multiple calls to participation overview at the same time

packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte, packages/shared/components/ProposalAnswer.svelte, packages/shared/components/ProposalQuestion.svelte, packages/shared/components/ProposalsDetails.svelte, packages/shared/components/atoms/boxes/KeyValueBox.svelte, packages/shared/lib/contexts/governance/actions/pollParticipationEventStatus.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> enhancement: governance loading animations

packages/desktop/features/governance.features.ts, packages/desktop/package.json
...
```
- Incremented desktop version to 2.1.0-alpha-5
- Disabled the removing of Governance proposals
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
Test general app functionality. …
=> release: desktop `2.1.0-alpha-5`

packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte, packages/shared/components/ProposalsDetails.svelte, packages/shared/lib/contexts/governance/stores/participation-overviews.store.ts, packages/shared/lib/contexts/governance/utils/getNumberOfVotedProposals.ts, packages/shared/lib/contexts/governance/utils/getNumberOfVotingProposals.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: fix endless loading on proposal details

packages/mobile/components/ActivityList.svelte, packages/mobile/components/AssetList.svelte
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
=> feat: activity filter

packages/shared/lib/contexts/governance/utils/isSelectedAccountVoting.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: fix destructuring error

packages/shared/package.json, yarn.lock
Need to update to the version 21 for NodeJS bindings.
```
- Incremented shared @iota/wallet dep
- Modified yarn.lock file
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
Test general app functionality.
-   [ ] I have commented my code, …
=> chore: update `wallet.rs`

packages/shared/components/molecules/activity-info/GenericActivityInformation.svelte, packages/shared/components/popups/ActivityDetailsPopup.svelte, packages/shared/components/popups/BurnNativeTokensConfirmationPopup.svelte, packages/shared/components/popups/send/SendConfirmationPopup.svelte, packages/shared/lib/auxiliary/deep-link/handlers/wallet/operations/handleDeepLinkSendFormOperation.ts, packages/shared/lib/core/wallet/actions/getAccountAssetsForSelectedAccount.ts, packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts, packages/shared/lib/core/wallet/utils/sortAssets.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: add more optional chaining

packages/desktop/views/dashboard/collectibles/views/CollectiblesDetailsView.svelte, packages/shared/lib/core/wallet/utils/generateActivity/generateSingleFoundryActivity.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: fix storage deposit for foundry activities

packages/shared/components/molecules/NftMedia.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: fix soonaverse urls with special characters

packages/shared/lib/core/router/enums/routes.ts
Update links to wiki
...
```
- Update URLs
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: update faq & urls for FFv1

packages/desktop/components/popups/VoteForProposalPopup.svelte, packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> enhancement: add manage voting power button  to vote popup

packages/shared/components/atoms/MediaDisplay.svelte, packages/shared/components/molecules/NftMedia.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: handle new soonaverse nfts

packages/shared/components/atoms/MediaDisplay.svelte, packages/shared/components/molecules/NftMedia.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: url not being passed in media display

packages/shared/lib/core/wallet/utils/generateActivity/generateActivitiesFromBasicOutputs.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: only show burn activities if it is self transaction

packages/shared/components/Proposals.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> ui: fix scrollbar on proposal list

.github/workflows/ci.lint.yml, .github/workflows/ci.snyk.yml, .github/workflows/ci.test.yml, .github/workflows/ci.ts.yml, package.json, packages/desktop/tsconfig.json, packages/mobile/tsconfig.json
Port of https://github.com/iotaledger/firefly/pull/5957 to mobile branch
...
```
- Updated mobile CI to check types aswell
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ …
=> Fix: check types in mobile ci

packages/shared/lib/core/router/enums/routes.ts
Updated the wiki URLs for mobile app
...
```
- Updated URLs
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have verified that new and existing unit tests pass …
=> fix: urls for mobile wiki

packages/desktop/views/onboarding/views/profile-backup/views/VerifyMnemonicView.svelte
"busy" not existing variable is causing this view to error, this PR removes it everywhere in this file
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
- Go through the create profile flow
=> fix: VerifyMnemonicView desktop

packages/desktop/views/login/views/EnterPinView.svelte, packages/shared/locales/en.json
closes #6008 
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feat: adds update stronghold TextHint in EnterPinView

packages/desktop/lib/routers/actions/initialiseRouters.ts, packages/desktop/lib/routers/actions/resetRouters.ts, packages/desktop/lib/routers/utils/getSubroutersForAppContext.ts, packages/shared/lib/core/router/enums/index.ts, packages/shared/lib/core/router/enums/login-route.enum.ts, packages/shared/lib/core/router/enums/login/index.ts, packages/shared/lib/core/router/enums/login/update-stronghold-route.enum.ts, packages/shared/lib/core/router/subrouters/index.ts, packages/shared/lib/core/router/subrouters/login-router.ts, packages/shared/lib/core/router/subrouters/login/index.ts, packages/shared/lib/core/router/subrouters/login/update-stronghold-router.ts
closes #6010 
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feat: adds update stronghold router and route

packages/desktop/views/login/views/update-stronghold/UpdateStrongholdRouter.svelte, packages/desktop/views/login/views/update-stronghold/views/ChangePasswordView.svelte, packages/desktop/views/login/views/update-stronghold/views/UpdateStrongholdView.svelte, packages/desktop/views/login/views/update-stronghold/views/index.js, packages/shared/lib/core/router/subrouters/login-router.ts, packages/shared/locales/en.json
⚠️ #6087 needs to be merged first
closes #6050 
closes #6051
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feat: adds ChangePassword view for update stronghold

packages/shared/components/organisms/ProposalCard.svelte
Change proposal card if status has ended to a slightly lighter gray color.
...
```
- Changed color proposal card
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …
=> Feat: update proposal card color in dark mode

packages/desktop/components/popups/MintNftFormPopup.svelte, packages/shared/components/Error.svelte, packages/shared/locales/en.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: fix royalty validations

packages/shared/components/Button.svelte, packages/shared/lib/profile.ts, packages/shared/lib/stronghold.ts, packages/shared/lib/typings/profile.ts
Close https://github.com/iotaledger/firefly/issues/6069
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feat: track stronghold version

packages/desktop/electron/electronApi.js, packages/desktop/electron/main.js, packages/desktop/package.json, packages/desktop/webpack.config.js, packages/shared/lib/core/app/interfaces/platform.interface.ts, packages/shared/lib/core/nfts/actions/downloadNftMedia.ts, packages/shared/lib/core/nfts/actions/index.ts, packages/shared/lib/core/nfts/constants/bytes-per-megabyte.constant.ts, packages/shared/lib/core/nfts/constants/index.ts, packages/shared/lib/core/nfts/enums/download-error-type.enum.ts, packages/shared/lib/core/nfts/enums/download-warning-type.enum.ts, packages/shared/lib/core/nfts/enums/http-header.enum.ts, packages/shared/lib/core/nfts/enums/index.ts, packages/shared/lib/core/nfts/interfaces/index.ts, packages/shared/lib/core/nfts/interfaces/nft-download-metadata.interface.ts, packages/shared/lib/core/nfts/interfaces/nft.interface.ts, packages/shared/lib/core/nfts/utils/buildNftFromNftOutput.ts, packages/shared/lib/core/nfts/utils/downloadAllNftMedia.ts, packages/shared/lib/core/nfts/utils/index.ts, packages/shared/lib/core/profile-manager/actions/events-handlers/handleNewOutputEvent.ts, packages/shared/lib/core/profile/actions/active-profile/login.ts, packages/shared/lib/tests/__mocks__/platform.mock.ts, yarn.lock
This PR includes the download and caching of NFT media. On Login, for every nft it its checked if the corresponding media is stored locally, if not, it gets downloaded. 
```
- On Login, check for every nft if the corresponding media is stored locally, if not, download it
- On new NftOutput, download media
```
Closes #3451 
- __Desktop__
- __Mobile__
...
=> enhancement: download nft media to local system

.github/workflows/build-desktop.yml
Fixed that release draft shows the correct url on how to verify the correct FF version
...
```
- Update URL
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …
=> Fix: update verify url

.github/workflows/build-desktop.yml
Updated the verify download link for the release template
...
```
- Updated verify download link
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> Fix: update verify link

packages/desktop/components/ProposalAnswer.svelte
Clsoes #6207 
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: make questions collapsible

packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> enhancement: collapse all questions

packages/shared/lib/profile.ts, packages/shared/lib/typings/profile.ts, packages/shared/lib/wallet.ts
Need a way to check a profile's stronghold version.
```
- Add Stronghold version constant
- Add field to profile data for Stronghold version
- Add util function to check if Stronghold version is outdated
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
...
-   [x] I have performed a self-review of …
=> feat: add Stronghold version

packages/desktop/electron/electronApi.js, packages/desktop/electron/main.js, packages/shared/lib/core/app/interfaces/platform.interface.ts, packages/shared/lib/core/nfts/utils/checkIfNftShouldBeDownloaded.ts, packages/shared/lib/tests/__mocks__/platform.mock.ts
Clsoes #6252 
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> enhancement: improve check if media exists

packages/mobile/components/drawers/send/SendRouter.svelte, packages/mobile/components/drawers/send/views/ReviewView.svelte
This PR aims to fix a crash we had in mobile due to the latets changes in the core libraries.
Additionally, latest desktop changes have been added to add the surplus fixes
Close https://github.com/iotaledger/firefly/issues/6326
```
- fix: mobile send crash
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have followed the contribution guidelines for …
=> fix: mobile send crash

packages/desktop/webpack.config.js
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: add conditionNames

packages/mobile/components/inputs/PinInput.svelte, packages/mobile/views/login/views/EnterPinView.svelte
Seems like there was a double event being fired because we validated & submitted inside the component and inside the view 
Close https://github.com/iotaledger/firefly/issues/6386
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have performed a …
=> fix: mobile login

yarn.lock
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: update `yarn.lock` file

packages/desktop/features/settings.features.ts, packages/desktop/views/dashboard/settings/views/collectibles/RefreshNftMedia.svelte, packages/desktop/views/dashboard/settings/views/collectibles/collectibles-settings.constant.js, packages/desktop/views/dashboard/settings/views/collectibles/index.js, packages/shared/lib/auxiliary/icon/constants/settings-icon-svg.ts, packages/shared/lib/core/router/enums/settings/collectibles-settings-route.enum.ts, packages/shared/locales/en.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feature: refresh nft media

.github/workflows/ci.lint.yml
...
```
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: remove `rust` linting job

packages/mobile/App.svelte, packages/mobile/capacitor/capacitorApi.ts
Close https://github.com/iotaledger/firefly/issues/6190
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feat: add mobile version details

packages/mobile/App.svelte, packages/mobile/capacitor/capacitorApi.ts, packages/shared/lib/core/app/interfaces/platform.interface.ts, packages/shared/lib/tests/__mocks__/platform.mock.ts
Close https://github.com/iotaledger/firefly/issues/4784
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feat: set language based on device on first startup

packages/shared/lib/core/wallet/utils/generateActivity/helper/getSubjectFromActivity.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: fix unknown activity

.github/workflows/build-and-release-desktop.yml
Update node to fix CI: https://github.com/iotaledger/firefly/actions/runs/4698060718
...
```
- Update node to latest CI
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] …
=> fix: update node

packages/mobile/capacitor.config.ts, packages/mobile/features/capacitor.features.ts, packages/mobile/features/features.ts, packages/mobile/features/onboarding.features.ts
Close https://github.com/iotaledger/firefly/issues/6344
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: prepare feature flags

packages/mobile/android/app/build.gradle, packages/mobile/ios/App/App.xcodeproj/project.pbxproj, packages/mobile/package.json
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
- …
=> chore: bump version

packages/desktop/components/popups/send/SendConfirmationPopup.svelte, packages/shared/components/molecules/BasicActivityDetails.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: use correct unit on confirmation

packages/mobile/components/drawers/send/views/AmountView.svelte
Close https://github.com/iotaledger/firefly/issues/6520
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [x] iOS
... …
=> fix: max amount send flow

packages/desktop/components/buttons/popup-buttons/FaucetRequestButton.svelte, packages/shared/lib/contexts/developer/actions/requestTokensFromFaucet.ts, packages/shared/lib/core/network/constants/faucet-urls.constant.ts
Close https://github.com/iotaledger/firefly/issues/6590
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> refactor: faucet to use `NetworkId`

packages/mobile/components/NodeListTable.svelte, packages/mobile/components/drawers/profile/views/settings/views/networkInformation/views/NetworkInformationNodeInfoView.svelte, packages/shared/components/modals/NodeActionsMenu.svelte, packages/shared/components/organisms/NodeListTable.svelte, packages/shared/lib/contexts/governance/utils/createProposalFromEvent.ts, packages/shared/lib/core/network/tests/network.test.ts, packages/shared/lib/core/network/utils/isNetworkOfficial.ts
Close https://github.com/iotaledger/firefly/issues/6588
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> refactor: official nodes and official network to use `NetworkId`

packages/desktop/components/popups/ActivityDetailsPopup.svelte, packages/desktop/views/dashboard/collectibles/views/CollectiblesDetailsView.svelte, packages/shared/components/molecules/activity-info/GenericActivityInformation.svelte, packages/shared/lib/core/network/constants/explorer-urls.constant.ts, packages/shared/lib/core/network/utils/getOfficialExplorerUrl.ts
Close https://github.com/iotaledger/firefly/issues/6592
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> refactor: explorer to use `NetworkId`

packages/mobile/android/app/build.gradle, packages/mobile/android/app/src/main/AndroidManifest.xml, packages/mobile/android/app/src/main/java/org/iota/firefly/mobile/MainActivity.java, packages/mobile/android/app/src/main/java/org/iota/firefly/mobile/WebViewSettingsPlugin.java, packages/mobile/android/app/src/main/res/values/strings.xml, packages/mobile/ios/App/App.xcodeproj/project.pbxproj, packages/mobile/package.json
Closes https://github.com/iotaledger/firefly/issues/6550
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have verified that new …
=> chore: use different app id

packages/shared/lib/contexts/onboarding/actions/findShimmerRewards.ts, packages/shared/lib/contexts/onboarding/actions/syncShimmerClaimingAccount.ts, packages/shared/locales/en.json
...
```
- Added missing translation string to en.json
- Changed hardcoded strings to use new translation string
```
-   [x] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
- …
=> fix: add missing translation string

packages/desktop/views/dashboard/Sidebar.svelte, packages/shared/components/atoms/NetworkIcon.svelte, packages/shared/components/molecules/AssetIcon.svelte, packages/shared/lib/auxiliary/icon/constants/index.ts, packages/shared/lib/auxiliary/icon/constants/network-icon-svg.ts
Close https://github.com/iotaledger/firefly/issues/6614
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feat: add network icon map using network id

packages/shared/components/inputs/NetworkInput.svelte, packages/shared/lib/core/layer-2/constants/network-address.constant.ts, packages/shared/lib/core/layer-2/utils/getDestinationNetworkFromAddress.ts, packages/shared/lib/core/layer-2/utils/getLayer2NetworkFromAddress.ts, packages/shared/lib/core/layer-2/utils/isLayer1Destination.ts
Close https://github.com/iotaledger/firefly/issues/6616
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> refactor: `NETWORK_ADDRESS` to use `NetworkId`

packages/mobile/views/onboarding/views/profile-recovery/views/ImportMnemonicPhraseView.svelte, packages/mobile/views/onboarding/views/profile-setup/views/SetupClaimedView.svelte, packages/mobile/views/onboarding/views/profile-setup/views/SetupRecoveredView.svelte, packages/mobile/views/onboarding/views/profile-setup/views/SetupView.svelte, packages/shared/components/atoms/buttons/OnboardingButton.svelte
Close https://github.com/iotaledger/firefly/issues/6519
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> enhancement: disable onboarding buttons while async loading

.github/workflows/ci.lint.yml, .github/workflows/ci.snyk.yml, .github/workflows/ci.test.yml, packages/shared/components/inputs/Amount.svelte, packages/shared/components/popups/StakingManager.svelte, packages/shared/lib/assets.ts, packages/shared/lib/chart.ts, packages/shared/lib/core/router/subrouters/login-router.ts, packages/shared/lib/currency.ts, packages/shared/lib/market.ts, packages/shared/lib/wallet.ts, packages/shared/routes/dashboard/wallet/views/Send.svelte, packages/shared/routes/setup/Balance.svelte, packages/shared/routes/setup/Congratulations.svelte, packages/shared/routes/setup/migrate/views/Migrate.svelte
...
```
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
Difficult to reproduce - can't tell exactly where it's coming from but good to test if `marketData` is ever `null` or `undefined`.
-   [ ] I have …
=> fix: `TypeError: cannot read property 'usd' of null`

packages/mobile/components/drawers/profile/views/settings/views/DiagnosticsView.svelte
closes #6586 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
- See if currency field in diagnostics show the correct value
=> fix-mobile: currency undefined

packages/desktop/components/drawers/network-config/drawers/ConnectedChainsDrawer.svelte, packages/desktop/features/network.features.ts, packages/shared/lib/features/interfaces/network-features.interface.ts
Adding a chain is not going to be a part of the MVP production release, so it should be behind a feature flag.
```
- Add feature flag for adding a chain
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
Enable / disable the feature flag and see the UI.
-   [x] I have performed a self-review of my …
=> chore: add feature flag for adding a L2 chain

packages/mobile/capacitor/capacitorApi.ts, packages/mobile/capacitor/plugins/secure-filesystem-access/android/src/main/java/org/iota/plugins/securefilesystemaccess/SecureFilesystemAccessPlugin.java, packages/mobile/capacitor/plugins/secure-filesystem-access/ios/Plugin/Plugin.swift, packages/mobile/features/features.ts
Closes https://github.com/iotaledger/firefly/issues/6428
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [x] iOS
...
-   [ ] I have verified that new …
=> Feat: List and remove profile folders

packages/shared/lib/contexts/governance/actions/initializeRegisteredProposals.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: interrupt participation fetch if logged out

packages/shared/lib/contexts/onboarding/actions/restoreBackupFromStrongholdFile.ts, packages/shared/lib/contexts/onboarding/helpers/restoreBackupByCopyingFile.ts, packages/shared/lib/core/error/constants/error-regex.constant.ts
Closes https://github.com/iotaledger/firefly/issues/6531
Since this changes affects shared files, they has been tested with Android / iOS / Linux (Desktop)
```
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [x] iOS
...
-   [ ] I …
=> fix: stronghold import infinite loading

packages/desktop/App.svelte, packages/desktop/electron/lib/menu.js, packages/desktop/electron/lib/menuState.js, packages/desktop/features/settings.features.ts, packages/desktop/lib/helpers.ts, packages/desktop/views/dashboard/Sidebar.svelte, packages/desktop/views/dashboard/settings/views/advanced/DeveloperToggle.svelte, packages/desktop/views/dashboard/settings/views/advanced/advanced-settings.constant.js, packages/desktop/views/dashboard/settings/views/advanced/index.js, packages/shared/lib/auxiliary/icon/constants/settings-icon-svg.ts, packages/shared/lib/core/app/interfaces/platform-event-map.interface.ts, packages/shared/lib/core/router/enums/settings/advanced-settings-route.enum.ts, packages/shared/lib/features/interfaces/settings-features.interface.ts, packages/shared/locales/en.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feat: developer mode toggle setting

packages/mobile/components/drawers/send/views/AmountView.svelte
AmountView in the send flow wasn't showing a numeric keyboard. Changed to show numeric keyboard and tested on both iOS and android.
```
- Added numeric keyboard to AmountView for send flow
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [x] iOS
...
- …
=> mobile-fix: add numeric keyboard to send flow

packages/shared/lib/core/utils/string.ts, packages/shared/lib/core/utils/tests/string.test.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> test: string utils

packages/desktop/components/AccountSummary.svelte, packages/desktop/components/buttons/popup-buttons/FaucetRequestButton.svelte, packages/desktop/components/popups/FaucetRequestPopup.svelte, packages/desktop/views/dashboard/Dashboard.svelte, packages/desktop/views/dashboard/settings/views/network/NetworkInformation.svelte, packages/mobile/components/buttons/NetworkStatusButton.svelte, packages/mobile/components/drawers/NetworkStatusDrawer.svelte, packages/mobile/components/drawers/profile/views/settings/views/networkInformation/views/NetworkInformationInitView.svelte, packages/shared/components/organisms/NodeConfigurationForm.svelte, packages/shared/lib/core/network/actions/getAndUpdateNodeInfo.ts, packages/shared/lib/core/network/helpers/getNetworkStatusFromNodeInfo.ts, packages/shared/lib/core/network/stores/node-info.store.ts, packages/shared/lib/core/network/utils/buildPersistedNetworkFromNodeInfoResponse.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: add strict typescript to node info

packages/desktop/components/popups/MintNftConfirmationPopup.svelte, packages/desktop/components/popups/MintNftFormPopup.svelte, packages/shared/lib/core/wallet/interfaces/account-assets.interface.ts, packages/shared/lib/core/wallet/stores/all-account-activities.store.ts, packages/shared/lib/core/wallet/stores/mint-nft-details.store.ts, packages/shared/lib/core/wallet/stores/persisted-assets.store.ts, packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts, packages/shared/lib/core/wallet/stores/selected-account-assets.store.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: add strict typescript to mint nft

packages/shared/lib/participation/constants.ts
...
```
```
...
- __Desktop__
- __Mobile__
...
=> chore: 6th ASMB staking period for mobile

packages/desktop/features/onboarding.features.ts, packages/desktop/package.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> release: desktop 2.1.2

.github/workflows/build-test.yml
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: adjust automated build CI for Firefly Shimmer

packages/mobile/capacitor/capacitorApi.ts, packages/mobile/capacitor/plugins/secure-filesystem-access/android/src/main/java/org/iota/plugins/securefilesystemaccess/SecureFilesystemAccessPlugin.java, packages/mobile/capacitor/plugins/secure-filesystem-access/ios/Plugin/Plugin.m, packages/mobile/capacitor/plugins/secure-filesystem-access/ios/Plugin/Plugin.swift, packages/mobile/capacitor/plugins/secure-filesystem-access/src/definitions.ts, packages/shared/lib/tests/mocks/platform.ts, packages/shared/lib/typings/platform.ts
Closes https://github.com/iotaledger/firefly/issues/6796
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have verified that new …
=> feat: add copy delete filesystem plugin

packages/shared/lib/core/router/app-router.ts, packages/shared/lib/core/router/subrouters/import-router.ts, packages/shared/lib/core/router/subrouters/update-stronghold-router.ts, packages/shared/lib/core/router/types/event.ts, packages/shared/lib/shell/walletApi.ts, packages/shared/lib/stronghold.ts, packages/shared/lib/tests/mocks/platform.ts, packages/shared/lib/typings/platform.ts, packages/shared/routes/login/views/EnterPin.svelte, packages/shared/routes/login/views/SelectProfile.svelte, packages/shared/routes/update-stronghold/UpdateStronghold.svelte, packages/shared/routes/update-stronghold/views/Update.svelte
This PR implements and fixes all the logic in the front end for the update stronghold
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [x] iOS
=> feat-mobile: update stronghold logic v1

packages/desktop/views/dashboard/send-flow/send-flow.router.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: reorder send flow

packages/backend/Cargo.lock, packages/backend/Cargo.toml, packages/backend/bindings/capacitor/android/gradle/wrapper/gradle-wrapper.properties, packages/backend/bindings/capacitor/android/src/main/java/org/iota/fireflyactorsystem/WalletPlugin.java, packages/backend/bindings/capacitor/ios/Plugin/Plugin.m, packages/backend/bindings/capacitor/ios/Plugin/Plugin.swift, packages/backend/bindings/capacitor/ios/Podfile, packages/backend/bindings/capacitor/src/definitions.ts, packages/mobile/capacitor/walletPluginApi.ts, packages/mobile/ios/App/Podfile, packages/mobile/public/IotaWalletInternal.podspec, packages/shared/lib/core/router/app-router.ts, packages/shared/lib/core/router/subrouters/import-router.ts, packages/shared/lib/core/router/subrouters/update-stronghold-router.ts, packages/shared/lib/core/router/types/event.ts, packages/shared/lib/shell/walletApi.ts, packages/shared/lib/stronghold.ts, packages/shared/lib/tests/mocks/walletActor.ts, packages/shared/lib/typings/walletActor.ts, packages/shared/routes/login/views/EnterPin.svelte, packages/shared/routes/login/views/SelectProfile.svelte, packages/shared/routes/update-stronghold/UpdateStronghold.svelte, packages/shared/routes/update-stronghold/views/Update.svelte
Closes #6068
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: add Stronghold migration v1

packages/desktop/components/NetworkCard.svelte, packages/shared/lib/core/account/actions/buildAccountState.ts, packages/shared/lib/core/account/actions/buildAccountStateAndPersistedData.ts, packages/shared/lib/core/account/interfaces/persisted-account-data.interface.ts, packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> enhancement: cache deposit address

packages/desktop/package.json, yarn.lock
Update electron
...
```
- Bump electron to 22.3.11
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: bump electron to 22.3.11

packages/shared/lib/contexts/onboarding/actions/restoreBackupFromStrongholdFile.ts, packages/shared/lib/contexts/onboarding/actions/verifyAndStoreMnemonic.ts, packages/shared/lib/core/app/classes/platform.class.ts, packages/shared/lib/core/app/stores/mobile.store.ts, packages/shared/lib/core/error/classes/base-error.class.ts, packages/shared/lib/core/profile/types/account-recovery-configuration.type.ts
#6923
...
```
- Add isMobile() helper function
- Fix wrong conditionals
- Add originalMessage to error log
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …
=> fix: claiming smr

packages/shared/lib/core/wallet/utils/convertToRawAmount.ts
Close https://github.com/iotaledger/firefly/issues/6937
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: erc-20 tokens raw amount support

.github/workflows/build-test.yml
This changes the job schedule to weekly at 12:00 AM on Sundays. 
```
- Changed cron job scheduled time
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I …
=> chore: finalize build test schedule

.github/workflows/build-desktop-test.yml, .github/workflows/build-desktop.yml
Just to create more consistency in the workflow naming.
```
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: change workflow name for v2 build

packages/shared/components/popups/AirdropNetworkInfo.svelte
Remove outdated text
...
```
- Remove outdated text
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have verified that new and existing unit tests pass locally with …
=> chore: update text

.github/dependabot.yml
Remove dependency check for mobile folder.
...
```
- Update dependabot
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have verified that new and existing unit tests …
=> chore: remove dependabot check for mobile

packages/desktop/package.json, packages/shared/package.json, yarn.lock
Fix for critical security issues reported by snyk around electron.
https://github.com/iotaledger/firefly/actions/runs/5280875517/jobs/9553631150
...
```
- Updated electron
- Updated web3
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …
=> chore: update electron

packages/desktop/components/popups/send/SendConfirmationPopup.svelte, packages/shared/components/inputs/AssetDropdown.svelte, packages/shared/components/molecules/BasicActivityDetails.svelte, packages/shared/lib/core/layer-2/types/layer2-metadata.interface.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: fix old sendflow

packages/shared/components/molecules/AssetIcon.svelte
Closes #7046 
```
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
- Go to Send asset
- Choose another option from the dropdown
...
-   [ ] I have verified that new and existing unit tests pass locally with …
=> fix: asset selection reactivity in send flow

packages/shared/components/inputs/Dropdown.svelte
Closes #7052 
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have verified that my …
=> fix: dropdown component alignment 

packages/shared/lib/core/network/utils/getNetworkId.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> hotfix: add missing optional chaining

packages/shared/lib/core/account/actions/buildAccountState.ts, packages/shared/lib/core/account/actions/buildAccountStateAndPersistedData.ts, packages/shared/lib/core/account/interfaces/persisted-account-data.interface.ts, packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
Close https://github.com/iotaledger/firefly/issues/7132
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> revert: undo cache deposit address

packages/desktop/electron/main.js
Modify comment in the `suspend` event of the power monitor
```
- Modify comment in the `suspend` event of the power monitor
```
-   [ ] MacOS
-   [X] Linux
-   **Mobile**
-   [ ] iOS
- Login to a profile
- Suspend computer with linux OS
- Boot the computer
- Verify that the `logout` has been done correctly
-   [x] I have verified that my latest changes pass CI workflows for testing and …
=> fix: comment

packages/desktop/electron/main.js, packages/desktop/views/dashboard/Dashboard.svelte, packages/shared/lib/core/app/interfaces/platform-event-map.interface.ts
Update name of power monitor events. `Lock screen` and `Suspend`
```
- Modify lock-screen event by power-monitor-lock-screen
- Modify suspend event by power-monitor-suspend
```
-   [ ] MacOS
-   [X] Linux
-   **Mobile**
-   [ ] iOS
- Login to a profile
- Suspend the computer
- Boot the computer
- Check that `logout` was successful
-   [x] I have verified that my latest changes pass CI …
=> enhancement: update naming of power monitor events

packages/shared/components/popups/Index.svelte, packages/shared/components/popups/MobileDeprecation.svelte, packages/shared/lib/app.ts, packages/shared/locales/en.json, packages/shared/routes/dashboard/Dashboard.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feat: add mobile deprecation popup

packages/desktop/views/update-stronghold/views/ChangePasswordView.svelte, packages/desktop/views/update-stronghold/views/UpdateBackupView.svelte, packages/shared/lib/contexts/onboarding/actions/claimShimmerRewards.ts
Close https://github.com/iotaledger/firefly/issues/7278
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: shimmer claiming

packages/shared/components/filter-items/DateFilterItem.svelte, packages/shared/components/filter-items/NumberFilterItem.svelte, packages/shared/components/filter-items/OrderFilterItem.svelte, packages/shared/components/filter-items/SelectionFilterItem.svelte, packages/shared/components/inputs/Dropdown.svelte
Fixes #7274 
> Update component to focus correctly the selected item
...
```
- Fix a bug where the component was searching an element incorrectly
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have added or modified tests that prove my changes …
=> fix: dropdown not focusing correctly

packages/shared/lib/contexts/governance/actions/setVotingPower.ts
Fixes #7208 
...
```
```
-   [ ] MacOS
-   [x] Linux
-   **Mobile**
-   [ ] iOS
- Click on manage voting power
- Confirm without changes
...
-   [ ] I have verified that my latest changes pass CI workflows for testing …
=> fix: avoid error when voting power stays the same

.github/workflows/handbook.yml
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> ci: bump handbook workflow from v2 to v3

.github/workflows/build-desktop.yml, patches/dmg-builder+22.9.1.patch
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: macos build

packages/shared/package.json, yarn.lock
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: upgrade bindings to rc-44

packages/desktop/views/onboarding/views/complete-onboarding/views/FinishOnboardingView.svelte, packages/desktop/views/onboarding/views/create-profile/views/ChooseCreateProfileFlowView.svelte
> Moved logic to update stronghold version from `ChooseCreateProfileFlowView` to `FinishOnboardingView`
```
- Moved logic to update stronghold version from `ChooseCreateProfileFlowView` to `FinishOnboardingView`
```
-   [ ] MacOS
-   [X] Linux
-   **Mobile**
-   [ ] iOS
Create and restore profiles and check that the software profiles appear with the latest version of stronghold and ledger does not appear the version of stronghold …
=> fix: stronghold version

packages/desktop/features/analytics.features.ts, packages/desktop/features/interfaces/analytics-features.interface.ts, packages/desktop/views/update-stronghold/views/UpdateStrongholdView.svelte
> Adds a 'stronghold-migration' event for Amplitude to track stats about success/fail of stronghold migrations
Closes https://github.com/iotaledger/firefly/issues/7322
```
- Added a 'stronghold-migration' event for Amplitude to track outcomes of stronghold migration
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
-   [ ] I have …
=> feat: add stronghold migration analytics event 

packages/backend/Cargo.lock, packages/backend/Cargo.toml, packages/backend/bindings/node/native/Cargo.lock, packages/backend/bindings/node/native/Cargo.toml
Close https://github.com/iotaledger/firefly/issues/7338
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> chore: update bindings

packages/shared/components/Sidebar.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> feat: remove staking badge notification

packages/shared/package.json, yarn.lock
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
...
- …
=> chore: update bindings to rc 46

packages/desktop/views/onboarding/views/restore-profile/views/ClaimFinderView.svelte, packages/shared/package.json, yarn.lock
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: shimmer claiming missing unlock stronghold

.github/workflows/build-desktop.yml
...
```
```
-   [ ] MacOS
-   [ ] Linux
-   **Mobile**
-   [ ] iOS
... …
=> fix: Install cargo-patch with locked deps

packages/shared/components/pills/Pill.svelte
> Closes #7075 
...
```
- Add missing types
```
-   [ ] MacOS
-   [x] Linux
...
-   [ ] I have verified that my latest …
=> refactor: cleanup Pill component

packages/shared/package.json, yarn.lock
Closes https://github.com/iotaledger/firefly/issues/7403
...
```
```
-   [ ] MacOS
-   [ ] Linux
...
-   [ ] I have added or modified tests that prove my changes …
=> chore: bump @iota/sdk to v1.0.9

packages/shared/routes/dashboard/staking/Staking.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> hotfix: do not display new staking event popup until there is a new one

packages/desktop/package.json, packages/shared/routes/dashboard/staking/Staking.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> release: desktop 1.7.5

packages/desktop/components/popups/send/SendConfirmationPopup.svelte
resolves #7421 
-   [x] MacOS
-   [x] Linux
=> Fix: Rework setting initial expiration date in SendConfirmationPopup

packages/shared/lib/core/profile/utils/getStorageDirectoryOfProfiles.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: listen on window's load instead of document

packages/shared/components/MediaDisplay.svelte, packages/shared/components/NftActivityDetails.svelte
Close https://github.com/iotaledger/firefly/issues/7426
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: nft aspect ratio & crash when navigating to nft details from activity

packages/shared/lib/core/profile-manager/api/clearStrongholdPassword.ts
Closes https://github.com/iotaledger/firefly/issues/7454
...
```
```
-   [ ] MacOS
-   [ ] Linux
...
-   [ ] I have added or modified tests that prove my changes …
=> fix(patch): error when logging out after unlocking stronghold not finished

packages/desktop/package.json, packages/shared/lib/core/network/constants/default-chain-configurations.constant.ts, packages/shared/lib/core/network/enums/chain-id.enum.ts
Bump version and add Shimmer EVM
-   [ ] MacOS
-   [x] Linux
=> Chore: Add Shimmer EVM

packages/shared/package.json, yarn.lock
Closes #7467 
> Update the latest version of the sdk
```
- Update the latest version of the sdk
```
-   [ ] MacOS
-   [X] Linux
-   [x] I have made corresponding changes to the documentation
=> chore: bump @iota/sdk to v1.0.13

packages/desktop/electron/lib/analytics.js, packages/desktop/product.js, packages/desktop/webpack.config.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: add network prefix to sentry and amplitude analytics

packages/shared/locales/en.json
Closes #7486 
> Add text in vesting collect
```
- Add text in vesting collect
```
-   [ ] MacOS
-   [X] Linux
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
=> feat: add text in vesting collect

packages/desktop/components/popups/BalanceBreakdownPopup.svelte
Closes https://github.com/iotaledger/firefly/issues/7492
=> fix: Proper amount accumulation of balance breakdown

.github/workflows/build-and-release-desktop.yml, README.md, packages/desktop/components/popups/BalanceBreakdownPopup.svelte, packages/desktop/features/onboarding.features.ts, packages/desktop/features/vesting.features.ts, packages/desktop/product.js, packages/desktop/views/dashboard/Dashboard.svelte, packages/shared/lib/core/network/constants/default-network-metadata.constant.ts, packages/shared/locales/en.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore & fix: update code for shimmer app

.github/workflows/build-and-release-desktop.yml, README.md, packages/desktop/features/onboarding.features.ts, packages/desktop/features/vesting.features.ts, packages/desktop/package.json, packages/desktop/product.js
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore: update code for iota app

packages/desktop/components/popups/DiagnosticsPopup.svelte, packages/desktop/product.js, packages/shared/locales/en.json
Closes #7485 
> Add App Name to diagnostics popup
```
- Add App Name to diagnostics popup
```
-   [ ] MacOS
-   [X] Linux
-   [X] I have followed the contribution guidelines for this project
-   [X] I have performed a self-review of my own code
-   [X] I have verified that my latest changes pass CI workflows for testing and linting
-   [X] I have made corresponding changes to the documentation
=> feat: add App Name to diagnostics popup

packages/shared/locales/en.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> hotfix: stardust locale

packages/shared/lib/core/network/constants/official-node-urls.constant.ts, packages/shared/lib/core/network/tests/network.test.ts
Close https://github.com/iotaledger/firefly/issues/7473
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore: update shimmer and iota nodes

packages/shared/lib/core/network/constants/official-node-urls.constant.ts, packages/shared/lib/core/network/tests/network.test.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> tmp: remove tanglebay node for release, add when ready

packages/desktop/product.js
https://github.com/iotaledger/firefly/blob/f5bb517ad0c9c5570f0080695d161f3d1229901b/packages/desktop/electron-builder-config.js#L10
=> fix: wrong appId

packages/shared/components/buttons/ReceiveAddressButton.svelte
Closes #5149 
...
```
- Remove unnecessary padding-bottom
```
-   [ ] MacOS
-   [x] Linux
... …
=> enhancement: improve padding on wallet tab when app is minimum size

packages/shared/package.json, yarn.lock
Close https://github.com/iotaledger/firefly/issues/7575
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore: bump @iota/sdk to v1.1.1

packages/shared/lib/core/network/constants/official-node-urls.constant.ts, packages/shared/lib/core/network/tests/network.test.ts
Close https://github.com/iotaledger/firefly/issues/7579
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: add tanglebay mainnet node

packages/shared/lib/core/network/utils/getNetworkIdFromNetworkName.ts
Closes https://github.com/iotaledger/firefly/issues/7618
=> chore: Add testnet-2

packages/desktop/package.json, yarn.lock
Closes https://github.com/iotaledger/firefly/issues/7614
=> chore: bump electron to 22.3.27

.github/workflows/build-and-release-desktop.yml, .github/workflows/build-desktop-test.v1.yml, .github/workflows/build-desktop-test.v2.yml, .github/workflows/build-desktop.yml, packages/desktop/package.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> release: desktop shimmer 2.1.9

.github/ISSUE_TEMPLATE/create-task.yml
Closes https://github.com/iotaledger/firefly/issues/7656
=> chore: Simplify Task template

packages/shared/locales/en.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: wrong migration chrysalis locale

packages/shared/package.json, yarn.lock
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore: bump @iota/sdk to v1.1.3

packages/desktop/components/popups/send/SendConfirmationPopup.svelte, packages/shared/lib/core/wallet/utils/send/sendUtils.ts
Close https://github.com/iotaledger/firefly/issues/7718
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: add time expiration unlock condition for l1-l2 txs

packages/shared/lib/contexts/onboarding/actions/findShimmerRewards.ts, packages/shared/lib/core/account/actions/findBalances.ts, packages/shared/lib/core/ledger/actions/pollLedgerNanoStatus.ts, packages/shared/lib/core/ledger/stores/ledger-nano-status.store.ts
Close https://github.com/iotaledger/firefly/issues/7714
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: reduce ledger polling on heavy duty work like recover accounts

packages/shared/components/inputs/AssetAmountInput.svelte
> Closes #7709 
...
```
- show error message when input validation fails
```
-   [ ] MacOS
-   [x] Linux
...
-   [ ] I …
=> feat: improve `AssetAmountInput` validation

packages/desktop/views/dashboard/vesting/Vesting.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: remove use of prepareConsolidateOutputs in vesting

packages/shared/lib/contexts/onboarding/actions/completeOnboardingProcess.ts, packages/shared/lib/contexts/onboarding/actions/initialiseOnboardingProfile.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: broken create new profile & onboarding

packages/shared/components/activity-info/GenericActivityInformation.svelte, packages/shared/locales/en.json
Close https://github.com/iotaledger/firefly/issues/7721
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: rename gasBudget to gasFee in UI

packages/shared/package.json, yarn.lock
Closes https://github.com/iotaledger/firefly/issues/7956
Changelog: https://github.com/iotaledger/iota-sdk/blob/develop/bindings/nodejs/CHANGELOG.md#115---2024-01-29
=> chore: bump @iota/sdk to v1.1.5

packages/desktop/electron/electronApi.js, packages/shared/lib/core/app/interfaces/platform.interface.ts, packages/shared/lib/core/profile/actions/active-profile/login.ts, packages/shared/lib/core/profile/actions/active-profile/logout.ts, packages/shared/lib/core/profile/actions/active-profile/resetActiveProfile.ts, packages/shared/lib/core/profile/actions/active-profile/setActiveProfile.ts, packages/shared/lib/tests/__mocks__/platform.mock.ts
Closes https://github.com/iotaledger/firefly/issues/7951
=> chore: Clean electron debris

.github/workflows/build-and-release-desktop.yml, .github/workflows/build-desktop-test.v1.yml, .github/workflows/build-desktop-test.v2.yml, .github/workflows/build-desktop.yml, packages/desktop/scripts/notarize.macos.js
https://www.electron.build/configuration/mac.html#NotarizeNotaryOptions
Close https://github.com/iotaledger/firefly/issues/7996
=> hotfix: macOS notarization

.github/workflows/build-desktop.yml
Closes https://github.com/iotaledger/firefly/issues/7998
=> chore: Clean up build desktop workflow

packages/shared/lib/contexts/onboarding/actions/cleanupOnboarding.ts, packages/shared/lib/contexts/onboarding/helpers/convertOnboardingProfileToPersistedProfile.ts
Closes https://github.com/iotaledger/firefly/issues/8013
=> fix: Prevent duplication of wallets across profiles created in same session

packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/FundConfirmationView.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: base coin error

packages/shared/components/NodeConfigurationForm.svelte, packages/shared/lib/core/network/interfaces/client-options.interface.ts, packages/shared/lib/core/network/interfaces/node-info-response.interface.ts, packages/shared/lib/core/network/interfaces/node.interface.ts, packages/shared/lib/core/network/utils/getNetworkIdFromNetworkName.ts, packages/shared/lib/core/wallet/actions/getNodeInfo.ts
Closes https://github.com/iotaledger/firefly/issues/8118
This seems to fix my issues, let me know if you find anything else that broke (it probably did, but I didn't notice)
=> Fix: Sync with sdk types

packages/desktop/components/modals/AccountManagementMenu.svelte
Closes #8141 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: update deposit address when the main account id is updated

packages/desktop/package.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore: bump version to 2.1.14

packages/desktop/electron/electronApi.js, packages/shared/lib/core/app/interfaces/platform.interface.ts, packages/shared/lib/tests/__mocks__/platform.mock.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> revert: bring back renameProfileFolder

packages/desktop/components/AccountManagementDetails.svelte, packages/desktop/components/popups/ActivateAccountPopup.svelte, packages/shared/lib/core/wallet/actions/events-handlers/handleNewOutputEvent.ts
Closes #8190 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: reactivity error when activating account

packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/AccountCreationView.svelte
Closes #8197 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: show / Hide password in implicit account creation

packages/shared/components/Error.svelte
> Closes #8198 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: align error message when unlocking password

packages/shared/lib/core/profile/actions/active-profile/login.ts, packages/shared/lib/core/wallet/actions/events-handlers/handleNewOutputEvent.ts, packages/shared/lib/core/wallet/constants/default-sync-options.constant.ts
> Closes #8107 and closes #8187 
...
```
```
-   [ ] MacOS
-   [ ] Linux
...
-   [ ] I …
=> feat: update `startBackgroundSync` & `DEFAULT_SYNC_OPTIONS`

packages/desktop/views/dashboard/Sidebar.svelte
> Closes #8233 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: change icon for delegation tab

packages/shared/components/activity-info/GenericActivityInformation.svelte, packages/shared/lib/core/wallet/interfaces/processed-transaction.interface.ts, packages/shared/lib/core/wallet/types/activities/base-activity.type.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateSingleAccountActivity.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateSingleAnchorActivity.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateSingleBasicActivity.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateSingleConsolidationActivity.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateSingleFoundryActivity.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateSingleGovernanceActivity.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateSingleNftActivity.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateVestingActivity.ts, packages/shared/lib/core/wallet/utils/outputs/preprocessIncomingTransaction.ts, packages/shared/lib/core/wallet/utils/outputs/preprocessOutgoingTransaction.ts, packages/shared/locales/en.json
Reverts iotaledger/firefly#8263
=> Revert "feat: add mana to txs in tx activities and activity details"

packages/shared/lib/core/wallet/utils/outputs/preprocessOutgoingTransaction.ts
Closes https://github.com/iotaledger/firefly/issues/8279
Context: https://github.com/iotaledger/iota-sdk/pull/2086
=> fix: Incorrect timestamp outgoing txs 

packages/shared/lib/core/api/interfaces/api.interface.ts, packages/shared/lib/core/network/utils/getNetworkIdFromNetworkName.ts, packages/shared/lib/core/profile/actions/getWallet.ts
Closes https://github.com/iotaledger/firefly/issues/8295
=> fix: Cannot read wallet options of undefined

packages/desktop/components/popups/CreateDelegationPopup.svelte, packages/desktop/views/dashboard/delegation/Delegation.svelte
- Avoid negative undelegated amount
- Improve mana cost calculation in delegation
- Prevent weird SDK errors
Close https://github.com/iotaledger/firefly/issues/8284
```
```
-   [ ] MacOS
-   [ ] Linux
...
-   [ ] I have commented my …
=> enhancement: polish delegation flow

packages/shared/lib/core/wallet/actions/buildWalletState.ts
Closes #8312 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: main account selection not persist after multiple changes and logout

packages/shared/lib/core/wallet/utils/generateActivity/helper/getTimelockDateFromOutput.ts, packages/shared/lib/core/wallet/utils/outputs/getExpirationDateFromOutput.ts, packages/shared/lib/core/wallet/utils/outputs/isOutputExpired.ts, packages/shared/lib/core/wallet/utils/outputs/isOutputTimeLocked.ts, packages/shared/lib/core/wallet/utils/send/validateSendConfirmation.ts, packages/shared/lib/core/wallet/utils/transactions/getSenderAddressFromInputs.ts
Closes #8305 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: remove ExpirationUnlockConditionTemp and TimelockUnlockConditionTemp

packages/shared/lib/core/wallet/actions/activities/linkTransactionsWithClaimingTransactions.ts, packages/shared/lib/core/wallet/actions/events-handlers/handleNewOutputEvent.ts, packages/shared/lib/core/wallet/actions/events-handlers/handleSpentOutputEvent.ts
Closes #8308 
Closes #8283 
...
```
```
-   [ ] MacOS
-   [ ] Linux
...
-   [ ] I …
=> fix: claimed nfts in tx history

packages/shared/components/activity-info/GenericActivityInformation.svelte, packages/shared/lib/core/wallet/tests/formatTokenAmountDefault.test.ts, packages/shared/lib/core/wallet/utils/formatTokenAmountDefault.ts, packages/shared/lib/core/wallet/utils/index.ts, packages/shared/lib/core/wallet/utils/isOutputOfSelectedWalletAddress.ts, packages/shared/lib/core/wallet/utils/outputs/preprocessIncomingTransaction.ts, packages/shared/lib/core/wallet/utils/outputs/preprocessOutgoingTransaction.ts
Closes #8282 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: mana in block issued

packages/desktop/components/popups/MintNativeTokenFormPopup.svelte
Closes #8302 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: remove account selection from mint native tokens devtools

packages/desktop/components/popups/ClaimDelegationRewardsPopup.svelte, packages/desktop/views/dashboard/delegation/Delegation.svelte
> Closes #8327  and closes #8328 
...
```
```
-   [ ] MacOS
-   [ ] Linux
...
-   [ ] I …
=> fix: mana rewards units

packages/desktop/components/ManaBox.svelte, packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/FundConfirmationView.svelte, packages/shared/lib/core/network/utils/getImplicitAccountsMana.ts
Closes #8324 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: generating mana with multiple implicit accounts

packages/desktop/components/AccountManagementList.svelte, packages/desktop/components/popups/ImplicitAccountAddressPopup.svelte, packages/desktop/components/popups/Popup.svelte, packages/shared/lib/auxiliary/popup/enums/popup-id.enum.ts, packages/shared/locales/en.json
Closes #8342 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: add popup to create a new account

packages/shared/locales/en.json
Closes https://github.com/iotaledger/firefly/issues/8346
=> fix: Update i18 key for conflicting account creation

packages/desktop/components/popups/ActivityDetailsPopup.svelte, packages/desktop/components/popups/BurnNativeTokensConfirmationPopup.svelte, packages/desktop/components/popups/ClaimDelegationRewardsPopup.svelte, packages/desktop/components/popups/CreateDelegationPopup.svelte, packages/desktop/components/popups/MintNativeTokenConfirmationPopup.svelte, packages/desktop/components/popups/MintNftConfirmationPopup.svelte, packages/desktop/components/popups/send/SendConfirmationPopup.svelte, packages/desktop/views/dashboard/Dashboard.svelte, packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/AccountCreationView.svelte, packages/desktop/views/onboarding/views/restore-profile/views/ClaimFinderView.svelte, packages/shared/locales/en.json
> Closes #8345 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: display bic negative warning in all popups that issue a block

packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/AccountCreationView.svelte
Closes #8349 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: generating mana after activating the account

packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/AccountCreationView.svelte
Closes #8364 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: hasMainAccountNegativeBIC in activate account

packages/shared/components/NftMedia.svelte, packages/shared/lib/core/profile/classes/DirectoryManager.ts
Closes https://github.com/iotaledger/firefly/issues/8359
=> fix: Use correct base path for non-dev images

packages/shared/lib/core/wallet/utils/generateActivity/generateSingleAccountActivity.ts
Closes #8281 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: storage deposit in mint account tx details

packages/desktop/components/popups/BalanceBreakdownPopup.svelte, packages/shared/locales/en.json
Closes #8369 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: add Delegation to storage deposit in balance breakdown

packages/shared/package.json, yarn.lock
Closes https://github.com/iotaledger/firefly/issues/8389
=> chore: Update to @iota/sdk alpha-6

packages/desktop/components/modals/AccountActionsMenu.svelte, packages/desktop/components/popups/BalanceFinderPopup.svelte, packages/desktop/features/onboarding.features.ts, packages/desktop/views/onboarding/views/network-setup/views/ChooseNetworkView.svelte, packages/shared/components/AssetIcon.svelte, packages/shared/components/NetworkIcon.svelte, packages/shared/lib/auxiliary/icon/constants/network-icon-svg.ts, packages/shared/lib/core/layer-2/enums/destination-network.enum.ts, packages/shared/lib/core/ledger/stores/ledger-app-name.store.ts, packages/shared/lib/core/market/utils/getMarketCoinByNetworkId.ts, packages/shared/lib/core/network/constants/chronicle-urls.constant.ts, packages/shared/lib/core/network/constants/coin-type.constant.ts, packages/shared/lib/core/network/constants/default-base-token.constant.ts, packages/shared/lib/core/network/constants/default-chain-configurations.constant.ts, packages/shared/lib/core/network/constants/default-network-metadata.constant.ts, packages/shared/lib/core/network/constants/explorer-urls.constant.ts, packages/shared/lib/core/network/constants/faucet-urls.constant.ts, packages/shared/lib/core/network/constants/official-node-urls.constant.ts, packages/shared/lib/core/network/enums/chain-id.enum.ts, packages/shared/lib/core/network/enums/network-id.enum.ts, packages/shared/lib/core/network/enums/token-supply.enum.ts, packages/shared/lib/core/network/tests/network.test.ts, packages/shared/lib/core/network/utils/getEnabledNetworkFromFeatureFlags.ts, packages/shared/lib/core/network/utils/getNetworkIdFromNetworkName.ts, packages/shared/lib/core/network/utils/getNetworkNameFromNetworkId.ts, packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts, packages/shared/lib/core/profile/constants/profile-version.constant.ts, packages/shared/lib/core/wallet/tests/getOutputParameters.test.ts, packages/shared/locales/en.json
Close https://github.com/iotaledger/firefly/issues/8384
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore: rename testnet to shimmer testnet, add new iota testnet network & add iota testnet evm

packages/shared/lib/core/network/constants/default-base-token.constant.ts, packages/shared/lib/core/network/constants/default-network-metadata.constant.ts, packages/shared/lib/core/network/utils/getNetworkIdFromNetworkName.ts
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore: update network params

packages/shared/package.json, yarn.lock
Closes https://github.com/iotaledger/firefly/issues/8400
=> chore: Update to @iota/sdk alpha-7

packages/shared/components/inputs/AssetDropdown.svelte
> Closes #8393 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> Fix: asset changes to base token when custom allotting mana

packages/shared/lib/core/profile/actions/active-profile/logout.ts
Closes https://github.com/iotaledger/firefly/issues/8398
Simply reset the routers before the resetting the stores.
=> fix: Fix auto logout errors

packages/desktop/components/popups/CreateDelegationPopup.svelte
…alidator
> Closes #8413 
...
```
```
-   [ ] MacOS
-   [ ] Linux
...
-   [ ] I have …
=> fix: unable to delegate when entering first the amount and then the validator

packages/desktop/views/dashboard/delegation/Delegation.svelte
> Closes #8412 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: inconsistency between available and undelegated balance

packages/shared/lib/core/wallet/utils/getDefaultTransactionOptions.ts
Close https://github.com/iotaledger/firefly/issues/8414
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: use `ReuseAddress` as remainderValueStrategy

packages/shared/package.json, yarn.lock
Closes https://github.com/iotaledger/firefly/issues/8435
=> chore: Update to @iota/sdk alpha-8

packages/shared/components/Idle.svelte, packages/shared/lib/contexts/onboarding/actions/completeOnboardingProcess.ts, packages/shared/lib/contexts/settings/actions/deleteProfile.ts, packages/shared/lib/core/profile/actions/active-profile/login.ts, packages/shared/lib/core/profile/actions/active-profile/logout.ts
Closes https://github.com/iotaledger/firefly/issues/8429
=> fix: Always remove active profile on logout

packages/desktop/components/popups/CreateDelegationPopup.svelte
Closes #8431 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: confirm button in create delegation popup

packages/desktop/features/onboarding.features.ts
Closes https://github.com/iotaledger/firefly/issues/8440
=> chore: Disable ledger for now

packages/desktop/features/onboarding.features.ts
Closes https://github.com/iotaledger/firefly/issues/8444
=> chore: Disable custom network profiles

packages/desktop/views/dashboard/delegation/Delegation.svelte, packages/shared/locales/en.json
> Closes #8443 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: add delegation tooltip

packages/shared/lib/core/profile/stores/hasStrongholdLocked.store.ts
Closes https://github.com/iotaledger/firefly/issues/8449
=> fix: Cannot destructure property stronghold timeout

packages/shared/lib/core/wallet/types/activities/base-activity.type.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateSingleNftActivity.ts, packages/shared/lib/core/wallet/utils/generateActivity/helper/getSubjectFromActivity.ts
> Closes #8460 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: update `to Wallet x` until we have multiwallet to account address

packages/shared/locales/en.json
Closes #8463 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: gifted storage deposit literal

packages/shared/components/DelegationActivityDetails.svelte, packages/shared/lib/core/wallet/enums/activity-action.enum.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateActivities.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateActivitiesFromDelegationOutputs.ts, packages/shared/lib/core/wallet/utils/getActivityTileTitle.ts, packages/shared/locales/en.json
> Closes #8442 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: show claimed mana rewards activity

packages/shared/lib/core/wallet/utils/generateActivity/generateActivitiesFromBasicOutputs.ts
Closes https://github.com/iotaledger/firefly/issues/8467
Depends on https://github.com/iotaledger/firefly/pull/8426
=> fix: Consolidation activities

packages/desktop/components/popups/BalanceBreakdownPopup.svelte, packages/desktop/components/popups/ConsolidateOutputsPopup.svelte, packages/desktop/components/popups/Popup.svelte, packages/shared/lib/auxiliary/popup/enums/popup-id.enum.ts
Closes #8466 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: add mana cost to consolidate popup

packages/shared/lib/core/wallet/utils/generateActivity/generateActivitiesFromBasicOutputs.ts
Reverts iotaledger/firefly#8468
=> Revert "fix: Consolidation activities"

packages/desktop/components/modals/WalletActionsMenu.svelte
Closes #8483 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: disable withdraw from L2

packages/shared/lib/core/wallet/actions/getWalletAssetsForSelectedWallet.ts
> Closes #8485 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: remove conversion to fiat on testnet

packages/desktop/components/ManaBox.svelte
Close https://github.com/iotaledger/firefly/issues/8479
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: enough mana in mana box

packages/desktop/components/ManaBox.svelte, packages/desktop/views/dashboard/wallet/views/implicit-account-creation-multistep/FundConfirmationView.svelte, packages/shared/locales/en.json
Closes #8486 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: improve mana cost calculation error

packages/shared/lib/core/wallet/enums/activity-action.enum.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateActivities.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateActivitiesFromDelegationOutputs.ts, packages/shared/lib/core/wallet/utils/generateActivity/generateSingleDelegationActivity.ts, packages/shared/lib/core/wallet/utils/getActivityTileTitle.ts, packages/shared/locales/en.json
Closes #8473 
Closes #8470 
...
```
```
-   [ ] MacOS
-   [ ] Linux
...
-   [ ] I …
=> feat: review mana accuracy

packages/desktop/components/popups/CreateDelegationPopup.svelte
Close https://github.com/iotaledger/firefly/issues/8487
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: re-calculate mana cost with delegated amount change

packages/desktop/views/dashboard/delegation/Delegation.svelte
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> hotfix: prevent delegation fetch error crash

packages/shared/components/labels/TogglableAssetBalanceLabel.svelte
> Closes #8500 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> feat: fix available balance toggle on tesnet and custom network

packages/shared/lib/core/api/interfaces/api.interface.ts, packages/shared/lib/core/network/utils/getPassiveManaForOutput.ts
Closes #8473 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: mana accuracy in transaction details

packages/desktop/package.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> release: desktop shimmer 2.1.15

packages/desktop/package.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> release: desktop iota 2.0.10

packages/shared/lib/core/wallet/utils/getAccountTransactionOptions.ts, packages/shared/lib/core/wallet/utils/getDefaultTransactionOptions.ts
Closes #8515 
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> fix: issuer id in transaction options

packages/desktop/package.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore: bump version to 3.0.0-beta-2

packages/shared/lib/core/network/constants/explorer-urls.constant.ts
Closes https://github.com/iotaledger/firefly/issues/8518
=> chore: update iota 2.0 testnet explorer

.github/workflows/build-and-release-desktop.yml, .github/workflows/build-desktop-test.v2.yml, .github/workflows/build-desktop.yml, .github/workflows/ci.lint.yml, .github/workflows/ci.snyk.yml, .github/workflows/ci.test.yml, .github/workflows/ci.ts.yml, .github/workflows/handbook.yml, packages/desktop/package.json
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore: bump version to 2.2.0-alpha-1 & update ubuntu gh actions to LTS 22

.github/workflows/build-and-release-desktop.yml, .github/workflows/build-desktop-test.v1.yml, .github/workflows/build-desktop.yml
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore: pin actions/upload-artifact to v4.4.3

.github/workflows/build-and-release-desktop.yml, packages/desktop/package.json
Uses external code signing server using FIPS compliant secure hardware
=> chore: updated windows code signing

packages/shared/package.json, yarn.lock
Close https://github.com/iotaledger/firefly/issues/8667
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore: update iota-sdk

.github/workflows/build-and-release-desktop.yml
...
```
```
-   [ ] MacOS
-   [ ] Linux
... …
=> chore: bump download-artifact to v4

README.md
Add repo deprecated disclaimer
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
=> chore: add repo deprecation disclaimer

packages/desktop/components/popups/AppDeprecationPopup.svelte, packages/desktop/components/popups/GetSeedPopup.svelte, packages/desktop/components/popups/UnlockStrongholdPopup.svelte, packages/desktop/views/dashboard/Dashboard.svelte, packages/shared/components/modals/InitProfileActionsModal.svelte, packages/shared/lib/contexts/onboarding/actions/initialiseProfileManagerFromOnboardingProfile.ts, packages/shared/lib/core/error/constants/error-regex.constant.ts, packages/shared/lib/core/error/enums/client-error.enum.ts, packages/shared/lib/core/profile-manager/utils/getSecretManagerFromProfileType.ts
=> fix: add stronghold migration for seed backup

packages/desktop/views/login/views/EnterPinView.svelte, packages/shared/components/modals/InitProfileActionsModal.svelte
=> fix: reseting active profile and profile manager
